import type { StringTable } from '../../i18n/types';

/** Binder strings (C-20, C-21, C-22, L-31), en + es from the start (P-13). Keys are namespaced `binder.*`. */
export const strings: StringTable = {
  // nav + page headers
  'binder.nav': { en: 'Binder', es: 'Carpeta' },
  'binder.navRequests': { en: 'To do', es: 'Pendiente' },
  'binder.title': { en: 'My binder', es: 'Mi carpeta' },
  'binder.subtitle': { en: 'Everything about your case in one place: what you sent us, what we filed, and what was served.', es: 'Todo sobre su caso en un solo lugar: lo que nos envió, lo que presentamos y lo que se notificó.' },
  'binder.mapTitle': { en: 'Binder map', es: 'Mapa de la carpeta' },
  'binder.mapSubtitle': { en: 'Everything you have, laid out along the stages of your case.', es: 'Todo lo que tiene, colocado a lo largo de las etapas de su caso.' },
  'binder.requestsTitle': { en: 'What we need', es: 'Lo que necesitamos' },
  'binder.requestsSubtitle': { en: 'The office asked for these. Each one takes a minute.', es: 'La oficina pidió esto. Cada cosa toma un minuto.' },
  'binder.addTitle': { en: 'Add to your binder', es: 'Agregar a su carpeta' },
  'binder.addSubtitle': { en: 'Photos, papers, emails or text messages - whatever you have.', es: 'Fotos, papeles, correos o mensajes de texto: lo que tenga.' },
  'binder.staffTitle': { en: 'Client binder', es: 'Carpeta del cliente' },
  'binder.staffIndexTitle': { en: 'Client binders', es: 'Carpetas de clientes' },
  'binder.staffIndexSubtitle': { en: 'What clients have sent in, case by case. New items come first.', es: 'Lo que los clientes han enviado, caso por caso. Lo nuevo primero.' },

  // filters and empty states
  'binder.search': { en: 'Search your binder', es: 'Buscar en su carpeta' },
  'binder.searchStaff': { en: 'Search this binder', es: 'Buscar en esta carpeta' },
  'binder.all': { en: 'Everything', es: 'Todo' },
  'binder.allPhases': { en: 'All stages', es: 'Todas las etapas' },
  'binder.count': { en: '{n} items', es: '{n} elementos' },
  'binder.countOne': { en: '1 item', es: '1 elemento' },
  'binder.empty': { en: 'Your binder is empty', es: 'Su carpeta está vacía' },
  'binder.emptyBody': { en: 'Add a photo of the notice, your lease or a rent receipt and it will appear here.', es: 'Agregue una foto del aviso, su contrato o un recibo de renta y aparecerá aquí.' },
  'binder.noMatches': { en: 'Nothing matches that', es: 'Nada coincide con eso' },
  'binder.noMatchesBody': { en: 'Try another word, or clear the filters.', es: 'Pruebe otra palabra o borre los filtros.' },
  'binder.clearFilters': { en: 'Clear filters', es: 'Borrar filtros' },

  // buttons
  'binder.add': { en: 'Add to binder', es: 'Agregar a la carpeta' },
  'binder.openMap': { en: 'Map view', es: 'Vista de mapa' },
  'binder.openList': { en: 'List view', es: 'Vista de lista' },
  'binder.openRequests': { en: 'What we asked for', es: 'Lo que le pedimos' },
  'binder.zoomIn': { en: 'Zoom in', es: 'Acercar' },
  'binder.zoomOut': { en: 'Zoom out', es: 'Alejar' },
  'binder.close': { en: 'Close', es: 'Cerrar' },
  'binder.cancel': { en: 'Cancel', es: 'Cancelar' },
  'binder.save': { en: 'Save', es: 'Guardar' },
  'binder.back': { en: 'Back', es: 'Atrás' },

  // missing strip
  'binder.missing': { en: 'What is missing', es: 'Lo que falta' },
  'binder.missingBody': { en: 'The office is waiting for these before the next step.', es: 'La oficina espera esto antes del siguiente paso.' },
  'binder.nothingMissing': { en: 'Nothing is missing right now. Thank you.', es: 'No falta nada ahora mismo. Gracias.' },
  'binder.upload': { en: 'Upload', es: 'Subir' },
  'binder.due': { en: 'Needed by {date}', es: 'Se necesita para {date}' },
  'binder.overdue': { en: 'Overdue', es: 'Atrasado' },

  // item detail
  'binder.detailWhen': { en: 'When it happened', es: 'Cuándo pasó' },
  'binder.detailReceived': { en: 'Added to your binder', es: 'Agregado a su carpeta' },
  'binder.detailSource': { en: 'Where it came from', es: 'De dónde vino' },
  'binder.detailFile': { en: 'File', es: 'Archivo' },
  'binder.detailHash': { en: 'Fingerprint (SHA-256)', es: 'Huella (SHA-256)' },
  'binder.detailChain': { en: 'What happened to it', es: 'Qué pasó con esto' },
  'binder.detailThread': { en: 'The conversation', es: 'La conversación' },
  'binder.detailNote': { en: 'Note from the office', es: 'Nota de la oficina' },
  'binder.detailSquare': { en: 'Stage of your case', es: 'Etapa de su caso' },
  'binder.detailNoPreview': { en: 'The office holds the original; this is the preview kept in the app.', es: 'La oficina tiene el original; esta es la vista previa guardada en la aplicación.' },
  'binder.messages': { en: '{n} messages', es: '{n} mensajes' },

  // requests (C-21)
  'binder.reqOpen': { en: 'Still needed', es: 'Todavía pendiente' },
  'binder.reqDone': { en: 'Done', es: 'Hecho' },
  'binder.reqNone': { en: 'Nothing to do right now', es: 'Nada que hacer ahora mismo' },
  'binder.reqNoneBody': { en: 'When the office needs something from you, it appears here and on your home screen.', es: 'Cuando la oficina necesite algo de usted, aparecerá aquí y en su pantalla de inicio.' },
  'binder.reqKindQuestion': { en: 'A question', es: 'Una pregunta' },
  'binder.reqKindItem': { en: 'Something to upload', es: 'Algo para subir' },
  'binder.reqKindReview': { en: 'Read your draft', es: 'Lea su borrador' },
  'binder.reqKindApproval': { en: 'Approve your draft', es: 'Apruebe su borrador' },
  'binder.reqKindSignature': { en: 'Sign', es: 'Firme' },
  'binder.reqKindPayment': { en: 'Payment', es: 'Pago' },
  'binder.reqAnswer': { en: 'Answer', es: 'Responder' },
  'binder.reqAnswerLabel': { en: 'Your answer', es: 'Su respuesta' },
  'binder.reqAnswerHint': { en: 'Approximate is fine. Write it the way you would say it.', es: 'Aproximado está bien. Escríbalo como lo diría.' },
  'binder.reqSend': { en: 'Send answer', es: 'Enviar respuesta' },
  'binder.reqOpenOrder': { en: 'Open the document', es: 'Abrir el documento' },
  'binder.reqReceived': { en: 'Received, thank you', es: 'Recibido, gracias' },
  'binder.reqAnswered': { en: 'Answered', es: 'Respondido' },
  'binder.reqUploaded': { en: 'You uploaded: {title}', es: 'Usted subió: {title}' },
  'binder.reqAsked': { en: 'Asked {date}', es: 'Pedido el {date}' },

  // add (C-22)
  'binder.addUpload': { en: 'Upload files', es: 'Subir archivos' },
  'binder.addUploadBody': { en: 'Photos, PDFs, anything on your phone or computer.', es: 'Fotos, PDF, lo que tenga en su teléfono o computadora.' },
  'binder.addPhoto': { en: 'Take a photo', es: 'Tomar una foto' },
  'binder.addPhotoBody': { en: 'Opens your camera. Good for a notice on the door or damage in the apartment.', es: 'Abre su cámara. Ideal para un aviso en la puerta o daños en el apartamento.' },
  'binder.addEmail': { en: 'Connect your email', es: 'Conectar su correo' },
  'binder.addEmailBody': { en: 'So we can find the messages you sent the landlord without you hunting for them.', es: 'Para encontrar los mensajes que envió al arrendador sin que usted los busque.' },
  'binder.addTexts': { en: 'Import text messages', es: 'Importar mensajes de texto' },
  'binder.addTextsBody': { en: 'Export them from your phone, or simply paste the conversation.', es: 'Expórtelos de su teléfono o simplemente pegue la conversación.' },
  'binder.addWhatsapp': { en: 'WhatsApp export', es: 'Exportación de WhatsApp' },
  'binder.addWhatsappBody': { en: 'Use "Export chat" in WhatsApp and choose "Without media", then upload the .txt file.', es: 'Use "Exportar chat" en WhatsApp y elija "Sin archivos", luego suba el archivo .txt.' },
  'binder.addForward': { en: 'Forward-to address', es: 'Dirección para reenviar' },
  'binder.addForwardBody': { en: 'Forward any email to this address and it lands in your binder.', es: 'Reenvíe cualquier correo a esta dirección y llegará a su carpeta.' },
  'binder.connect': { en: 'Connect', es: 'Conectar' },
  'binder.connected': { en: 'Connected', es: 'Conectado' },
  'binder.pendingConsent': { en: 'Waiting for your permission', es: 'Esperando su permiso' },
  'binder.notConnected': { en: 'Not connected', es: 'No conectado' },
  'binder.disconnect': { en: 'Disconnect', es: 'Desconectar' },
  'binder.consentTitle': { en: 'Before we read anything', es: 'Antes de leer nada' },
  'binder.consentRead': { en: 'What we read: only messages between you and the people in your case (your landlord, the manager, the property company) and only from the date you moved in.', es: 'Qué leemos: solo mensajes entre usted y las personas de su caso (su arrendador, el administrador, la empresa) y solo desde la fecha en que se mudó.' },
  'binder.consentStore': { en: 'What we keep: the text of those messages, their dates and who sent them, in your binder.', es: 'Qué guardamos: el texto de esos mensajes, sus fechas y quién los envió, en su carpeta.' },
  'binder.consentNever': { en: 'What we never touch: your bank, your medical mail, your family and anything else in your inbox. We never send email as you.', es: 'Qué nunca tocamos: su banco, su correo médico, su familia y todo lo demás en su bandeja. Nunca enviamos correos como usted.' },
  'binder.consentStop': { en: 'You can disconnect at any time, and you can delete anything you added while it is still under review.', es: 'Puede desconectar cuando quiera y puede borrar lo que agregó mientras siga en revisión.' },
  'binder.consentAgree': { en: 'I understand and agree', es: 'Entiendo y acepto' },
  'binder.consentRecorded': { en: 'Your permission was recorded on {date}.', es: 'Su permiso se registró el {date}.' },
  'binder.pasteTitle': { en: 'Paste a conversation', es: 'Pegar una conversación' },
  'binder.pasteBody': { en: 'Open the conversation on your phone, select all, copy, and paste it here. Lines like "[Sep 12] Alex: the plumber comes Tuesday" are read automatically.', es: 'Abra la conversación en su teléfono, seleccione todo, copie y péguelo aquí. Las líneas como "[12 sep] Alex: el plomero viene el martes" se leen automáticamente.' },
  'binder.pasteLabel': { en: 'The conversation', es: 'La conversación' },
  'binder.pasteWho': { en: 'Who is the other person?', es: '¿Quién es la otra persona?' },
  'binder.pasteWhoHint': { en: 'The landlord, the manager, the company - however their name appears in the messages.', es: 'El arrendador, el administrador, la empresa: como aparezca su nombre en los mensajes.' },
  'binder.pasteMine': { en: 'How do your own messages appear?', es: '¿Cómo aparecen sus propios mensajes?' },
  'binder.pasteMineHint': { en: 'Usually "Me" or your first name.', es: 'Normalmente "Yo" o su nombre.' },
  'binder.importFile': { en: 'Upload an export file (.txt, .csv, .json)', es: 'Subir un archivo exportado (.txt, .csv, .json)' },
  'binder.importWaFile': { en: 'Upload the WhatsApp .txt export', es: 'Subir la exportación .txt de WhatsApp' },
  'binder.importReview': { en: 'Check before saving', es: 'Revise antes de guardar' },
  'binder.importCount': { en: '{n} messages', es: '{n} mensajes' },
  'binder.importRange': { en: 'From {range}', es: 'Del {range}' },
  'binder.importPeople': { en: 'People: {people}', es: 'Personas: {people}' },
  'binder.importUnparsed': { en: '{n} lines we could not read were kept exactly as they are.', es: '{n} líneas que no pudimos leer se guardaron tal cual.' },
  'binder.importSave': { en: 'Add these messages to my binder', es: 'Agregar estos mensajes a mi carpeta' },
  'binder.importNothing': { en: 'We could not find any messages in that. Check the text and try again.', es: 'No encontramos mensajes ahí. Revise el texto e inténtelo de nuevo.' },
  'binder.importSaved': { en: 'Saved. The office will review it.', es: 'Guardado. La oficina lo revisará.' },
  'binder.iphoneSteps': { en: 'iPhone: open the conversation, tap the contact at the top, then export with a tool like iMazing, or press and hold a message, "More", select all, forward to yourself and copy.', es: 'iPhone: abra la conversación, toque el contacto arriba y exporte con una herramienta como iMazing, o mantenga pulsado un mensaje, "Más", seleccione todo, reenvíelo a usted mismo y cópielo.' },
  'binder.androidSteps': { en: 'Android: use "SMS Backup & Restore" and export as XML or CSV, or open Messages on the web, select the conversation and copy it.', es: 'Android: use "SMS Backup & Restore" y exporte en XML o CSV, o abra Mensajes en la web, seleccione la conversación y cópiela.' },
  'binder.uploadSaved': { en: 'Added to your binder. The office will review it.', es: 'Agregado a su carpeta. La oficina lo revisará.' },

  // staff (L-31)
  'binder.queue': { en: 'To review', es: 'Por revisar' },
  'binder.queueEmpty': { en: 'Nothing waiting', es: 'Nada pendiente' },
  'binder.queueEmptyBody': { en: 'Everything the client sent has been reviewed.', es: 'Todo lo que el cliente envió ya fue revisado.' },
  'binder.tabQueue': { en: 'Review queue', es: 'Cola de revisión' },
  'binder.tabBinder': { en: 'The binder', es: 'La carpeta' },
  'binder.tabConnections': { en: 'Connections', es: 'Conexiones' },
  'binder.accept': { en: 'Accept into the binder', es: 'Aceptar en la carpeta' },
  'binder.acceptShort': { en: 'Accept', es: 'Aceptar' },
  'binder.reject': { en: 'Reject', es: 'Rechazar' },
  'binder.rejectTitle': { en: 'Tell the client what is wrong', es: 'Dígale al cliente qué falta' },
  'binder.rejectNote': { en: 'What the client will read', es: 'Lo que el cliente va a leer' },
  'binder.rejectHint': { en: 'Plain words, and say what to send instead.', es: 'Palabras claras, y diga qué enviar en su lugar.' },
  'binder.exhibit': { en: 'Exhibit letter', es: 'Letra de la prueba' },
  'binder.exhibitAuto': { en: 'Next free letter', es: 'Siguiente letra libre' },
  'binder.square': { en: 'Board square', es: 'Casilla del tablero' },
  'binder.chain': { en: 'Chain of custody', es: 'Cadena de custodia' },
  'binder.thread': { en: 'Thread', es: 'Conversación' },
  'binder.requestMore': { en: 'Request more', es: 'Pedir más' },
  'binder.requestMoreTitle': { en: 'Ask the client for something', es: 'Pedir algo al cliente' },
  'binder.requestPrompt': { en: 'What do you need?', es: '¿Qué necesita?' },
  'binder.requestPromptHint': { en: 'How the client will read it, e.g. "Photo of the envelope, front and back".', es: 'Como lo leerá el cliente, por ejemplo "Foto del sobre, frente y reverso".' },
  'binder.requestWhy': { en: 'Why we need it', es: 'Por qué lo necesitamos' },
  'binder.requestDue': { en: 'Needed by', es: 'Para cuándo' },
  'binder.requestVia': { en: 'Send it', es: 'Enviar por' },
  'binder.requestSend': { en: 'Send the request', es: 'Enviar la petición' },
  'binder.requestSent': { en: 'Request sent to the client', es: 'Petición enviada al cliente' },
  'binder.exportIndex': { en: 'Export binder index', es: 'Exportar índice de la carpeta' },
  'binder.exportTitle': { en: 'Binder index', es: 'Índice de la carpeta' },
  'binder.exportPrint': { en: 'Print', es: 'Imprimir' },
  'binder.exportNote': { en: 'Exhibits in order, with the date each thing happened and where it came from.', es: 'Pruebas en orden, con la fecha de cada cosa y su procedencia.' },
  'binder.download': { en: 'Download the original', es: 'Descargar el original' },
  'binder.newItems': { en: '{n} new', es: '{n} nuevos' },
  'binder.exhibits': { en: '{n} exhibits', es: '{n} pruebas' },
  'binder.exhibitsLabel': { en: 'Exhibits', es: 'Pruebas' },
  'binder.connectionsNone': { en: 'The client has not connected anything yet.', es: 'El cliente aún no ha conectado nada.' },
  'binder.itemsImported': { en: '{n} imported', es: '{n} importados' },
  'binder.consentNone': { en: 'No permission recorded: nothing may be read from this channel.', es: 'Sin permiso registrado: no se puede leer nada de este canal.' },
  'binder.openBinder': { en: 'Open the binder', es: 'Abrir la carpeta' },
  'binder.noCases': { en: 'No client binders yet', es: 'Aún no hay carpetas de clientes' },
  'binder.noCasesBody': { en: 'A binder appears as soon as a client adds their first photo or document.', es: 'Una carpeta aparece en cuanto un cliente agrega su primera foto o documento.' },
  'binder.byClient': { en: 'from the client', es: 'del cliente' },
  'binder.byOffice': { en: 'from the office', es: 'de la oficina' },
  'binder.acceptedAs': { en: 'Accepted as Exhibit {label}', es: 'Aceptado como prueba {label}' },
  'binder.rejected': { en: 'Rejected and sent back to the client', es: 'Rechazado y devuelto al cliente' },
};
