import type { StringTable } from '../../i18n/types';

/** LMS strings (C-40, C-41, C-42, L-40, A-11), en + es from the start (P-13). Keys namespaced `learning.*`. */
export const strings: StringTable = {
  // nav + shared
  'learning.nav': { en: 'Learn', es: 'Aprender' },
  'learning.navCounsel': { en: 'Client learning', es: 'Aprendizaje del cliente' },
  'learning.navAdmin': { en: 'Learning content', es: 'Contenido educativo' },
  'learning.play': { en: 'Play', es: 'Reproducir' },
  'learning.pause': { en: 'Pause', es: 'Pausa' },
  'learning.continue': { en: 'Continue', es: 'Continuar' },
  'learning.watch': { en: 'Watch', es: 'Ver' },
  'learning.read': { en: 'Read', es: 'Leer' },
  'learning.watched': { en: 'Watched', es: 'Visto' },
  'learning.markWatched': { en: 'Mark as watched', es: 'Marcar como visto' },
  'learning.markRead': { en: 'Mark as read', es: 'Marcar como leído' },
  'learning.minRead': { en: '{n} min read', es: '{n} min de lectura' },
  'learning.lessonsCount': { en: '{n} lessons', es: '{n} lecciones' },
  'learning.minutesCount': { en: '{n} min', es: '{n} min' },
  'learning.doneOf': { en: '{done} of {total}', es: '{done} de {total}' },
  'learning.article': { en: 'Article', es: 'Artículo' },
  'learning.video': { en: 'Video', es: 'Video' },
  'learning.source': { en: 'The library, its order and its groups are the firm’s own (caltenantlaw.com, read on 18 September 2026). The courses, the topics and the prep kit are our packaging of it and are not confirmed by the firm yet.', es: 'La biblioteca, su orden y sus grupos son del bufete (caltenantlaw.com, leído el 18 de septiembre de 2026). Los cursos, los temas y el kit de preparación son nuestra organización y el bufete aún no los ha confirmado.' },
  'learning.saved': { en: 'Saved', es: 'Guardado' },
  'learning.kind.series': { en: 'Series', es: 'Serie' },
  'learning.kind.topic': { en: 'Topic', es: 'Tema' },
  'learning.kind.reading': { en: 'Reading', es: 'Lectura' },
  'learning.kind.kit': { en: 'Kit', es: 'Kit' },

  // C-40
  'learning.title': { en: 'Learn', es: 'Aprender' },
  'learning.sub': { en: 'Every video and article the firm gives away, in the order that helps you most.', es: 'Todos los videos y artículos gratuitos del bufete, en el orden que más le ayuda.' },
  'learning.overall': { en: '{done} of {total} watched · {minutes} min of library', es: '{done} de {total} vistos · {minutes} min de biblioteca' },
  'learning.continueWatching': { en: 'Continue watching', es: 'Seguir viendo' },
  'learning.startHere': { en: 'Start here', es: 'Empiece aquí' },
  'learning.startHereBody': { en: 'Four videos and one article are what an attorney would otherwise spend your paid 30 minutes telling you.', es: 'Cuatro videos y un artículo son lo que un abogado le contaría en sus 30 minutos pagados.' },
  'learning.forYourStage': { en: 'For where you are on the board', es: 'Para donde está en el tablero' },
  'learning.forYourStageSub': { en: 'Your case is on “{square}”. These explain this square and what comes after it.', es: 'Su caso está en «{square}». Estos explican esta casilla y lo que sigue.' },
  'learning.forYourStageNone': { en: 'Once your case is on the board, the videos for your square appear here.', es: 'Cuando su caso esté en el tablero, aquí aparecerán los videos de su casilla.' },
  'learning.assignedTitle': { en: 'Assigned by your attorney', es: 'Asignado por su abogado' },
  'learning.assignedSub': { en: 'With the reason, in their words.', es: 'Con el motivo, en sus palabras.' },
  'learning.due': { en: 'By {date}', es: 'Para el {date}' },
  'learning.overdue': { en: 'Was due {date}', es: 'Vencía el {date}' },
  'learning.coursesTitle': { en: 'Courses', es: 'Cursos' },
  'learning.coursesSub': { en: 'The library, packaged.', es: 'La biblioteca, organizada.' },
  'learning.allTitle': { en: 'All videos and articles', es: 'Todos los videos y artículos' },
  'learning.searchLabel': { en: 'Search the library', es: 'Buscar en la biblioteca' },
  'learning.filterAll': { en: 'All', es: 'Todos' },
  'learning.filterWatched': { en: 'Watched', es: 'Vistos' },
  'learning.filterUnwatched': { en: 'Not watched', es: 'Sin ver' },
  'learning.groupAll': { en: 'Every group', es: 'Todos los grupos' },
  'learning.noResults': { en: 'Nothing matches that', es: 'Nada coincide' },
  'learning.noResultsBody': { en: 'Try a shorter word, or clear the filters.', es: 'Pruebe con una palabra más corta o quite los filtros.' },
  'learning.journey': { en: 'My journey', es: 'Mi recorrido' },
  'learning.journeyLink': { en: 'See the whole road', es: 'Ver todo el recorrido' },
  'learning.nextUpAnchor': { en: 'Next up', es: 'Lo siguiente' },

  // C-41
  'learning.journeyTitle': { en: 'Your learning journey', es: 'Su recorrido de aprendizaje' },
  'learning.journeySub': { en: 'The eviction game board, phase by phase, with what to watch at each one.', es: 'El tablero del desalojo, fase por fase, con qué ver en cada una.' },
  'learning.youAreHere': { en: 'You are here', es: 'Usted está aquí' },
  'learning.youAreHereBody': { en: 'Your case is on “{square}” in the {phase} phase.', es: 'Su caso está en «{square}», en la fase {phase}.' },
  'learning.noCase': { en: 'No case open yet — the whole road is ahead of you.', es: 'Aún no hay un caso abierto: todo el recorrido está por delante.' },
  'learning.phaseDone': { en: 'Behind you', es: 'Ya pasó' },
  'learning.phaseNow': { en: 'Where you are', es: 'Donde está' },
  'learning.phaseAhead': { en: 'Ahead', es: 'Por delante' },
  'learning.phaseNothing': { en: 'No video is mapped to this phase yet.', es: 'Todavía no hay ningún video asignado a esta fase.' },
  'learning.openBoard': { en: 'See the game board', es: 'Ver el tablero' },
  'learning.offBoard': { en: 'Not tied to a square', es: 'Sin casilla asignada' },
  'learning.offBoardSub': { en: 'Rights, repairs, deposits, moving out: useful whatever square you are on.', es: 'Derechos, reparaciones, depósitos, mudanza: útiles en cualquier casilla.' },

  // C-42
  'learning.backToLearn': { en: 'Learn', es: 'Aprender' },
  'learning.back10': { en: 'Back 10s', es: 'Atrás 10s' },
  'learning.forward10': { en: 'Forward 10s', es: 'Adelante 10s' },
  'learning.progressLabel': { en: 'Watched so far', es: 'Visto hasta ahora' },
  'learning.captions': { en: 'Captions and Spanish subtitles come from YouTube’s own player (the CC button).', es: 'Los subtítulos en inglés y español vienen del reproductor de YouTube (botón CC).' },
  'learning.keysHint': { en: 'Space plays and pauses. Left and right arrows move to the previous and next lesson.', es: 'La barra espaciadora reproduce y pausa. Las flechas izquierda y derecha cambian de lección.' },
  'learning.prevLesson': { en: 'Previous', es: 'Anterior' },
  'learning.nextLesson': { en: 'Next lesson', es: 'Siguiente lección' },
  'learning.notes': { en: 'Your notes', es: 'Sus notas' },
  'learning.notesSub': { en: 'Private to you. Bring them to your consultation.', es: 'Privadas. Llévelas a su consulta.' },
  'learning.notePlaceholder': { en: 'What do you want to ask about this?', es: '¿Qué quiere preguntar sobre esto?' },
  'learning.addNote': { en: 'Save note', es: 'Guardar nota' },
  'learning.noNotes': { en: 'No notes on this one yet.', es: 'Aún no hay notas aquí.' },
  'learning.noteAt': { en: 'at {time}', es: 'en {time}' },
  'learning.deleteNote': { en: 'Delete', es: 'Borrar' },
  'learning.askAbout': { en: 'Ask about this', es: 'Preguntar sobre esto' },
  'learning.transcript': { en: 'Transcript', es: 'Transcripción' },
  'learning.openYoutube': { en: 'Open on YouTube', es: 'Abrir en YouTube' },
  'learning.readOnSite': { en: 'Read it on caltenantlaw.com', es: 'Leerlo en caltenantlaw.com' },
  'learning.inCourse': { en: 'In this course', es: 'En este curso' },
  'learning.presenter': { en: 'Presented by {name}', es: 'Presentado por {name}' },
  'learning.playerNote': { en: 'The video plays here, on youtube-nocookie.com, and nothing starts until you press play. How far you watch is saved to your case file.', es: 'El video se reproduce aquí, en youtube-nocookie.com, y nada empieza hasta que usted lo pide. Lo que ve queda guardado en su expediente.' },
  'learning.lessonMissing': { en: 'That lesson is not in the library', es: 'Esa lección no está en la biblioteca' },

  // L-40
  'learning.l40Title': { en: 'Client learning', es: 'Aprendizaje del cliente' },
  'learning.l40Sub': { en: 'What each client has watched before you pick up the phone.', es: 'Qué ha visto cada cliente antes de que usted llame.' },
  'learning.tileClients': { en: 'Clients', es: 'Clientes' },
  'learning.tileReady': { en: 'Ready for their consultation', es: 'Listos para su consulta' },
  'learning.tileAssignments': { en: 'Open assignments', es: 'Asignaciones abiertas' },
  'learning.colClient': { en: 'Client', es: 'Cliente' },
  'learning.colWatched': { en: 'Watched', es: 'Visto' },
  'learning.colLast': { en: 'Last watched', es: 'Última vez' },
  'learning.colPrep': { en: 'Prep kit', es: 'Kit de preparación' },
  'learning.colAssigned': { en: 'Assigned', es: 'Asignado' },
  'learning.colSquare': { en: 'Square', es: 'Casilla' },
  'learning.ready': { en: 'Ready', es: 'Listo' },
  'learning.notReady': { en: 'Not yet', es: 'Aún no' },
  'learning.never': { en: 'Never', es: 'Nunca' },
  'learning.assign': { en: 'Assign a lesson', es: 'Asignar una lección' },
  'learning.assignShort': { en: 'Assign', es: 'Asignar' },
  'learning.unassign': { en: 'Cancel', es: 'Cancelar' },
  'learning.assignTitle': { en: 'Assign to {client}', es: 'Asignar a {client}' },
  'learning.assignCourse': { en: 'Course', es: 'Curso' },
  'learning.assignLesson': { en: 'Lesson', es: 'Lección' },
  'learning.assignReason': { en: 'Why, in words they will read', es: 'Por qué, en palabras que leerá' },
  'learning.assignReasonHint': { en: 'This is shown to the client exactly as you write it.', es: 'El cliente lo verá exactamente como usted lo escriba.' },
  'learning.assignDue': { en: 'By when', es: 'Para cuándo' },
  'learning.assignSave': { en: 'Assign', es: 'Asignar' },
  'learning.assignDone': { en: 'Assigned to {client}', es: 'Asignado a {client}' },
  'learning.unassigned': { en: 'Assignment cancelled', es: 'Asignación cancelada' },
  'learning.noClients': { en: 'No clients on your cases yet', es: 'Aún no hay clientes en sus casos' },
  'learning.noClientsBody': { en: 'Clients appear here as soon as a case is opened for them.', es: 'Los clientes aparecen aquí en cuanto se abre un caso.' },
  'learning.missingPrep': { en: 'Still to watch before the consultation', es: 'Falta ver antes de la consulta' },
  'learning.clientProgress': { en: 'Everything this client has watched', es: 'Todo lo que este cliente ha visto' },
  'learning.filterReady': { en: 'Ready', es: 'Listos' },
  'learning.filterNotReady': { en: 'Not ready', es: 'No listos' },
  'learning.privateNotes': { en: 'A client’s own notes stay private to them.', es: 'Las notas del cliente son privadas.' },

  // A-11
  'learning.a11Title': { en: 'Learning content', es: 'Contenido educativo' },
  'learning.a11Sub': { en: 'The courses, what is in them and in what order. Edited here, never in a file.', es: 'Los cursos, qué contienen y en qué orden. Se edita aquí, nunca en un archivo.' },
  'learning.colCourse': { en: 'Course', es: 'Curso' },
  'learning.colKind': { en: 'Kind', es: 'Tipo' },
  'learning.colLessons': { en: 'Lessons', es: 'Lecciones' },
  'learning.colMinutes': { en: 'Minutes', es: 'Minutos' },
  'learning.colAudience': { en: 'For', es: 'Para' },
  'learning.colPublished': { en: 'Published', es: 'Publicado' },
  'learning.published': { en: 'Published', es: 'Publicado' },
  'learning.unpublished': { en: 'Draft', es: 'Borrador' },
  'learning.audience.client': { en: 'Clients', es: 'Clientes' },
  'learning.audience.public': { en: 'Everyone', es: 'Todos' },
  'learning.audience.staff': { en: 'Staff', es: 'Equipo' },
  'learning.moveUp': { en: 'Move up', es: 'Subir' },
  'learning.moveDown': { en: 'Move down', es: 'Bajar' },
  'learning.required': { en: 'Required', es: 'Obligatoria' },
  'learning.optional': { en: 'Optional', es: 'Opcional' },
  'learning.unlockRule': { en: 'Opens', es: 'Se abre' },
  'learning.unlock.always': { en: 'Always', es: 'Siempre' },
  'learning.unlock.after_previous': { en: 'After the previous lesson', es: 'Tras la lección anterior' },
  'learning.unlock.at_stage': { en: 'At its board square', es: 'En su casilla del tablero' },
  'learning.remove': { en: 'Remove', es: 'Quitar' },
  'learning.addLesson': { en: 'Add a lesson from the library', es: 'Agregar una lección de la biblioteca' },
  'learning.addArticle': { en: 'Add an article', es: 'Agregar un artículo' },
  'learning.add': { en: 'Add', es: 'Agregar' },
  'learning.courseTitleLabel': { en: 'Title', es: 'Título' },
  'learning.courseSubtitleLabel': { en: 'One line under the title', es: 'Una línea bajo el título' },
  'learning.emptyCourse': { en: 'No lessons in this course yet', es: 'Este curso aún no tiene lecciones' },
  'learning.newCourse': { en: 'New course', es: 'Curso nuevo' },
  'learning.editCourse': { en: 'Edit', es: 'Editar' },
  'learning.editLesson': { en: 'Edit the lesson itself', es: 'Editar la lección' },
  'learning.showMore': { en: 'Show {n} more', es: 'Ver {n} más' },
};
