/** Learning (LMS) rules, prompt 0006 pass 2 wave A. Ids append-only. */
import { defineRules } from './types';

export const rules = defineRules([
  { id: 'RULE-LEARN-01', title: 'Progress belongs to the person, and it is measured', description: 'One `lesson_progress` row per person per lesson, written by id through the provider: the player reports the real position about every ten seconds and on pause, `watched_pct` never goes backwards, and `completed_at` is set at 90 % or more (or by the explicit "Mark as watched" fallback, which is also a write, never a local flag).', category: 'marketing', status: 'implemented', pages: ['C-40', 'C-42', 'L-40'], source: 'prompt 0006 (the LMS knows what a customer has and has not watched) · P-14', implementedIn: 'src/modules/learning/lib.ts (writeProgress), VideoPlayer onProgress' },
  { id: 'RULE-LEARN-02', title: 'Staff see a client\'s progress, never a stranger\'s', description: 'An attorney or paralegal sees learning progress only for clients on a case they are on; the owner and super admin see the whole network. Nobody but the person who wrote them sees `lesson_notes` (a note reaches staff only when the client sends it in a message).', category: 'marketing', status: 'implemented', pages: ['L-40', 'C-42'], source: 'prompt 0006 (staff see progress only for their clients) · RLS lines on lesson_progress / lesson_notes', implementedIn: 'src/modules/learning/lib.ts (useMyClients), schema/learning.ts rls' },
  { id: 'RULE-LEARN-03', title: 'A locked lesson is dimmed with its reason, never hidden', description: '`course_lessons.unlock_rule` is always | after_previous | at_stage. A lesson that is not open yet still appears, dimmed, saying why ("opens once your case reaches the discovery square"), and can still be opened: the free library is free, the order is guidance (RULE-LEARN-06).', category: 'marketing', status: 'implemented', pages: ['C-40', 'C-41', 'A-11'], source: 'prompt 0006 (locked-until-stage lessons shown dimmed with why) · P-09', implementedIn: 'src/modules/learning/lib.ts (unlockState)' },
  { id: 'RULE-LEARN-04', title: 'An assignment carries a reason and a due date', description: 'A `lesson_assignments` row always says who assigned it, why in the client\'s own language, and by when; the client app shows the reason next to the lesson. An assignment is never a charge and never blocks anything.', category: 'marketing', status: 'implemented', pages: ['L-40', 'C-40'], source: 'prompt 0006 (assign a lesson / course with reason and due)', implementedIn: 'src/data/schema/learning.ts lesson_assignments; L-40 assign modal' },
  { id: 'RULE-LEARN-05', title: 'Nothing autoplays with sound', description: 'The player is click-to-play: until a person presses Play it shows the poster and loads nothing from YouTube (no third-party frame, cookies or storage); Play creates the youtube-nocookie.com iframe with no third-party script. Sound starts only when a person asks for it. This holds on every surface, including the TV. (0.2.0: was a paused iframe with `autoplay=0`; the iframe itself threw a storage error in a third-party context.)', category: 'marketing', status: 'implemented', pages: ['C-42'], source: 'prompt 0006 (no autoplay with sound) · P-03', implementedIn: 'src/components/organism/VideoPlayer/VideoPlayer.tsx' },
  { id: 'RULE-LEARN-06', title: 'The curriculum order is the firm\'s, and where it is ours it says so', description: 'The two series and the group order come from caltenantlaw.com itself (docs/data/videos.json, scraped 2026-09-18, D-043) and are shown in that order. The four topic courses, the reading room and the consultation prep kit are our cut of the same library and are unverified until the firm confirms them; the pages say so and A-11 is where the firm corrects it. Ordering columns are `order_index` (D-036); `lessons.order` keeps its Pass 1 name until a rename pass.', category: 'marketing', status: 'in_dev', pages: ['C-40', 'A-11'], source: 'D-043 · D-036 · prompt 0006', implementedIn: 'src/data/seed/learning.ts COURSES; A-11 course builder' },
  { id: 'RULE-LEARN-07', title: 'The free library stays free and is never a paywall', description: 'Every lesson and article is watchable by any client without buying anything; the LMS recommends, it does not gate. The firm\'s own argument is that watching first makes the paid 30 minutes worth more, so the prep kit is a suggestion with a reason, not a requirement.', category: 'marketing', status: 'implemented', pages: ['C-40', 'C-41', 'L-40'], source: 'firm-site-digest §5 · prompt 0006', implementedIn: 'no gate exists in the module; unlock rules only dim' },
]);
