/**
 * Legal-memory seed from the firm brief (docs/legal/ carries the digests; the brief marks each with a currency
 * caveat). Every rule here is `requested` and `verify: true`: the system shows them as the firm's positions to be
 * confirmed, never as legal advice. Ids are append-only.
 */
import { defineRules } from './types';

export const rules = defineRules([
  { id: 'RULE-UD-01', title: 'UD response window', description: 'A tenant served with an unlawful detainer summons has a response window (the site quotes 10 court days after service, following AB 2347); the choices are motion to quash, demurrer or answer. Deadline math must use court days and exclude court holidays.', category: 'ud_procedure', status: 'requested', pages: ['GB-01', 'C-01', 'L-01'], source: 'docs/legal/ · brief §4 step 4, §6', authority: 'CCP §1167, AB 2347', verify: true },
  { id: 'RULE-UD-02', title: 'Trial set within 20 days of the answer', description: 'Once an answer is filed and trial is requested, the court sets trial within 20 days. The board and case timeline count from the answer filing date.', category: 'ud_procedure', status: 'requested', pages: ['GB-01', 'L-01'], source: 'docs/legal/ · brief §4 step 9', authority: 'CCP §1170.5', verify: true },
  { id: 'RULE-UD-03', title: 'Discovery cut-off five days before trial', description: 'Discovery in a UD closes five days before trial; the case timeline warns paralegals before the cut-off.', category: 'ud_procedure', status: 'requested', pages: ['S-01', 'L-01'], source: 'docs/legal/ · brief §4 step 6', authority: 'CCP §1170.8', verify: true },
  { id: 'RULE-UD-04', title: '5-day notice to vacate after judgment', description: 'After judgment for possession the sheriff posts a 5-day notice to vacate and returns 6 or more days later. A stay of execution is the hold-everything order that pauses this.', category: 'ud_procedure', status: 'requested', pages: ['GB-01', 'C-01'], source: 'docs/legal/ · brief §4 step 12', authority: 'CCP §715.010, §1174', verify: true },
  { id: 'RULE-UD-05', title: 'Default cannot be entered while a quash or writ is pending', description: 'A clerk may still enter default despite a pending motion to quash or petition for writ; the board shows the trap and the remedies (relief from default, ex parte stay).', category: 'ud_procedure', status: 'requested', pages: ['GB-01', 'L-01'], source: 'docs/legal/ · brief §4 step 5', authority: 'CCP §473, §418.10', verify: true },
  { id: 'RULE-NOTICE-01', title: 'Notice periods by basis', description: '3-day pay-or-quit / perform-or-quit / quit notices; 30-day for tenancies under a year and 60-day after a year (CC §1946.1); 90-day for tenants of foreclosed homes. Notice type drives the first square on the board.', category: 'notices', status: 'requested', pages: ['GB-01', 'C-01', 'F-01'], source: 'docs/legal/ · brief §6 notice types', authority: 'CCP §1161, CC §1946.1, PTFA 2009', verify: true },
  { id: 'RULE-NOTICE-02', title: 'Pay-or-quit notice must state the exact amount', description: 'A 3-day notice to pay rent or quit must state the exact amount due and the period; overstated amounts or included late fees make the notice defective.', category: 'notices', status: 'requested', pages: ['C-01', 'L-01'], source: 'docs/legal/ · brief §6', authority: 'CCP §1161(2)', verify: true },
  { id: 'RULE-DEPOSIT-01', title: 'Security deposit 21-day return', description: 'The landlord must return the deposit or an itemized statement within 21 days of move-out; bad-faith retention exposes up to twice the deposit in statutory damages plus actual damages. The kit targets the recovery flow in small claims.', category: 'deposits', status: 'requested', pages: ['C-01', 'P-01'], source: 'docs/legal/ · brief §6 security deposits', authority: 'CC §1950.5', verify: true },
  { id: 'RULE-DEPOSIT-02', title: 'Deposit capped at one month of rent', description: 'From 2024-07-01 most landlords may collect at most one month of rent as a security deposit (AB 12); intake flags a larger deposit as a claim.', category: 'deposits', status: 'requested', pages: ['F-01', 'C-01'], source: 'docs/legal/ · brief §6', authority: 'CC §1950.5 (AB 12)', verify: true },
  { id: 'RULE-RENT-01', title: 'Rent increase notice 30 / 90 days', description: 'Rent increases of 10 % or less need 30 days written notice; more than 10 % need 90 days. Statewide cap under the Tenant Protection Act is 5 % plus CPI, at most 10 %.', category: 'rent', status: 'requested', pages: ['C-01', 'P-01'], source: 'docs/legal/ · brief §6', authority: 'CC §827, CC §1947.12', verify: true },
  { id: 'RULE-HAB-01', title: 'Repair and deduct limit', description: 'A tenant may repair and deduct up to one month of rent, at most twice in twelve months, after reasonable notice; the site copy must not overstate this.', category: 'habitability', status: 'requested', pages: ['C-01', 'P-01'], source: 'docs/legal/ · brief §6 habitability', authority: 'CC §1941.1, §1942', verify: true },
  { id: 'RULE-PRIVACY-01', title: '24-hour written notice of entry', description: 'Landlord entry needs 24 hours written notice for an enumerated purpose; there is no general annual inspection right. Intake records entries as potential harassment evidence.', category: 'privacy', status: 'requested', pages: ['C-01', 'F-01'], source: 'docs/legal/ · brief §6 landlord entry', authority: 'CC §1954', verify: true },
  { id: 'RULE-INTAKE-01', title: 'Consultation is prepaid and time-boxed', description: 'The initial attorney consultation is a prepaid 30-minute block by phone or video; the hotline bills in 10-minute blocks separately. Nothing in the system presents a consultation as free legal advice.', category: 'intake', status: 'requested', pages: ['F-01', 'C-01', 'P-01'], source: 'brief §2.1, §2.2', verify: false },
]);
