import type { StringTable } from '../../i18n/types';

/**
 * Services catalog strings (P-10..P-12, A-10). Everything the app says is bilingual. Service titles, SKU numbers,
 * deliverables and "what you get" stay in the firm's English until the firm supplies Spanish: they are the firm's
 * own product copy, not ours to translate (the same rule the board applies to its squares).
 */
export const strings: StringTable = {
  'catalog.nav.services': { en: 'Services', es: 'Servicios' },
  'catalog.nav.how': { en: 'How it works', es: 'Cómo funciona' },
  'catalog.nav.admin': { en: 'Services catalog', es: 'Catálogo de servicios' },

  // Shared vocabulary
  'catalog.free': { en: 'Free', es: 'Gratis' },
  'catalog.noPrice': { en: 'Price not listed', es: 'Precio no publicado' },
  'catalog.noSku': { en: 'no SKU listed', es: 'sin número de SKU' },
  'catalog.unverified': { en: 'as listed on caltenantlaw.com on {date} · unverified', es: 'según caltenantlaw.com el {date} · sin verificar' },
  'catalog.unverifiedTip': { en: 'This price was read from the firm’s live website (caltenantlaw.com) on {date}. It is what the store posts, not a quote, and the firm has not yet confirmed it in CTL OS. An attorney sets "verified" in the catalog admin before it is presented as fact.', es: 'Este precio se leyó del sitio web del despacho (caltenantlaw.com) el {date}. Es lo que publica la tienda, no una cotización, y el despacho aún no lo ha confirmado en CTL OS. Un abogado lo marca como verificado en la administración del catálogo antes de presentarlo como un hecho.' },
  'catalog.verified': { en: 'verified', es: 'verificado' },
  'catalog.whereOnBoard': { en: 'Where this fits on the board', es: 'Dónde encaja en el tablero' },
  'catalog.offBoard': { en: 'Not a square on the eviction board — a matter of its own.', es: 'No es una casilla del tablero de desalojo: es un asunto aparte.' },
  'catalog.anyStage': { en: 'Any stage', es: 'Cualquier etapa' },
  'catalog.needsFirst': { en: 'Needs first', es: 'Requiere antes' },
  'catalog.turnaround': { en: 'Turnaround', es: 'Tiempo de entrega' },
  'catalog.details': { en: 'Details', es: 'Detalles' },
  'catalog.addToPlan': { en: 'Add to plan', es: 'Añadir al plan' },
  'catalog.addToPlanWhat': { en: 'add this service to your plan and check out', es: 'añadir este servicio a tu plan y pagar' },
  'catalog.backToMenu': { en: 'All services', es: 'Todos los servicios' },

  // P-10
  'catalog.p10.eyebrow': { en: 'Unbundled legal services · pay for the piece you need', es: 'Servicios legales por piezas · paga solo lo que necesitas' },
  'catalog.p10.title': { en: 'Legal help, one piece at a time', es: 'Ayuda legal, pieza por pieza' },
  'catalog.p10.lead': { en: 'No retainer, no hourly surprise. Every document, kit and consultation has a number and a price, filed under the stage of the eviction it belongs to. Buy the motion you need, do the rest yourself, and keep control of what it costs.', es: 'Sin anticipo ni sorpresas por hora. Cada documento, kit y consulta tiene un número y un precio, archivado en la etapa del desalojo a la que pertenece. Compra la moción que necesitas, haz el resto tú y mantén el control del costo.' },
  'catalog.p10.statServices': { en: 'Services on the menu', es: 'Servicios en el menú' },
  'catalog.p10.statPriced': { en: 'With a listed price', es: 'Con precio publicado' },
  'catalog.p10.statStages': { en: 'Stages of the board', es: 'Etapas del tablero' },
  'catalog.p10.stages': { en: 'Start where you are', es: 'Empieza donde estás' },
  'catalog.p10.stagesDesc': { en: 'The menu is organised like the game board. Pick the stage you are at and the menu narrows to what is used there.', es: 'El menú está organizado como el tablero. Elige tu etapa y el menú se reduce a lo que se usa ahí.' },
  'catalog.p10.allStages': { en: 'Every stage', es: 'Todas las etapas' },
  'catalog.p10.searchLabel': { en: 'Search the services', es: 'Buscar servicios' },
  'catalog.p10.searchPlaceholder': { en: 'Search a SKU, a document, a square…', es: 'Busca un SKU, un documento, una casilla…' },
  'catalog.p10.priceLabel': { en: 'Price', es: 'Precio' },
  'catalog.p10.priceAll': { en: 'Any price', es: 'Cualquiera' },
  'catalog.p10.priceFree': { en: 'Free', es: 'Gratis' },
  'catalog.p10.priceUnder': { en: 'Under $250', es: 'Menos de $250' },
  'catalog.p10.priceMid': { en: '$250–$600', es: '$250–$600' },
  'catalog.p10.priceOver': { en: 'Over $600', es: 'Más de $600' },
  'catalog.p10.priceNone': { en: 'Not listed', es: 'Sin precio' },
  'catalog.p10.unitLabel': { en: 'How it is charged', es: 'Cómo se cobra' },
  'catalog.p10.unitAll': { en: 'Any way', es: 'Cualquiera' },
  'catalog.p10.unitFlat': { en: 'Flat price', es: 'Precio fijo' },
  'catalog.p10.unitMinimum': { en: 'Minimum charge', es: 'Cargo mínimo' },
  'catalog.p10.unitHour': { en: 'Per hour', es: 'Por hora' },
  'catalog.p10.unit10': { en: 'Per 10 minutes', es: 'Por 10 minutos' },
  'catalog.p10.unitItem': { en: 'Each', es: 'Cada una' },
  'catalog.p10.unitDeposit': { en: 'Deposit', es: 'Depósito' },
  'catalog.p10.unitFree': { en: 'Free', es: 'Gratis' },
  'catalog.p10.clear': { en: 'Clear filters', es: 'Limpiar filtros' },
  'catalog.p10.compare': { en: 'Compare the kits', es: 'Comparar los kits' },
  'catalog.p10.compareHide': { en: 'Hide the comparison', es: 'Ocultar la comparación' },
  'catalog.p10.compareTitle': { en: 'The do-it-yourself kits, side by side', es: 'Los kits para hacerlo tú mismo, lado a lado' },
  'catalog.p10.compareDesc': { en: 'Same forms an attorney would use, with the instructions. The kits are the cheapest way to stay in the fight; the drafted documents are the same work done for you.', es: 'Los mismos formularios que usaría un abogado, con instrucciones. Los kits son la forma más barata de seguir en la pelea; los documentos redactados son ese mismo trabajo hecho por nosotros.' },
  'catalog.p10.colWhat': { en: 'What it is', es: 'Qué es' },
  'catalog.p10.colGet': { en: 'What you get', es: 'Qué recibes' },
  'catalog.p10.colWhere': { en: 'Used at', es: 'Se usa en' },
  'catalog.p10.count': { en: '{n} of {total} services', es: '{n} de {total} servicios' },
  'catalog.p10.noMatch': { en: 'Nothing on the menu matches that', es: 'Nada en el menú coincide' },
  'catalog.p10.noMatchBody': { en: 'Try a SKU number, the name of a document, or the square you are standing on.', es: 'Prueba con un número de SKU, el nombre de un documento o la casilla donde estás.' },
  'catalog.p10.sourceTitle': { en: 'About these prices', es: 'Sobre estos precios' },
  'catalog.p10.sourceBody': { en: 'Every figure here was read from the firm’s live website, caltenantlaw.com, on {date} (the /all-services list and the Ecwid store), and the firm has not yet confirmed it in CTL OS. Nothing on this page is a quote or legal advice, and buying a document does not create an attorney-client relationship on its own — the consultation does.', es: 'Cada cifra se leyó del sitio web del despacho, caltenantlaw.com, el {date} (la lista /all-services y la tienda Ecwid), y el despacho aún no la ha confirmado en CTL OS. Nada en esta página es una cotización ni asesoría legal, y comprar un documento no crea por sí solo una relación abogado-cliente; la consulta sí.' },
  'catalog.p10.offBoardTitle': { en: 'Any stage, or a matter of its own', es: 'Cualquier etapa, o un asunto aparte' },

  // P-11
  'catalog.p11.eyebrow': { en: 'Service', es: 'Servicio' },
  'catalog.p11.notFound': { en: 'No service with that number', es: 'No hay servicio con ese número' },
  'catalog.p11.notFoundBody': { en: 'The menu may have been reorganised. Open the full list and search from there.', es: 'Puede que el menú se haya reorganizado. Abre la lista completa y busca desde ahí.' },
  'catalog.p11.whatYouGet': { en: 'What this buys you', es: 'Qué te da esto' },
  'catalog.p11.requirements': { en: 'Before we can do it', es: 'Antes de poder hacerlo' },
  'catalog.p11.boardTitle': { en: 'Where it sits on the board', es: 'Dónde está en el tablero' },
  'catalog.p11.boardDesc': { en: 'The squares this service belongs to, and the moves the board draws out of each one.', es: 'Las casillas a las que pertenece este servicio y los movimientos que el tablero dibuja desde cada una.' },
  'catalog.p11.nextMoves': { en: 'The board’s next moves from here', es: 'Los siguientes movimientos del tablero desde aquí' },
  'catalog.p11.noNextMoves': { en: 'A terminal square: the board stops here.', es: 'Casilla final: el tablero termina aquí.' },
  'catalog.p11.openBoard': { en: 'Open this square on the board', es: 'Abrir esta casilla en el tablero' },
  'catalog.p11.howTitle': { en: 'How to order it', es: 'Cómo pedirlo' },
  'catalog.p11.howDesc': { en: 'We read your papers before we draft against them. That is the order, every time.', es: 'Leemos tus papeles antes de redactar contra ellos. Ese es el orden, siempre.' },
  'catalog.p11.relatedTitle': { en: 'Also used at this stage', es: 'También se usa en esta etapa' },
  'catalog.p11.sourcesTitle': { en: 'Where these facts came from', es: 'De dónde salieron estos datos' },
  'catalog.p11.evidenceLive': { en: 'Read from the firm’s live store (caltenantlaw.com, Ecwid store 1197002) on {date}: title, price, description and order form exactly as posted. The firm has not yet confirmed it in CTL OS.', es: 'Leído de la tienda en vivo del despacho (caltenantlaw.com, tienda Ecwid 1197002) el {date}: título, precio, descripción y formulario tal como se publican. El despacho aún no lo ha confirmado en CTL OS.' },
  'catalog.p11.notIncluded': { en: 'Not included', es: 'No incluye' },
  'catalog.p11.productImage': { en: 'Product image as the store shows it', es: 'Imagen del producto tal como la muestra la tienda' },
  'catalog.firmIconNote': { en: 'Icons and category tiles are the firm’s own store artwork (caltenantlaw.com, scraped {date}); rights stay with the firm.', es: 'Los iconos y las fichas de categoría son las ilustraciones propias de la tienda del despacho (caltenantlaw.com, capturadas el {date}); los derechos son del despacho.' },
  'catalog.p11.evidenceSnippet': { en: 'Quoted from the firm’s indexed store listing.', es: 'Citado del listado indexado de la tienda del despacho.' },
  'catalog.p11.evidenceInferred': { en: 'Reconstructed from URLs, titles and partial snippets — treat it as a draft until the firm confirms it.', es: 'Reconstruido de URLs, títulos y fragmentos parciales: trátalo como borrador hasta que el despacho lo confirme.' },
  'catalog.p11.sourceLink': { en: 'Store listing', es: 'Listado de la tienda' },
  'catalog.p11.bookConsult': { en: 'Start with the consultation', es: 'Empieza con la consulta' },
  'catalog.p11.category': { en: 'Category', es: 'Categoría' },

  // P-12
  'catalog.p12.eyebrow': { en: 'How buying legal help works here', es: 'Cómo funciona comprar ayuda legal aquí' },
  'catalog.p12.title': { en: 'A legal vending machine', es: 'Una máquina expendedora legal' },
  'catalog.p12.lead': { en: 'Most firms sell you a lawyer by the hour and hope you do not ask what it adds up to. This one sells the pieces: watch the videos for free, pay for half an hour of an attorney’s attention, then buy only the documents your stage actually needs.', es: 'La mayoría de los despachos te venden un abogado por hora y esperan que no preguntes cuánto suma. Este vende las piezas: mira los videos gratis, paga media hora de atención de un abogado y luego compra solo los documentos que tu etapa realmente necesita.' },
  'catalog.p12.stepsTitle': { en: 'The order it goes in', es: 'El orden en que va' },
  'catalog.p12.step1': { en: 'Watch the free videos', es: 'Mira los videos gratis' },
  'catalog.p12.step1Body': { en: 'The whole eviction, explained by the attorney, before you pay anything. Rewind it, save it, watch it at 2am. Most people arrive at the consultation already knowing the vocabulary — which is exactly the point, and why the half hour is enough.', es: 'Todo el desalojo explicado por el abogado antes de pagar nada. Repítelo, guárdalo, míralo a las 2am. La mayoría llega a la consulta conociendo ya el vocabulario, que es justo la idea y por eso media hora alcanza.' },
  'catalog.p12.step2': { en: 'Fill in the intake form', es: 'Completa el formulario' },
  'catalog.p12.step2Body': { en: 'One form about your notice, your dates and your landlord. It becomes your file, not an email attachment. You get a copy and a link to the services page.', es: 'Un formulario sobre tu aviso, tus fechas y tu arrendador. Se convierte en tu expediente, no en un archivo adjunto. Recibes una copia y un enlace a la página de servicios.' },
  'catalog.p12.step3': { en: 'Half an hour with an attorney', es: 'Media hora con un abogado' },
  'catalog.p12.step3Body': { en: 'By phone or Microsoft Teams, with a licensed California tenant attorney. You read the notice out loud, we read the statute back, and you leave knowing the next move and what it costs.', es: 'Por teléfono o Microsoft Teams, con un abogado de inquilinos con licencia en California. Lees el aviso en voz alta, nosotros leemos la ley y sales sabiendo el siguiente paso y su costo.' },
  'catalog.p12.step4': { en: 'Buy the documents for your stage', es: 'Compra los documentos de tu etapa' },
  'catalog.p12.step4Body': { en: 'A motion to quash, a demurrer, an answer, discovery, trial papers — whatever the square you are standing on calls for. Each one has a number and a price. You buy one, not a package.', es: 'Una moción para anular, una excepción, una contestación, discovery, papeles de juicio: lo que pida la casilla donde estás. Cada uno tiene número y precio. Compras uno, no un paquete.' },
  'catalog.p12.step5': { en: 'Use the hotline for quick questions', es: 'Usa la línea directa para dudas rápidas' },
  'catalog.p12.step5Body': { en: 'Already a client and the question is short? Buy a block of minutes instead of a whole consultation. Unused minutes come back to you.', es: '¿Ya eres cliente y la pregunta es corta? Compra un bloque de minutos en vez de una consulta entera. Los minutos no usados se te devuelven.' },
  'catalog.p12.step6': { en: 'Add a court appearance if you want one', es: 'Añade una comparecencia si la quieres' },
  'catalog.p12.step6Body': { en: 'The firm does everything but go to court — and can arrange a lawyer to stand up for you when a hearing or trial needs one.', es: 'El despacho hace todo menos ir a la corte, y puede conseguir un abogado que te represente cuando una audiencia o un juicio lo requiera.' },
  'catalog.p12.returningTitle': { en: 'If you have been here before', es: 'Si ya has estado aquí' },
  'catalog.p12.returningBody': { en: 'Returning clients skip the first two steps: the follow-up consultation form, then a follow-up half hour with the attorney who already knows the file. Anything shorter than that goes to the hotline.', es: 'Los clientes que regresan se saltan los dos primeros pasos: el formulario de seguimiento y luego media hora con el abogado que ya conoce el expediente. Lo más corto que eso va a la línea directa.' },
  'catalog.p12.whyTitle': { en: 'Why sell it this way', es: 'Por qué venderlo así' },
  'catalog.p12.whyBody': { en: 'Because an eviction is a sequence of moves, not one big service — and because a renter fighting a landlord should never be told "it depends" when they ask what it costs. Every square of the board has a price on it, and you are the one who decides which squares you pay for.', es: 'Porque un desalojo es una secuencia de jugadas, no un gran servicio, y porque a un inquilino que pelea contra su arrendador nunca se le debe decir "depende" cuando pregunta cuánto cuesta. Cada casilla del tablero tiene precio y tú decides cuáles pagas.' },
  'catalog.p12.openMenu': { en: 'Open the services menu', es: 'Abrir el menú de servicios' },
  'catalog.p12.openBoard': { en: 'See the game board', es: 'Ver el tablero' },
  'catalog.p12.thisStep': { en: 'This step', es: 'Este paso' },
  'catalog.p12.costsAsListed': { en: 'What it costs, as listed', es: 'Lo que cuesta, según el sitio' },
  'catalog.p12.noCost': { en: 'Free', es: 'Gratis' },
  'catalog.p12.notWiredForm': { en: 'open the initial consultation form', es: 'abrir el formulario de consulta inicial' },

  // A-10
  'catalog.a10.title': { en: 'Services catalog', es: 'Catálogo de servicios' },
  'catalog.a10.subtitle': { en: 'The firm’s menu: prices, titles, availability and what an attorney has confirmed. Every edit is written by row id through the provider.', es: 'El menú del despacho: precios, títulos, disponibilidad y lo que un abogado ha confirmado. Cada edición se escribe por id de fila a través del proveedor.' },
  'catalog.a10.statTotal': { en: 'Services', es: 'Servicios' },
  'catalog.a10.statPriced': { en: 'With a price', es: 'Con precio' },
  'catalog.a10.statVerified': { en: 'Verified', es: 'Verificados' },
  'catalog.a10.statOffBoard': { en: 'Not on the board', es: 'Fuera del tablero' },
  'catalog.a10.searchLabel': { en: 'Search the catalog', es: 'Buscar en el catálogo' },
  'catalog.a10.tableTitle': { en: 'All services', es: 'Todos los servicios' },
  'catalog.a10.colSku': { en: 'SKU', es: 'SKU' },
  'catalog.a10.colTitle': { en: 'Title', es: 'Título' },
  'catalog.a10.colCategory': { en: 'Category', es: 'Categoría' },
  'catalog.a10.colStage': { en: 'Stage', es: 'Etapa' },
  'catalog.a10.colPrice': { en: 'Price (USD)', es: 'Precio (USD)' },
  'catalog.a10.colUnit': { en: 'Charged', es: 'Cobro' },
  'catalog.a10.colEvidence': { en: 'Evidence', es: 'Evidencia' },
  'catalog.a10.colVerified': { en: 'Verified', es: 'Verificado' },
  'catalog.a10.colActive': { en: 'On the menu', es: 'En el menú' },
  'catalog.a10.colOpen': { en: 'Public page', es: 'Página pública' },
  'catalog.a10.priceHint': { en: 'Whole dollars; empty means no price is listed', es: 'Dólares enteros; vacío significa sin precio publicado' },
  'catalog.a10.export': { en: 'Export CSV', es: 'Exportar CSV' },
  'catalog.a10.reset': { en: 'Reset from repo JSON', es: 'Restaurar desde el JSON del repo' },
  'catalog.a10.resetDone': { en: 'Catalog restored from docs/data/services-catalog.json ({n} rows changed)', es: 'Catálogo restaurado desde docs/data/services-catalog.json ({n} filas cambiadas)' },
  'catalog.a10.exported': { en: 'services-catalog.csv downloaded', es: 'services-catalog.csv descargado' },
  'catalog.a10.categoriesTitle': { en: 'Categories', es: 'Categorías' },
  'catalog.a10.categoriesDesc': { en: 'The order the public menu renders in. Up and down move a category; there is no drag-only control (P-03).', es: 'El orden en que se muestra el menú público. Arriba y abajo mueven una categoría; no hay control que solo funcione arrastrando (P-03).' },
  'catalog.a10.moveUp': { en: 'Move up', es: 'Subir' },
  'catalog.a10.moveDown': { en: 'Move down', es: 'Bajar' },
  'catalog.a10.servicesIn': { en: '{n} services', es: '{n} servicios' },
  'catalog.a10.sourceTitle': { en: 'Where the catalog comes from', es: 'De dónde viene el catálogo' },
  'catalog.a10.sourceBody': { en: 'docs/data/services-catalog.json is the catalog: a live scrape of caltenantlaw.com taken on {date} (98 rows: 96 store products + the hotline and hourly rates, 20 menu categories + the firm’s 28 hidden stage categories). This table edits a copy; the firm’s confirmed answers land back in the JSON in the same turn (RULE-CATALOG-04). Toggle “verified” once an attorney has checked a row.', es: 'docs/data/services-catalog.json es el catálogo: una captura en vivo de caltenantlaw.com del {date} (98 filas: 96 productos de la tienda + la línea directa y la tarifa por hora, 20 categorías del menú + las 28 categorías de etapa ocultas del despacho). Esta tabla edita una copia; las respuestas confirmadas del despacho vuelven al JSON en el mismo turno (RULE-CATALOG-04). Marca “verificado” cuando un abogado haya revisado la fila.' },
  'catalog.a10.saved': { en: 'Saved', es: 'Guardado' },

  'catalog.nav.outline': { en: 'Outline', es: 'Esquema' },
  'catalog.tbc': { en: 'To be confirmed', es: 'Por confirmar' },
  'catalog.tbcTip': { en: 'The firm has not told us this yet and the current website does not state it. It stays empty rather than guessed.', es: 'El despacho aún no nos lo ha dicho y el sitio actual no lo indica. Se queda vacío en vez de inventado.' },
  'catalog.timeExpectation': { en: 'Time expectation', es: 'Tiempo previsto' },
  'catalog.youReceive': { en: 'You receive', es: 'Recibes' },
  'catalog.youProvide': { en: 'What you provide', es: 'Qué aportas' },
  'catalog.beforeYouOrder': { en: 'Before you order', es: 'Antes de pedirlo' },
  'catalog.beforeYouOrderDesc': { en: 'What we need from you before the work can start. Assembled by CTL OS from the store\u2019s own prerequisites \u2014 the firm confirms it.', es: 'Lo que necesitamos de ti antes de empezar. Compilado por CTL OS a partir de los requisitos de la tienda; el despacho lo confirma.' },
  'catalog.nothingNeeded': { en: 'Nothing \u2014 buy it and download it.', es: 'Nada: cómpralo y descárgalo.' },
  'catalog.format.pdf': { en: 'A PDF', es: 'Un PDF' },
  'catalog.format.call': { en: 'A call with an attorney', es: 'Una llamada con un abogado' },
  'catalog.format.kit': { en: 'A do-it-yourself kit', es: 'Un kit para hacerlo tú mismo' },
  'catalog.format.filing': { en: 'Court-ready paperwork', es: 'Documentos listos para presentar' },
  'catalog.format.letter': { en: 'A letter on our letterhead', es: 'Una carta con nuestro membrete' },
  'catalog.format.review': { en: 'A written review by an attorney', es: 'Una revisión escrita de un abogado' },

  // P-13 outline
  'catalog.p13.eyebrow': { en: 'Every service, in one list', es: 'Todos los servicios, en una lista' },
  'catalog.p13.title': { en: 'The whole menu, as an outline', es: 'El menú completo, como esquema' },
  'catalog.p13.lead': { en: 'The same catalog as a collapsible tree: every category, every sub-category and every service with its number, price, time and what you have to provide. Built to be read top to bottom, expanded one branch at a time, or printed and marked up.', es: 'El mismo catálogo como árbol plegable: cada categoría, subcategoría y servicio con su número, precio, tiempo y lo que debes aportar. Para leerlo de arriba abajo, abrir una rama a la vez, o imprimirlo y anotarlo.' },
  'catalog.p13.treeLabel': { en: 'Services outline', es: 'Esquema de servicios' },
  'catalog.p13.expandAll': { en: 'Expand all', es: 'Abrir todo' },
  'catalog.p13.collapseAll': { en: 'Collapse all', es: 'Cerrar todo' },
  'catalog.p13.print': { en: 'Print', es: 'Imprimir' },
  'catalog.p13.keys': { en: 'Arrow keys move and open branches; Enter opens a service.', es: 'Las flechas mueven y abren ramas; Enter abre un servicio.' },
  'catalog.p13.counts': { en: '{cats} store categories · {svcs} services · {priced} with a posted price · as listed on caltenantlaw.com on {date}', es: '{cats} categorías de la tienda · {svcs} servicios · {priced} con precio publicado · según caltenantlaw.com el {date}' },
  'catalog.p13.view': { en: 'Outline', es: 'Esquema' },
  'catalog.p13.viewStore': { en: 'Store menu', es: 'Menú de la tienda' },
  'catalog.p13.viewStages': { en: 'Firm’s stage map', es: 'Mapa de etapas del despacho' },
  'catalog.p13.storeDesc': { en: 'The store as the firm shows it today: the 20 categories of the /store menu in menu order, each with its products in the order the store lists them.', es: 'La tienda tal como la muestra el despacho hoy: las 20 categorías del menú /store en su orden, cada una con sus productos en el orden de la tienda.' },
  'catalog.p13.stagesDesc': { en: 'The firm’s older stage-based navigation, still attached to every product in the store but hidden from the menu: Consultation · I’m Being Evicted… · Legal Papers · Sue Your Landlord, four levels deep. A product appears under every stage it is filed in; {unfiled} products the old tree never filed sit under “Store menu only”.', es: 'La navegación por etapas anterior del despacho, aún ligada a cada producto pero oculta del menú: Consultation · I’m Being Evicted… · Legal Papers · Sue Your Landlord, cuatro niveles. Un producto aparece en cada etapa donde está archivado; {unfiled} productos que el árbol antiguo nunca archivó están en “Solo menú de la tienda”.' },
  'catalog.p13.colService': { en: 'Service', es: 'Servicio' },
  'catalog.p13.openDetail': { en: 'Open this service', es: 'Abrir este servicio' },
  'catalog.p13.empty': { en: 'No services in this category yet', es: 'Aún no hay servicios en esta categoría' },
  'catalog.p13.printNote': { en: 'Printed from CTL OS. Every price is as listed on caltenantlaw.com on {date} and not yet confirmed by the firm.', es: 'Impreso desde CTL OS. Cada precio es el publicado en caltenantlaw.com el {date} y aún no está confirmado por el despacho.' },

  // C-04 cross-wiring
  'catalog.next.title': { en: 'What usually comes next', es: 'Lo que suele venir después' },
  'catalog.next.desc': { en: 'From where your case stands on the board. Prices are as listed on the firm’s site and are not a quote.', es: 'Desde donde está tu caso en el tablero. Los precios son los publicados en el sitio y no son una cotización.' },
  'catalog.next.seeAll': { en: 'See the whole menu', es: 'Ver el menú completo' },
};
