import type { StringTable } from '../../i18n/types';

export const strings: StringTable = {
  'owner.title': { en: 'Network', es: 'Red' },
  'owner.sub': { en: 'The whole network on one screen: what is running late and where, who carries how much, what each SKU and each office brings in, and how many callers become clients.', es: 'Toda la red en una pantalla: qué va con retraso y dónde, quién lleva cuánto, qué aporta cada SKU y cada oficina, y cuántas personas que llaman se convierten en clientes.' },
  'owner.lateRadar': { en: 'Late-work radar', es: 'Radar de trabajo atrasado' },
  'owner.byOffice': { en: 'By office', es: 'Por oficina' },
  'owner.byPerson': { en: 'By person', es: 'Por persona' },
  'owner.caseload': { en: 'Caseload by attorney', es: 'Carga de casos por abogado' },
  'owner.revenueBySku': { en: 'Revenue by SKU', es: 'Ingresos por SKU' },
  'owner.revenueByOffice': { en: 'Revenue by office', es: 'Ingresos por oficina' },
  'owner.offices': { en: 'Network offices', es: 'Oficinas de la red' },
  'owner.conversion': { en: 'Intake conversion this month', es: 'Conversión de admisiones este mes' },
  'owner.openCases': { en: 'Open cases', es: 'Casos abiertos' },
  'owner.lateItems': { en: 'Late items', es: 'Pendientes atrasados' },
  'owner.collected': { en: 'Collected', es: 'Cobrado' },
  'owner.outstanding': { en: 'Outstanding', es: 'Por cobrar' },
  'owner.allOffices': { en: 'All offices', es: 'Todas las oficinas' },
  'owner.chartSoon': { en: 'Charts arrive with the dataviz pass; the numbers below are the source of truth.', es: 'Las gráficas llegan en la etapa de visualización; los números de abajo son la fuente de verdad.' },
  'owner.showChart': { en: 'Show the chart', es: 'Ver la gráfica' },
  'owner.openRadar': { en: 'Open the full radar', es: 'Abrir el radar completo' },
  'owner.feedbackInbox': { en: 'Feedback inbox', es: 'Bandeja de comentarios' },
  'owner.nothingLate': { en: 'Nothing is running late across the network.', es: 'Nada va con retraso en toda la red.' },
  'owner.asListed': { en: 'Amounts as listed on the firm site; not a quote.', es: 'Importes según el sitio del bufete; no es una cotización.' },
  'owner.attorney': { en: 'Attorney', es: 'Abogado' },
  'owner.office': { en: 'Office', es: 'Oficina' },
  'owner.cases': { en: 'Cases', es: 'Casos' },
  'owner.late': { en: 'Late', es: 'Atrasados' },
  'owner.paid': { en: 'Paid', es: 'Pagado' },
  'owner.due': { en: 'Due', es: 'Pendiente' },
  'owner.intakes': { en: 'Intakes', es: 'Admisiones' },
  'owner.scheduled': { en: 'Scheduled', es: 'Programadas' },
  'owner.rate': { en: 'Rate', es: 'Tasa' },
  'owner.person': { en: 'Person', es: 'Persona' },
  'owner.role': { en: 'Role', es: 'Rol' },
  'owner.region': { en: 'Coverage', es: 'Cobertura' },
};
