import type { StringTable } from '../../i18n/types';

/** Client (tenant) app strings, en + es from the start (P-11). Keys are namespaced `client.*`. */
export const strings: StringTable = {
  'client.home': { en: 'Home', es: 'Inicio' },
  'client.binder': { en: 'Binder', es: 'Carpeta' },
  'client.learn': { en: 'Learn', es: 'Aprender' },
  'client.pay': { en: 'Pay', es: 'Pagar' },
  'client.homeTitle': { en: 'Your case', es: 'Su caso' },
  'client.hello': { en: 'Hello, {name}', es: 'Hola, {name}' },
  'client.noCaseTitle': { en: 'No case open yet', es: 'Aún no hay un caso abierto' },
  'client.noCaseBody': { en: 'Watch the free videos, then book a 30-minute consultation with an attorney.', es: 'Vea los videos gratuitos y luego reserve una consulta de 30 minutos con un abogado.' },
  'client.onTheBoard': { en: 'Where you are on the board', es: 'Dónde está en el tablero' },
  'client.openBoard': { en: 'See my square on the game board', es: 'Ver mi casilla en el tablero' },
  'client.whatHappened': { en: 'What happened', es: 'Qué pasó' },
  'client.whatNext': { en: 'What happens next', es: 'Qué sigue' },
  'client.myDeadlines': { en: 'My deadlines', es: 'Mis plazos' },
  'client.noDeadlines': { en: 'Nothing is due right now.', es: 'No hay nada pendiente ahora mismo.' },
  'client.watchNext': { en: 'What to watch next', es: 'Qué ver a continuación' },
  'client.payNext': { en: 'What to pay next', es: 'Qué pagar a continuación' },
  'client.nothingDue': { en: 'Nothing due. Thank you.', es: 'Nada pendiente. Gracias.' },
  'client.myBinder': { en: 'My binder', es: 'Mi carpeta' },
  'client.messages': { en: 'Messages', es: 'Mensajes' },
  'client.messagesBody': { en: 'Secure messages with your legal team arrive here.', es: 'Los mensajes seguros con su equipo legal llegarán aquí.' },
  'client.upload': { en: 'Add a document', es: 'Agregar un documento' },
  'client.viewAll': { en: 'See all', es: 'Ver todo' },
  'client.asListed': { en: 'Prices as listed; not a quote.', es: 'Precios según la lista; no es una cotización.' },
  'client.due': { en: 'Due', es: 'Vence' },
  'client.paid': { en: 'Paid', es: 'Pagado' },
  'client.payThis': { en: 'Pay', es: 'Pagar' },
  'client.continue': { en: 'Continue', es: 'Continuar' },
  'client.markWatched': { en: 'Mark as watched', es: 'Marcar como visto' },
  'client.watched': { en: 'Watched', es: 'Visto' },
  'client.play': { en: 'Play', es: 'Reproducir' },
  'client.binderTitle': { en: 'My binder', es: 'Mi carpeta' },
  'client.binderSub': { en: 'Every paper on your case, grouped by the square it belongs to.', es: 'Todos los papeles de su caso, agrupados por la casilla a la que pertenecen.' },
  'client.learnTitle': { en: 'Learn', es: 'Aprender' },
  'client.learnSub': { en: 'The firm’s free videos, in the order that helps you most.', es: 'Los videos gratuitos del bufete, en el orden que más le ayuda.' },
  'client.payTitle': { en: 'Pay', es: 'Pagar' },
  'client.paySub': { en: 'Each piece of work is priced on its own, like a vending machine.', es: 'Cada trabajo tiene su propio precio, como una máquina expendedora.' },
  'client.hotline': { en: 'Call the hotline', es: 'Llamar a la línea directa' },
  'client.allStages': { en: 'All squares', es: 'Todas las casillas' },
  'client.documents': { en: 'documents', es: 'documentos' },
  'client.totalDue': { en: 'Total due', es: 'Total a pagar' },
  'client.history': { en: 'Paid and refunded', es: 'Pagado y reembolsado' },
};
