import type { StringTable } from './types';

/** Strings the shells, shared components and dev tools use. Modules keep their own `strings`; keys here are namespaced shell / session / theme / lang / placeholder / feedback / stub / common / site. */
export const coreStrings: StringTable = {
  'common.cancel': { en: 'Cancel', es: 'Cancelar' }, 'common.send': { en: 'Send', es: 'Enviar' }, 'common.save': { en: 'Save', es: 'Guardar' }, 'common.remove': { en: 'Remove', es: 'Quitar' }, 'common.close': { en: 'Close', es: 'Cerrar' }, 'common.open': { en: 'Open', es: 'Abrir' }, 'common.run': { en: 'Run', es: 'Ejecutar' }, 'common.search': { en: 'Search', es: 'Buscar' }, 'common.yes': { en: 'Yes', es: 'Sí' }, 'common.no': { en: 'No', es: 'No' },
  'shell.hub': { en: 'Hub', es: 'Centro' }, 'shell.backToHub': { en: 'Back to the hub', es: 'Volver al centro' }, 'shell.openMenu': { en: 'Open menu', es: 'Abrir menú' }, 'shell.closeMenu': { en: 'Close menu', es: 'Cerrar menú' }, 'shell.skip': { en: 'Skip to content', es: 'Saltar al contenido' },
  'shell.search': { en: 'Search', es: 'Buscar' }, 'shell.searchPlanned': { en: 'search cases, clients and documents across the firm', es: 'buscar casos, clientes y documentos en todo el despacho' }, 'shell.help': { en: 'Help', es: 'Ayuda' },
  'shell.notifications': { en: 'Notifications', es: 'Notificaciones' }, 'shell.notificationsPlanned': { en: 'show deadlines, messages and hearing reminders', es: 'mostrar plazos, mensajes y recordatorios de audiencias' },
  'shell.presence': { en: 'Presence', es: 'Presencia' }, 'shell.presencePlanned': { en: 'show who else is on this page right now (realtime presence)', es: 'mostrar quién más está en esta página ahora (presencia en tiempo real)' }, 'shell.presenceYou': { en: 'You are the only one here', es: 'Solo tú estás aquí' },
  'shell.signOutDemo': { en: 'Sign out of the demo session', es: 'Cerrar la sesión demo' },
  'session.demo': { en: 'Demo session', es: 'Sesión demo' }, 'session.demoUser': { en: 'Demo user', es: 'Usuario demo' }, 'session.viewAs': { en: 'View as', es: 'Ver como' }, 'session.viewAsSelf': { en: 'View as: myself', es: 'Ver como: yo' }, 'session.signOut': { en: 'Sign out', es: 'Cerrar sesión' }, 'session.noEmail': { en: 'no email', es: 'sin correo' },
  'theme.appearance': { en: 'Appearance', es: 'Apariencia' }, 'theme.theme': { en: 'Theme', es: 'Tema' }, 'theme.light': { en: 'Light mode', es: 'Modo claro' }, 'theme.dark': { en: 'Dark mode', es: 'Modo oscuro' }, 'theme.brand': { en: 'Brand', es: 'Marca' },
  'lang.label': { en: 'Language', es: 'Idioma' },
  'hub.devMode': { en: 'Builder tool', es: 'Herramienta de construcción' }, 'hub.devModeHint': { en: 'Spec chip + inspector on every page, Ctrl+.', es: 'Ficha de especificación e inspector en cada página, Ctrl+.' },
  'placeholder.notWired': { en: 'Not wired yet', es: 'Aún no conectado' }, 'placeholder.toast': { en: 'Not wired yet', es: 'Aún no conectado' }, 'placeholder.plannedIn': { en: 'planned in', es: 'previsto en' }, 'placeholder.badge': { en: 'stub', es: 'pendiente' },
  'feedback.label': { en: 'Feedback', es: 'Comentarios' }, 'feedback.open': { en: 'Leave feedback on this page', es: 'Dejar un comentario sobre esta página' }, 'feedback.title': { en: 'Comment, request or report a bug', es: 'Comentar, pedir o reportar un error' }, 'feedback.about': { en: 'About this page', es: 'Sobre esta página' },
  'feedback.kind': { en: 'Kind', es: 'Tipo' }, 'feedback.kind.comment': { en: 'Comment', es: 'Comentario' }, 'feedback.kind.request': { en: 'Request', es: 'Petición' }, 'feedback.kind.bug': { en: 'Bug', es: 'Error' },
  'feedback.category': { en: 'Category', es: 'Categoría' }, 'feedback.cat.ui': { en: 'Screen / UI', es: 'Pantalla / UI' }, 'feedback.cat.content': { en: 'Wording / content', es: 'Texto / contenido' }, 'feedback.cat.data': { en: 'Data', es: 'Datos' }, 'feedback.cat.legal': { en: 'Legal accuracy', es: 'Exactitud legal' }, 'feedback.cat.idea': { en: 'Idea', es: 'Idea' }, 'feedback.cat.other': { en: 'Other', es: 'Otro' },
  'feedback.pick': { en: 'Pin to an element', es: 'Fijar a un elemento' }, 'feedback.repick': { en: 'Pin to another element', es: 'Fijar a otro elemento' }, 'feedback.pickHint': { en: 'Click the element you mean (Esc to cancel)', es: 'Haz clic en el elemento (Esc para cancelar)' },
  'feedback.text': { en: 'What did you notice?', es: '¿Qué notaste?' }, 'feedback.placeholder': { en: 'Tell us what happened or what you would like.', es: 'Cuéntanos qué pasó o qué te gustaría.' }, 'feedback.thanks': { en: 'Thanks, recorded for triage', es: 'Gracias, registrado para revisión' },
  'stub.comingSoon': { en: 'Coming soon', es: 'Próximamente' }, 'stub.plannedLayout': { en: 'Planned layout', es: 'Disposición prevista' }, 'stub.tables': { en: 'Tables', es: 'Tablas' }, 'stub.rules': { en: 'Rules', es: 'Reglas' }, 'stub.actions': { en: 'Planned actions', es: 'Acciones previstas' },
  'stub.body': { en: 'This screen is specified and will be built by its module. Every control below is a placeholder that says so.', es: 'Esta pantalla está especificada y la construirá su módulo. Cada control de abajo es un marcador que lo indica.' },
  'stub.openSpec': { en: 'Open spec', es: 'Abrir especificación' }, 'stub.willBuild': { en: 'build this page', es: 'construir esta página' },
  'site.brand': { en: 'California Tenant Law', es: 'California Tenant Law' }, 'site.tagline': { en: "Renters' rights lawyers since 1980", es: 'Abogados de inquilinos desde 1980' }, 'site.cta': { en: 'Book a consultation', es: 'Reservar una consulta' }, 'site.navLabel': { en: 'Website', es: 'Sitio web' },
  'site.nav.home': { en: 'Home', es: 'Inicio' }, 'site.nav.eviction': { en: 'Eviction defense', es: 'Defensa de desalojo' }, 'site.nav.services': { en: 'Services', es: 'Servicios' }, 'site.nav.videos': { en: 'Free videos', es: 'Videos gratis' }, 'site.nav.offices': { en: 'Offices', es: 'Oficinas' }, 'site.nav.board': { en: 'Game board', es: 'Tablero' },
  'site.offices': { en: 'Regional offices', es: 'Oficinas regionales' }, 'site.more': { en: 'More', es: 'Más' }, 'site.clientApp': { en: 'Client app', es: 'App del cliente' }, 'site.footerLead': { en: 'Tenant-side only. Consultations by phone or video across all 58 counties.', es: 'Solo del lado del inquilino. Consultas por teléfono o video en los 58 condados.' },
  'site.footerDisclaimer': { en: 'Demo system with fictional people and mock data.', es: 'Sistema demo con personas ficticias y datos simulados.' }, 'site.footerLine': { en: 'Your cloudy day is about to clear up.', es: 'Tu día nublado está por despejarse.' }, 'site.legalName': { en: 'California Tenant Law', es: 'California Tenant Law' }, 'site.notAdvice': { en: 'Information here is not legal advice.', es: 'La información aquí no es asesoría legal.' },
};
