import type { StringTable } from '../../i18n/types';

export const strings: StringTable = {
  'counsel.title': { en: 'My cases', es: 'Mis casos' },
  'counsel.sub': { en: 'Where every case stands on the board, what is running late, and what is due this week.', es: 'Dónde está cada caso en el tablero, qué va con retraso y qué vence esta semana.' },
  'counsel.runningLate': { en: 'Running late', es: 'Con retraso' },
  'counsel.deadlinesWeek': { en: 'Deadlines this week', es: 'Plazos de esta semana' },
  'counsel.discoveryDue': { en: 'Discovery due', es: 'Descubrimiento por vencer' },
  'counsel.docsToReview': { en: 'Documents to review', es: 'Documentos por revisar' },
  'counsel.nextHearings': { en: 'Next hearings', es: 'Próximas audiencias' },
  'counsel.myCases': { en: 'My cases', es: 'Mis casos' },
  'counsel.activeCases': { en: 'Active cases', es: 'Casos activos' },
  'counsel.openBoard': { en: 'Open on the board', es: 'Abrir en el tablero' },
  'counsel.done': { en: 'Done', es: 'Hecho' },
  'counsel.approve': { en: 'Approve for filing', es: 'Aprobar para presentar' },
  'counsel.assign': { en: 'Assign', es: 'Asignar' },
  'counsel.openDiscovery': { en: 'Open the discovery tracker', es: 'Abrir el seguimiento de pruebas' },
  'counsel.nothingLate': { en: 'Nothing is running late. Good.', es: 'Nada va con retraso. Bien.' },
  'counsel.nothingWeek': { en: 'Nothing due in the next seven days.', es: 'Nada vence en los próximos siete días.' },
  'counsel.noDocs': { en: 'No documents waiting for review.', es: 'No hay documentos esperando revisión.' },
  'counsel.noHearings': { en: 'No hearings on the calendar.', es: 'No hay audiencias en el calendario.' },
  'counsel.networkView': { en: 'Network view: every office', es: 'Vista de red: todas las oficinas' },
  'counsel.case': { en: 'Case', es: 'Caso' },
  'counsel.square': { en: 'Square', es: 'Casilla' },
  'counsel.county': { en: 'County', es: 'Condado' },
  'counsel.nextDue': { en: 'Next due', es: 'Próximo vencimiento' },
  'counsel.paralegal': { en: 'Paralegal', es: 'Asistente legal' },
  'counsel.attorney': { en: 'Attorney', es: 'Abogado' },
};
