import type { StringTable } from '../../i18n/types';

export const strings: StringTable = {
  'admin.title': { en: 'Admin & settings', es: 'Administración y ajustes' },
  'admin.sub': { en: 'People and their roles, the tables behind every page, the rules registry, and what testers reported.', es: 'Las personas y sus roles, las tablas detrás de cada página, el registro de reglas y lo que reportaron los probadores.' },
  'admin.users': { en: 'Users and roles', es: 'Usuarios y roles' },
  'admin.jumpTo': { en: 'Where things live', es: 'Dónde vive cada cosa' },
  'admin.tables': { en: 'Tables', es: 'Tablas' },
  'admin.tablesSub': { en: 'Every table with row counts and a row editor.', es: 'Todas las tablas con conteos y un editor de filas.' },
  'admin.rules': { en: 'Rules registry', es: 'Registro de reglas' },
  'admin.rulesSub': { en: 'Every business and legal rule, with the statutes still to verify.', es: 'Todas las reglas de negocio y legales, con los estatutos por verificar.' },
  'admin.feedback': { en: 'Feedback inbox', es: 'Bandeja de comentarios' },
  'admin.feedbackSub': { en: 'Comments, requests and bugs from testers, triaged before anything changes.', es: 'Comentarios, peticiones y errores de los probadores, clasificados antes de cambiar nada.' },
  'admin.settings': { en: 'Settings', es: 'Ajustes' },
  'admin.settingsSub': { en: 'Offices, branding, languages and the seams for Supabase and payments.', es: 'Oficinas, marca, idiomas y las conexiones para Supabase y pagos.' },
  'admin.presence': { en: 'Who is here', es: 'Quién está aquí' },
  'admin.presenceBody': { en: 'Live presence per route arrives with the realtime pass; the presence table already exists.', es: 'La presencia en vivo por ruta llega en la etapa de tiempo real; la tabla ya existe.' },
  'admin.invite': { en: 'Invite a person', es: 'Invitar a una persona' },
  'admin.changeRole': { en: 'Change role', es: 'Cambiar rol' },
  'admin.deactivate': { en: 'Deactivate', es: 'Desactivar' },
  'admin.activate': { en: 'Activate', es: 'Activar' },
  'admin.staff': { en: 'Staff', es: 'Equipo' },
  'admin.clients': { en: 'Clients', es: 'Clientes' },
  'admin.outside': { en: 'Opposing counsel', es: 'Abogados contrarios' },
  'admin.open': { en: 'Open', es: 'Abrir' },
  'admin.inboxTitle': { en: 'Feedback inbox', es: 'Bandeja de comentarios' },
  'admin.inboxSub': { en: 'Testers annotate the product itself. Record the decision on the row, then change the product.', es: 'Los probadores anotan sobre el producto. Registre la decisión en la fila y luego cambie el producto.' },
  'admin.triage': { en: 'Triage', es: 'Clasificar' },
  'admin.triageNote': { en: 'Why (recorded before the change)', es: 'Por qué (se registra antes del cambio)' },
  'admin.decisionRef': { en: 'Decision reference', es: 'Referencia de la decisión' },
  'admin.save': { en: 'Record the decision', es: 'Registrar la decisión' },
  'admin.reply': { en: 'Reply to the author', es: 'Responder al autor' },
  'admin.allStatuses': { en: 'All', es: 'Todos' },
  'admin.noFeedback': { en: 'Nothing in the inbox.', es: 'Nada en la bandeja.' },
  'admin.author': { en: 'Author', es: 'Autor' },
  'admin.page': { en: 'Page', es: 'Página' },
  'admin.kind': { en: 'Kind', es: 'Tipo' },
  'admin.status': { en: 'Status', es: 'Estado' },
  'admin.text': { en: 'What they said', es: 'Lo que dijeron' },
  'admin.role': { en: 'Role', es: 'Rol' },
  'admin.office': { en: 'Office', es: 'Oficina' },
  'admin.name': { en: 'Name', es: 'Nombre' },
  'admin.active': { en: 'Active', es: 'Activo' },
  'admin.newRows': { en: 'new', es: 'nuevos' },
};
