import type { StringTable } from '../../i18n/types';

/** Public-site module strings (P-01..P-04). English is primary; Spanish ships with the module (P-12). */
export const strings: StringTable = {
  // --- shared chrome
  'site.nav.attorneys': { en: 'Our attorneys', es: 'Nuestros abogados' },
  'site.nav.videos': { en: 'Free videos', es: 'Videos gratis' },
  'site.asShown': { en: 'As shown on caltenantlaw.com · unverified', es: 'Según caltenantlaw.com · sin verificar' },
  'site.asShownTip': { en: 'This name, title, office and portrait were read from the firm’s live website (caltenantlaw.com) on {date}. They are what the site publishes, not something the firm has confirmed inside CTL OS. A person at the firm confirms each one before it is presented as fact (D-046).', es: 'Este nombre, cargo, oficina y retrato se leyeron del sitio web del despacho (caltenantlaw.com) el {date}. Es lo que publica el sitio, no algo confirmado por el despacho dentro de CTL OS. Una persona del despacho confirma cada dato antes de presentarlo como un hecho (D-046).' },
  'site.nav.proposal': { en: 'The proposal', es: 'La propuesta' },
  'site.nav.replaces': { en: 'What it replaces', es: 'Qué reemplaza' },
  'site.nav.roadmap': { en: 'Roadmap', es: 'Plan' },
  'site.lang': { en: 'Language', es: 'Idioma' },
  'site.unverified': { en: 'Unverified', es: 'Sin verificar' },
  'site.asListed': { en: 'Prices and services as listed on caltenantlaw.com on {date}; not yet confirmed by the firm.', es: 'Precios y servicios según caltenantlaw.com el {date}; aún sin confirmar por el despacho.' },
  'site.free': { en: 'Free', es: 'Gratis' },
  'p1.board.posterAlt': { en: 'The Unlawful Detainer Game Board poster (© Ken Carlson 2021): the eviction process as a board game', es: 'El póster del tablero de desalojo (© Ken Carlson 2021): el proceso de desalojo como juego de mesa' },
  'site.pass': { en: 'Pass {n}', es: 'Fase {n}' },
  'site.status.done': { en: 'Built', es: 'Construido' },
  'site.status.doing': { en: 'In build', es: 'En construcción' },
  'site.status.planned': { en: 'Planned', es: 'Planeado' },

  // --- P-01 landing
  'p1.hero.eyebrow': { en: "Renters' rights lawyers since 1980", es: 'Abogados de inquilinos desde 1980' },
  'p1.hero.title': { en: 'Your cloudy day is about to clear up', es: 'Tu día nublado está por despejarse' },
  'p1.hero.lead': { en: 'Tenant-side only, across all 58 California counties, by phone or video. Learn the whole eviction for free first — then buy only the piece you actually need.', es: 'Solo del lado del inquilino, en los 58 condados de California, por teléfono o video. Aprende todo el desalojo gratis y luego compra solo la pieza que necesitas.' },
  'p1.hero.primary': { en: 'Book a 30-minute consultation', es: 'Reservar consulta de 30 minutos' },
  'p1.hero.secondary': { en: 'Start with the free videos', es: 'Empezar con los videos gratis' },
  'p1.hero.trust1': { en: 'Since 1980', es: 'Desde 1980' },
  'p1.hero.trust2': { en: 'All 58 counties', es: 'Los 58 condados' },
  'p1.hero.trust3': { en: 'Tenants only, never landlords', es: 'Solo inquilinos, nunca arrendadores' },
  'p1.hero.trust4': { en: 'Pay by the piece', es: 'Paga por pieza' },
  'p1.how.title': { en: 'How it works', es: 'Cómo funciona' },
  'p1.how.desc': { en: 'Three steps. The first one costs nothing.', es: 'Tres pasos. El primero no cuesta nada.' },
  'p1.how.step': { en: 'Step {n}', es: 'Paso {n}' },
  'p1.board.eyebrow': { en: 'The signature asset', es: 'La pieza distintiva' },
  'p1.board.title': { en: 'The eviction is a board game. Here is the board.', es: 'El desalojo es un juego de mesa. Aquí está el tablero.' },
  'p1.board.body': { en: 'Every eviction follows the same squares: the notice, the service, the motion to quash, the demurrer, the answer, discovery, trial, appeal. Each square has moves, and each move buys time or costs it. See where you would stand and what comes next.', es: 'Todo desalojo sigue las mismas casillas: el aviso, la entrega, la moción para anular, la excepción, la contestación, el discovery, el juicio y la apelación. Cada casilla tiene jugadas.' },
  'p1.board.cta': { en: 'Open the game board', es: 'Abrir el tablero' },
  'p1.stages.title': { en: 'Find your stage', es: 'Encuentra tu etapa' },
  'p1.stages.desc': { en: 'Pick where you are right now. We will show what happens next and what the firm does about it.', es: 'Elige dónde estás ahora. Te mostramos qué sigue y qué hace el bufete.' },
  'p1.stages.pickerLabel': { en: 'Your stage', es: 'Tu etapa' },
  'p1.stages.youAre': { en: 'Where you are', es: 'Dónde estás' },
  'p1.stages.weDo': { en: 'What we do', es: 'Qué hacemos' },
  'p1.stages.services': { en: 'Services listed for this stage', es: 'Servicios listados para esta etapa' },
  'p1.stages.open': { en: 'Open this stage in the store', es: 'Abrir esta etapa en la tienda' },
  'p1.videos.title': { en: 'Watch it all first, for free', es: 'Míralo todo primero, gratis' },
  'p1.videos.desc': { en: 'The attorney explains the whole process on video. Rewind it, save it, watch it at 2am. Rather than pay a lawyer to tell you the same thing.', es: 'El abogado explica todo el proceso en video. Repítelo, guárdalo, míralo a las 2am.' },
  'p1.videos.play': { en: 'Play', es: 'Reproducir' },
  'p1.videos.note': { en: 'A sample of the library. All {n} videos play free on the video library page; signed-in clients watch the same lessons in the app, with progress tracked.', es: 'Una muestra de la biblioteca. Los {n} videos se reproducen gratis en la página de videos; los clientes con sesión ven las mismas lecciones en la app, con seguimiento del progreso.' },
  'p1.offices.title': { en: 'Attorneys across California', es: 'Abogados en toda California' },
  'p1.offices.desc': { en: 'A network of regional tenant attorneys under one banner. Consultations happen by phone or video wherever you are.', es: 'Una red de abogados regionales de inquilinos. Las consultas son por teléfono o video.' },
  'p1.offices.demoNote': { en: 'Offices, cities, coverage and attorneys as posted on caltenantlaw.com on {date}, marked unverified until the firm confirms each one (D-046).', es: 'Oficinas, ciudades, cobertura y abogados según caltenantlaw.com el {date}, marcados como sin verificar hasta que el despacho confirme cada uno (D-046).' },
  'p1.book.title': { en: 'Thirty minutes with a licensed tenant attorney', es: 'Treinta minutos con un abogado de inquilinos' },
  'p1.book.body': { en: 'By phone or video. You leave knowing your real deadline, your best move, and what it costs.', es: 'Por teléfono o video. Sales sabiendo tu plazo real, tu mejor jugada y su costo.' },
  'p1.book.price': { en: '$165 for 30 minutes', es: '$165 por 30 minutos' },
  'p1.book.priceNote': { en: 'as listed on the current site', es: 'según el sitio actual' },
  'p1.book.intake': { en: 'Fill in the intake first', es: 'Completar la admisión primero' },
  'p1.demoBanner': { en: 'Concept for the redesigned caltenantlaw.com, built as part of CTL OS. Nothing here takes a payment yet.', es: 'Concepto del nuevo caltenantlaw.com, parte de CTL OS. Nada aquí cobra todavía.' },

  // --- P-05 attorneys
  'p5.eyebrow': { en: 'The people who take your call', es: 'Las personas que atienden tu llamada' },
  'p5.title': { en: 'Our attorneys', es: 'Nuestros abogados' },
  'p5.lead': { en: 'California Tenant Law is a network of regional tenant attorneys. These are the attorneys the firm names on its office pages — who they are, where they work and what they have done.', es: 'California Tenant Law es una red de abogados regionales de inquilinos. Estos son los abogados que el despacho nombra en las páginas de sus oficinas: quiénes son, dónde trabajan y qué han hecho.' },
  'p5.grid.title': { en: 'Attorneys by office', es: 'Abogados por oficina' },
  'p5.grid.desc': { en: '{n} attorneys across the network, as published on caltenantlaw.com on {date}. Pick an office to see who covers it.', es: '{n} abogados en la red, según caltenantlaw.com el {date}. Elige una oficina para ver quién la cubre.' },
  'p5.filter.label': { en: 'Filter by office', es: 'Filtrar por oficina' },
  'p5.filter.all': { en: 'All offices', es: 'Todas las oficinas' },
  'p5.card.officePage': { en: 'Office page on caltenantlaw.com', es: 'Página de la oficina en caltenantlaw.com' },
  'p5.sourceNote': { en: 'Names, titles, offices, bios and portraits are exactly as published on caltenantlaw.com on {date}, and stay marked unverified until the firm confirms each one in CTL OS. Bar numbers are not shown here.', es: 'Los nombres, cargos, oficinas, biografías y retratos son exactamente los publicados en caltenantlaw.com el {date}, y siguen marcados como sin verificar hasta que el despacho confirme cada uno en CTL OS. Los números de colegiado no se muestran aquí.' },
  'p5.noPhotoNote': { en: 'Where the firm’s site publishes no photograph, the card shows the attorney’s initials rather than a stand-in portrait.', es: 'Cuando el sitio del despacho no publica una fotografía, la tarjeta muestra las iniciales del abogado en lugar de un retrato sustituto.' },
  'p5.empty.title': { en: 'No attorney listed for that office yet', es: 'Todavía no hay abogado para esa oficina' },
  'p5.empty.body': { en: 'The firm’s site names an attorney on every office page we read; if an office is empty here, its page had none. Choose another office.', es: 'El sitio del despacho nombra a un abogado en cada página de oficina que leímos; si una oficina está vacía aquí, su página no tenía ninguno. Elige otra oficina.' },
  'p1.people.title': { en: 'Meet the attorneys', es: 'Conoce a los abogados' },
  'p1.people.desc': { en: 'A network of regional tenant attorneys, each one covering their own part of California.', es: 'Una red de abogados regionales de inquilinos, cada uno cubriendo su parte de California.' },
  'p1.people.cta': { en: 'Meet all the attorneys', es: 'Conoce a todos los abogados' },
  'p1.videos.libraryCta': { en: 'Watch the free videos', es: 'Mira los videos gratis' },
  'p1.videos.libraryBody': { en: 'The whole library — {n} videos in the firm’s own three series — plays right on the site, free, before you pay for anything.', es: 'Toda la biblioteca — {n} videos en las tres series del despacho — se reproduce en el sitio, gratis, antes de pagar nada.' },
  'p1.offices.attorney': { en: 'Attorney', es: 'Abogado' },
  'p1.offices.seeAttorney': { en: 'See this attorney', es: 'Ver a este abogado' },

  // --- P-06 videos
  'p6.eyebrow': { en: 'Free, before you pay anything', es: 'Gratis, antes de pagar nada' },
  'p6.title': { en: 'The free video library', es: 'La biblioteca de videos gratis' },
  'p6.lead': { en: 'The attorney explains the whole eviction on video: the notice, the papers, the motions, the trial and what comes after. Watch it here, rewind it, watch it at 2am.', es: 'El abogado explica todo el desalojo en video: el aviso, los papeles, las mociones, el juicio y lo que sigue. Míralo aquí, repítelo, míralo a las 2am.' },
  'p6.search': { en: 'Search the video library', es: 'Buscar en la biblioteca de videos' },
  'p6.searchPlaceholder': { en: 'Search: deposit, quash, repairs…', es: 'Buscar: depósito, anular, reparaciones…' },
  'p6.play': { en: 'Play', es: 'Reproducir' },
  'p6.close': { en: 'Close the player', es: 'Cerrar el reproductor' },
  'p6.groupOther': { en: 'Also on the articles', es: 'También en los artículos' },
  'p6.groupCount': { en: '{n} videos', es: '{n} videos' },
  'p6.trackNote': { en: 'Signed-in clients watch the same videos inside the app, where progress is tracked lesson by lesson and the attorney can see what you already know before the consultation starts.', es: 'Los clientes con sesión ven los mismos videos dentro de la app, donde el progreso se registra lección por lección y el abogado ve lo que ya sabes antes de la consulta.' },
  'p6.trackLink': { en: 'Open my lessons in the app', es: 'Abrir mis lecciones en la app' },
  'p6.trackSignedOut': { en: 'Tracked lessons live in the client app, which opens once you are a client. Nothing on this page needs an account.', es: 'Las lecciones con seguimiento están en la app del cliente, que se abre cuando ya eres cliente. Nada en esta página requiere una cuenta.' },
  'p6.empty.title': { en: 'No video matches that', es: 'Ningún video coincide' },
  'p6.empty.body': { en: 'Try a shorter word — the search looks at the title, the series and the presenter.', es: 'Prueba una palabra más corta: la búsqueda mira el título, la serie y el presentador.' },
  'p6.empty.clear': { en: 'Show every video', es: 'Mostrar todos los videos' },
  'p6.sourceNote': { en: '{n} videos, in the firm’s own groups and order, read from caltenantlaw.com on 2026-09-18. They play through youtube-nocookie, so nothing tracks you until you press play.', es: '{n} videos, en los grupos y el orden del despacho, leídos de caltenantlaw.com el 2026-09-18. Se reproducen por youtube-nocookie, así que nada te rastrea hasta que presionas reproducir.' },

  // --- P-02 proposal
  'p2.eyebrow': { en: 'Proposal for California Tenant Law', es: 'Propuesta para California Tenant Law' },
  'p2.title': { en: 'CTL OS: your complete operations system', es: 'CTL OS: su sistema operativo completo' },
  'p2.lead': { en: 'One system, every department, every role — the renter, the front desk, the attorneys, the assistants, the owner, marketing, even the other side. This page shows the whole surface and when each part ships.', es: 'Un sistema, cada departamento y cada rol: el inquilino, la recepción, los abogados, los asistentes, la dirección, marketing y hasta la parte contraria.' },
  'p2.stat.departments': { en: 'Departments', es: 'Departamentos' },
  'p2.stat.roles': { en: 'Role experiences', es: 'Experiencias de rol' },
  'p2.stat.features': { en: 'Features mapped', es: 'Funciones mapeadas' },
  'p2.stat.tasks': { en: 'Planned tasks', es: 'Tareas planeadas' },
  'p2.matrix.title': { en: 'Departments × roles', es: 'Departamentos × roles' },
  'p2.matrix.desc': { en: 'Every cell is something a specific person does in a specific part of the firm. Select one to see what it does, which pass it ships in and which pages build it.', es: 'Cada celda es algo que una persona hace en una parte del bufete. Selecciona una para ver qué hace y cuándo llega.' },
  'p2.matrix.dept': { en: 'Department', es: 'Departamento' },
  'p2.matrix.role': { en: 'Show role', es: 'Ver rol' },
  'p2.matrix.all': { en: 'All roles', es: 'Todos' },
  'p2.matrix.reset': { en: 'Show all roles', es: 'Ver todos los roles' },
  'p2.matrix.empty': { en: '—', es: '—' },
  'p2.matrix.count': { en: '{n} features', es: '{n} funciones' },
  'p2.drawer.what': { en: 'What it does', es: 'Qué hace' },
  'p2.drawer.who': { en: 'Who uses it', es: 'Quién lo usa' },
  'p2.drawer.when': { en: 'When it ships', es: 'Cuándo llega' },
  'p2.drawer.pages': { en: 'Pages', es: 'Páginas' },
  'p2.drawer.tasks': { en: 'Planned work', es: 'Trabajo planeado' },
  'p2.centre.title': { en: "One system around the client's case", es: 'Un sistema alrededor del caso del cliente' },
  'p2.centre.desc': { en: 'Nothing here is a separate app bolted on. The case is the centre, and every part of the firm reads and writes the same record.', es: 'Nada aquí es una app aparte. El caso es el centro y todo el bufete lee y escribe el mismo registro.' },
  'p2.centre.case': { en: 'The case', es: 'El caso' },
  'p2.centre.board': { en: 'Board position', es: 'Posición en el tablero' },
  'p2.centre.boardBody': { en: 'Which square the case is on. Everything else is a function of it.', es: 'En qué casilla está el caso. Todo lo demás depende de eso.' },
  'p2.centre.deadlines': { en: 'Deadlines', es: 'Plazos' },
  'p2.centre.deadlinesBody': { en: 'Court days from the position, each citing the statute behind it.', es: 'Días hábiles desde la posición, cada uno citando su ley.' },
  'p2.centre.binder': { en: 'Binder', es: 'Carpeta' },
  'p2.centre.binderBody': { en: 'Every document and piece of evidence, sorted by stage, gaps visible.', es: 'Cada documento y prueba, por etapa, con los vacíos visibles.' },
  'p2.centre.costs': { en: 'Costs', es: 'Costos' },
  'p2.centre.costsBody': { en: 'What the next move costs and what the branches after it could.', es: 'Cuánto cuesta la siguiente jugada y las ramas que siguen.' },
  'p2.centre.learning': { en: 'Learning', es: 'Aprendizaje' },
  'p2.centre.learningBody': { en: 'The lesson that matches this square, and whether they watched it.', es: 'La lección de esta casilla y si ya la vio.' },
  'p2.centre.comms': { en: 'Comms', es: 'Comunicación' },
  'p2.centre.commsBody': { en: 'Every call, message and recording attached to the same case.', es: 'Cada llamada, mensaje y grabación en el mismo caso.' },
  'p2.promises.title': { en: 'What we are promising', es: 'Lo que prometemos' },
  'p2.promises.desc': { en: 'The seven things that change how the firm works day to day.', es: 'Las siete cosas que cambian el día a día del bufete.' },
  'p2.method.title': { en: 'How it gets built', es: 'Cómo se construye' },
  'p2.method.desc': { en: 'The method matters as much as the feature list: you can watch it happen, comment on it and read every decision.', es: 'El método importa tanto como la lista: puedes verlo suceder, comentarlo y leer cada decisión.' },
  'p2.links.title': { en: 'See it for yourself', es: 'Míralo tú mismo' },
  'p2.links.plan': { en: 'The live project board', es: 'El tablero del proyecto' },
  'p2.links.planBody': { en: 'Every task, its pass, its dependencies and its status — the same file this page reads.', es: 'Cada tarea, su fase y su estado: el mismo archivo que lee esta página.' },
  'p2.links.board': { en: 'The game board', es: 'El tablero del juego' },
  'p2.links.boardBody': { en: 'The eviction flow as data, the spine of the whole case model.', es: 'El flujo del desalojo como datos, la columna del modelo.' },
  'p2.links.roadmap': { en: 'The roadmap', es: 'El plan' },
  'p2.links.roadmapBody': { en: 'Six passes, what each one ships, and what we need from you.', es: 'Seis fases, qué entrega cada una y qué necesitamos de ustedes.' },
  'p2.print': { en: 'Print this proposal', es: 'Imprimir la propuesta' },

  // --- P-03 replacement map
  'p3.eyebrow': { en: 'Replacement map', es: 'Mapa de reemplazo' },
  'p3.title': { en: 'What the firm stops paying for', es: 'Lo que el bufete deja de pagar' },
  'p3.lead': { en: 'Twelve tools carry the firm today, and none of them know about each other. Here is each one, what replaces it and when — and the four integrations kept on purpose.', es: 'Hoy doce herramientas sostienen al bufete y ninguna se conoce entre sí. Aquí está cada una, qué la reemplaza y cuándo, y las cuatro integraciones que se conservan.' },
  'p3.table.title': { en: 'The current stack', es: 'La pila actual' },
  'p3.note': { en: 'Tools are named as observed in the public index of the current site, except the pleading-paper tool, which the firm told us. Vendors marked inferred were not confirmed.', es: 'Las herramientas se nombran según el índice público del sitio actual. Las marcadas como inferidas no están confirmadas.' },
  'p3.filter': { en: 'Show', es: 'Ver' },
  'p3.filter.all': { en: 'Everything', es: 'Todo' },
  'p3.filter.replaced': { en: 'Replaced', es: 'Reemplazado' },
  'p3.filter.partly': { en: 'Partly kept', es: 'Parcial' },
  'p3.col.today': { en: 'Tool today', es: 'Herramienta hoy' },
  'p3.col.does': { en: 'What it does', es: 'Qué hace' },
  'p3.col.replacement': { en: 'Replaced by', es: 'Reemplazado por' },
  'p3.col.pass': { en: 'Ships', es: 'Llega' },
  'p3.col.evidence': { en: 'Source', es: 'Fuente' },
  'p3.ev.indexed': { en: 'On the site', es: 'En el sitio' },
  'p3.ev.inferred': { en: 'Inferred', es: 'Inferido' },
  'p3.ev.client': { en: 'From the firm', es: 'Del bufete' },
  'p3.kind.replaced': { en: 'Replaced', es: 'Reemplazado' },
  'p3.kind.partly': { en: 'Partly kept', es: 'Parcial' },
  'p3.kind.kept': { en: 'Kept', es: 'Se mantiene' },
  'p3.drawer.pain': { en: 'Why it hurts today', es: 'Por qué duele hoy' },
  'p3.drawer.seam': { en: 'What is kept', es: 'Qué se conserva' },
  'p3.seams.title': { en: 'Kept on purpose', es: 'Conservado a propósito' },
  'p3.seams.desc': { en: 'Not everything should be rebuilt. These stay behind a clean interface so swapping them later is a configuration change, not a rewrite.', es: 'No todo debe reconstruirse. Estos quedan detrás de una interfaz limpia.' },
  'p3.print': { en: 'Print the map', es: 'Imprimir el mapa' },
  'p3.rows': { en: '{n} tools', es: '{n} herramientas' },
  'p3.empty': { en: 'Nothing matches that filter.', es: 'Nada coincide con ese filtro.' },

  // --- P-04 roadmap
  'p4.eyebrow': { en: 'Roadmap', es: 'Plan de trabajo' },
  'p4.title': { en: 'Six passes, in dependency ticks', es: 'Seis fases, en pasos de dependencia' },
  'p4.lead': { en: 'Work is planned in dependency ticks, not calendar days: a task starts the moment everything it depends on is done, and many run in parallel. The length of the plan is its longest chain, not a number of weeks.', es: 'El trabajo se planea en pasos de dependencia, no en días de calendario: una tarea empieza cuando termina todo lo que necesita.' },
  'p4.updated': { en: 'Plan last updated {date}', es: 'Plan actualizado el {date}' },
  'p4.pass': { en: 'Pass {n}', es: 'Fase {n}' },
  'p4.passes.title': { en: 'The six passes', es: 'Las seis fases' },
  'p4.stat.tasks': { en: 'Tasks planned', es: 'Tareas planeadas' },
  'p4.stat.passes': { en: 'Passes', es: 'Fases' },
  'p4.goal': { en: 'Goal', es: 'Objetivo' },
  'p4.gate': { en: 'Starts when', es: 'Empieza cuando' },
  'p4.ships': { en: 'What ships', es: 'Qué entrega' },
  'p4.progress': { en: 'Progress', es: 'Avance' },
  'p4.tasks': { en: '{n} tasks', es: '{n} tareas' },
  'p4.showTasks': { en: 'Show the tasks', es: 'Ver las tareas' },
  'p4.hideTasks': { en: 'Hide the tasks', es: 'Ocultar las tareas' },
  'p4.taskCol.id': { en: 'Task', es: 'Tarea' },
  'p4.taskCol.title': { en: 'What it is', es: 'Qué es' },
  'p4.taskCol.lane': { en: 'Area', es: 'Área' },
  'p4.taskCol.status': { en: 'Status', es: 'Estado' },
  'p4.feedback.title': { en: 'How to tell us it is wrong', es: 'Cómo decirnos que algo está mal' },
  'p4.feedback.desc': { en: 'You do not file a ticket somewhere else. On any staff page there is a feedback button: point at the thing, say what you mean, and it arrives with the page, the element, the screen width and the theme already attached.', es: 'No abres un ticket en otro lado. En cualquier página del personal hay un botón de comentarios.' },
  'p4.feedback.triage': { en: 'Every note is triaged before anything changes, and the decision is written on the note itself: fix, ask, or not doing it and why.', es: 'Cada nota se revisa antes de cambiar algo y la decisión se escribe en la nota.' },
  'p4.feedback.try': { en: 'Leave a note', es: 'Dejar una nota' },
  'p4.asks.title': { en: 'What we need from you', es: 'Qué necesitamos de ustedes' },
  'p4.asks.desc': { en: 'Five things only the firm can answer. Each one is already blocking real work.', es: 'Cinco cosas que solo el bufete puede responder.' },
  'p4.asks.blocks': { en: 'Blocks', es: 'Bloquea' },
  'p4.plan.link': { en: 'Open the live project board', es: 'Abrir el tablero del proyecto' },
};
