import { defineSpec } from '../../specs/defineSpec';

/** Every width in the matrix; the studio was checked at all seven (P-01). */
export const CHECKED = [360, 390, 768, 1280, 1920, 2560, 3840];

const SOURCE = 'Justin, prompt 0006: "i also want a really cool system for drafting documents with relevant laws automatically on the side, precedence, recommendations, access to client details, etc. The pleading paper drafting system needs lots of attention, things to ask client, with ability to send the client the questions or requests for items, etc." The firm drafts pleading paper in WordPerfect today; D-018 chose a browser editor with the pleading-line ruler and PDF / DOCX export. Realtime co-editing is Pass 3 (S-12, T-097).';
const LEGAL = 'Every statute shown comes from docs/legal/statute-index.md and every row there is unverified (verified_on null, D-019); every precedent row ships verified: false. The panel says so on the card, on the insert and again in the recommendations (RULE-DRAFT-02, RULE-DRAFT-04).';

export const studioIndexSpec = defineSpec({
  code: 'S-21', name: 'Drafting studio',
  purpose: 'The paralegal or attorney starts here: either begin a draft for an order that does not have one (choosing from the templates that match its board square and document kind) or pick up something already being written. One table of every draft in the office with its order, client, revision, status, last edit and a preview of the page itself.',
  layout: ['PageHeader', 'StatTiles (drafts open, waiting on a client, filing due within 3 days, published templates)', 'StartADraft (order picker, suggested templates, start)', 'ContinueADraft (DataTable with DocPreview xs)', 'SourceNote'],
  data: ['drafts', 'templates', 'orders', 'users', 'cases', 'client_requests', 'draft_questions'],
  roles: ['paralegal', 'attorney', 'owner', 'super_admin'],
  logic: [
    'Orders offered in "Start a draft" are the open orders of the current office that have no drafts row yet, newest stage first; the pipeline links here with ?order=<id>, which preselects one and scrolls to the picker.',
    'Templates are suggested by suggestTemplates(): published templates whose board_node_ids contain the order\'s board_node_id or whose document_kind matches, then every other published template (RULE-DRAFT-05).',
    'Starting a draft copies the template body into drafts.blocks, resolves what the case, client and order rows already know into drafts.variables, builds the caption from the office attorney block and the case, and navigates to the studio. The template is never linked live: a later template edit cannot rewrite a document already with a client.',
    'The drafts table shows a DocPreview at xs drawn from the order\'s document_kind, the order ref, the client name, the revision, the draft status, the pipeline stage and when it was last edited; the search box matches title, order ref and client.',
    'The "waiting on a client" tile counts drafts whose order is waiting on the client (isWaitingOnClient), which is the one number Justin asked to see everywhere.',
    'A draft whose order has a filing_due_at within three days is flagged in the table and counted in its own tile.',
  ],
  integrations: ['Pipeline module (L-13 / L-14 link in with ?order=)', 'Legal memory K-11 (statute index)', 'Client app C-11 / C-21 (the requests this studio sends)'],
  components: ['PageHeader', 'Section', 'Card', 'StatTile', 'DataTable', 'DocPreview', 'Select', 'SearchInput', 'Button', 'Badge', 'StatusBadge', 'Chip', 'Tooltip', 'EmptyState', 'Icon'],
  actions: [
    { id: 'drafting.search', label: 'Search drafts', intent: 'find a draft by document, order or client', permission: 'drafts.read', params: { q: 'string' } },
    { id: 'drafting.pickOrder', label: 'Choose the order', intent: 'choose which order to draft for', permission: 'drafts.write', params: { orderId: 'id' } },
    { id: 'drafting.pickTemplate', label: 'Choose the template', intent: 'choose which template to draft from', permission: 'drafts.write', params: { templateId: 'id' } },
    { id: 'drafting.startDraft', label: 'Start the draft', intent: 'start a draft for this order from this template', permission: 'drafts.write', params: { orderId: 'id', templateId: 'id' } },
    { id: 'drafting.openDraft', label: 'Open a draft', intent: 'open a draft in the studio', permission: 'drafts.read', params: { draftId: 'id' } },
    { id: 'drafting.openTemplates', label: 'Manage templates', intent: 'open the template manager', permission: 'documents.write' },
  ],
  rules: ['RULE-DRAFT-01', 'RULE-DRAFT-05', 'RULE-PIPE-01', 'RULE-PIPE-02'],
  states: ['drafts in every status', 'order preselected from the pipeline (?order=)', 'no order left without a draft', 'no drafts at all', 'a filing due in two days', 'Spanish', 'dark', '10-foot (>= 2560)'],
  notes: [SOURCE, 'Deleting a draft is deliberately absent: a draft is the record of what was written for a client. Revisions supersede, nothing is removed.'],
  checkedAt: CHECKED,
});

export const draftSpec = defineSpec({
  code: 'S-22', name: 'Drafting studio: the draft',
  purpose: 'Where the document is actually written: California pleading paper in the middle with 28 numbered lines and a real caption, the outline and the blanks on the left, and on the right the statutes, the precedent, the live recommendations, the client’s own details and the questions we still owe them — with one button that turns those questions into requests the client answers in their app.',
  layout: ['PageHeader (order ref, client, stage, revision)', 'Toolbar (save, duplicate as revision, print, export, send for client review, request supervisor review, mark final, zoom)', 'LeftPane (outline, blanks to fill, template and version)', 'Centre (PleadingPaper editor)', 'RightPane (Laws · Precedent · Recommendations · Client · Questions)', 'Phone: the three panes become tabs'],
  data: ['drafts', 'templates', 'precedents', 'draft_questions', 'orders', 'order_stage_events', 'client_requests', 'cases', 'users', 'documents'],
  roles: ['paralegal', 'attorney', 'owner', 'super_admin'],
  logic: [
    'The centre is the PleadingPaper organism: blocks rendered with {{variables}} resolved, each block a contentEditable region snapped to the 28-line grid, pagination computed by line count (28 lines a page, ~85 characters a line) so the editor, the print stylesheet and a screenshot break in the same places.',
    'Every edit is written to drafts by id through the provider (never a local array), with word_count recomputed, so a second editor is not silently overwritten and the realtime pass has nothing to undo (P-14).',
    'Blanks resolve one way: resolveVariables() fills what the case, client and order rows know; a person may override any of them; a required blank still empty is highlighted in the form and is the first live recommendation.',
    'Laws: the template\'s statute_refs are looked up in docs/legal/statute-index.md through parseStatutes(); the search box searches the whole index. Insert writes the exact citation string into the block that has the caret, so the link back to the row never breaks (RULE-DRAFT-02).',
    'Precedent: precedentsFor() scores the library by shared board squares and shared statutes; every card carries the unverified badge and the standing caution (RULE-DRAFT-04).',
    'Recommendations: the template checklist plus liveRecommendations() — unresolved blanks, an incomplete caption, a filing deadline within three days, unverified statutes, unverified precedents, questions picked but not sent, requests still open with the client, whether the client has approved, whether supervisor review is pending, and the word count.',
    'Client: the order, the case, the client\'s name, phone and preferred language, the parties, the court, the board square, the open client_requests and the count of binder items on the case (documents rows of kind evidence or upload).',
    'Questions: template questions as checkboxes with "why we ask", plus your own. Send to client writes one client_requests row per selected question (kind question or item, prompt, detail, sent_via app, due in 3 days) and stamps the draft_questions row with its id; if the order sits in assigned or details_complete it also moves to gathering_client_details through applyTransition(), so the board, the desk and the client app all agree (RULE-DRAFT-03, RULE-PIPE-07).',
    'An answered question shows the client\'s answer with "Insert answer", which drops it into the block that has the caret.',
    'Send for client review is offered only from first_draft or attorney_review: it writes the client_requests review row, sets the draft to sent_for_client_review and moves the order to client_review through applyTransition(); a move the pipeline refuses is reported and never written (RULE-PIPE-08).',
    'Request supervisor review moves approved_by_client to supervisor_review. Mark final is offered only while the order is in supervisor_review and only to can(\'orders.supervise\') (RULE-DRAFT-01, RULE-PIPE-04).',
    'Print / PDF is real: the print stylesheet renders each page at Letter with 28 lines, the browser\'s own print dialogue saves the PDF. The draft status prints in the footer of every page so an unreviewed copy is recognisable.',
    'Zoom (75 / 100 / 125 per cent) is a CSS custom property on the sheet, so the line grid stays aligned; the value is in the URL (?zoom=) and so is the panel tab (?tab=), which makes both addressable for a voice controller (P-06).',
  ],
  integrations: ['docs/legal/statute-index.md (build-time markdown, parsed read-only)', 'src/domain/pipeline.ts applyTransition()', 'Client app C-11 / C-21 (client_requests)', 'Browser print (PDF)', 'DOCX export (T-069 / T-097, Placeholder)'],
  components: ['PageHeader', 'PleadingPaper', 'Tabs', 'SegmentedControl', 'Card', 'Section', 'DataTable', 'Modal', 'Input', 'Textarea', 'Select', 'Checkbox', 'Button', 'IconButton', 'Badge', 'StatusBadge', 'Chip', 'Tooltip', 'Placeholder', 'EmptyState', 'ProgressBar', 'Icon', 'SearchInput'],
  actions: [
    { id: 'drafting.save', label: 'Save', intent: 'save this draft', permission: 'drafts.write' },
    { id: 'drafting.editBlock', label: 'Edit a block', intent: 'change the text of one block of the document', permission: 'drafts.write', params: { blockId: 'id', text: 'string' } },
    { id: 'drafting.setVariable', label: 'Fill a blank', intent: 'fill one of the blanks in the document', permission: 'drafts.write', params: { key: 'string', value: 'string' } },
    { id: 'drafting.duplicateRevision', label: 'Duplicate as revision', intent: 'start the next revision of this draft', permission: 'drafts.write' },
    { id: 'drafting.print', label: 'Print or save as PDF', intent: 'print this draft on pleading paper or save it as a PDF', permission: 'drafts.read' },
    { id: 'drafting.exportDocx', label: 'Export DOCX', intent: 'download this draft as a Word document', permission: 'drafts.read' },
    { id: 'drafting.sendForClientReview', label: 'Send for client review', intent: 'send this draft to the client for review', permission: 'orders.advance', params: { message: 'string' } },
    { id: 'drafting.requestSupervisorReview', label: 'Request supervisor review', intent: 'send this draft to the supervising attorney', permission: 'orders.advance' },
    { id: 'drafting.markFinal', label: 'Mark final', intent: 'sign off this draft as the final version', permission: 'orders.supervise' },
    { id: 'drafting.setZoom', label: 'Zoom the page', intent: 'make the pleading page bigger or smaller', permission: 'drafts.read', params: { zoom: 'enum:75,100,125' } },
    { id: 'drafting.setPanelTab', label: 'Open a panel tab', intent: 'show the laws, the precedent, the recommendations, the client or the questions', permission: 'drafts.read', params: { tab: 'enum:laws,precedent,recommendations,client,questions' } },
    { id: 'drafting.focusBlock', label: 'Put the caret in a block', intent: 'move the caret to one block of the document', permission: 'drafts.read', params: { blockId: 'id' } },
    { id: 'drafting.searchLaws', label: 'Search the statute index', intent: 'search the statutes for something to cite', permission: 'docs.read', params: { q: 'string' } },
    { id: 'drafting.insertCitation', label: 'Insert a citation', intent: 'insert a statute citation into the block you are editing', permission: 'drafts.write', params: { citation: 'string' } },
    { id: 'drafting.insertPrecedent', label: 'Insert a precedent', intent: 'insert a case citation into the block you are editing', permission: 'drafts.write', params: { precedentId: 'id' } },
    { id: 'drafting.openStatute', label: 'Open the statute row', intent: 'open this statute in the legal memory', permission: 'docs.read', params: { citation: 'string' } },
    { id: 'drafting.toggleChecklistItem', label: 'Check a recommendation', intent: 'tick off one of the recommendations', permission: 'drafts.write', params: { itemId: 'id' } },
    { id: 'drafting.toggleQuestion', label: 'Select a question', intent: 'select or clear one of the questions for the client', permission: 'drafts.write', params: { questionId: 'id' } },
    { id: 'drafting.addQuestion', label: 'Add a question', intent: 'add your own question or item request for the client', permission: 'drafts.write', params: { text: 'string', kind: 'enum:question,item' } },
    { id: 'drafting.sendQuestions', label: 'Send questions to the client', intent: 'send the selected questions and item requests to the client', permission: 'orders.write' },
    { id: 'drafting.insertAnswer', label: 'Insert an answer', intent: 'insert the client’s answer into the block you are editing', permission: 'drafts.write', params: { questionId: 'id' } },
    { id: 'drafting.openOrder', label: 'Open the order', intent: 'open the order this draft belongs to', permission: 'orders.read' },
  ],
  rules: ['RULE-DRAFT-01', 'RULE-DRAFT-02', 'RULE-DRAFT-03', 'RULE-DRAFT-04', 'RULE-DRAFT-05', 'RULE-PIPE-01', 'RULE-PIPE-04', 'RULE-PIPE-07', 'RULE-PIPE-08'],
  states: ['being written with blanks missing', 'with the client (locked, duplicate to continue)', 'approved and awaiting the supervisor', 'final', 'filing due in two days', 'questions pending, sent and answered', 'zoom 75 / 125', 'phone (three tabs)', 'print', 'Spanish', 'dark', '10-foot (>= 2560)'],
  notes: [SOURCE, LEGAL, 'Export DOCX is a Placeholder (T-069 / T-097). Print and PDF are real through the print stylesheet.', 'No collaborative editing here: two people editing the same draft is S-12 / T-097 in Pass 3. Every write already goes by id with a version, so nothing here has to be undone for it.'],
  checkedAt: CHECKED,
});

export const templatesSpec = defineSpec({
  code: 'S-10', name: 'Document templates',
  purpose: 'Where the firm owns its own paperwork: every template as a row, edited as forms rather than code — the body blocks, the blanks and where each one is filled from, the questions we ask a client, the recommendations checklist and the statutes it leans on — with a live preview on pleading paper and a publish switch that decides whether it is offered when a draft is started.',
  layout: ['PageHeader', 'StatTiles (templates, published, drafts started from them, statutes cited)', 'TemplatesTable (code, title, kind, board squares, version, status, drafts)', 'Drawer: template editor (details, body, blanks, questions, recommendations, statutes, preview)', 'SourceNote'],
  data: ['templates', 'drafts', 'precedents'],
  roles: ['paralegal', 'attorney', 'owner', 'super_admin'],
  logic: [
    'The table lists every template of the office and the network library; search matches code, title, board square and statute citation.',
    'Opening a row opens a Drawer with the whole template as forms. Nothing here is code: a block is a kind and a text box, a blank is a key, a label, a type and a source, a question is text plus "why we ask", a recommendation is text plus a rule reference.',
    'Blocks and list items move with up / down buttons, never drag alone (P-03).',
    'Saving bumps template_version and writes by id through the provider; existing drafts are unaffected because a draft copies the body rather than linking to it (RULE-DRAFT-05).',
    'Preview renders the template on the PleadingPaper organism read-only with sample values, so the drafter sees the real page before publishing.',
    'The publish toggle writes status: published templates appear when a draft is started, draft ones are visible here only. Writing needs documents.write; a paralegal reads.',
    'Statute citations are typed as they appear in docs/legal/statute-index.md; one that is not in the index is shown as unmatched rather than silently accepted (RULE-DRAFT-02).',
  ],
  integrations: ['docs/legal/statute-index.md', 'docs/game-board/nodes.json (board squares)', 'docs/data/services-catalog.json (SKU)'],
  components: ['PageHeader', 'Section', 'Card', 'StatTile', 'DataTable', 'Drawer', 'PleadingPaper', 'Tabs', 'Input', 'Textarea', 'Select', 'Checkbox', 'Toggle', 'Button', 'IconButton', 'Badge', 'StatusBadge', 'Chip', 'Tooltip', 'EmptyState', 'Icon', 'Placeholder'],
  actions: [
    { id: 'drafting.searchTemplates', label: 'Search templates', intent: 'find a template by name, code, board square or statute', permission: 'documents.read', params: { q: 'string' } },
    { id: 'drafting.openTemplate', label: 'Open a template', intent: 'open one template to edit it', permission: 'documents.read', params: { templateId: 'id' } },
    { id: 'drafting.closeTemplate', label: 'Close the template', intent: 'close the template editor', permission: 'documents.read' },
    { id: 'drafting.editTemplateField', label: 'Edit a field', intent: 'change one field of the template', permission: 'documents.write', params: { field: 'string', value: 'string' } },
    { id: 'drafting.editTemplateBlock', label: 'Edit a body block', intent: 'change the text or kind of one block of the template', permission: 'documents.write', params: { blockId: 'id', text: 'string' } },
    { id: 'drafting.addTemplateBlock', label: 'Add a block', intent: 'add a block to the template body', permission: 'documents.write', params: { type: 'enum:heading,paragraph,numbered,signature,caption,pagebreak' } },
    { id: 'drafting.removeTemplateBlock', label: 'Remove a block', intent: 'remove a block from the template body', permission: 'documents.write', params: { blockId: 'id' } },
    { id: 'drafting.moveTemplateBlock', label: 'Move a block', intent: 'move a block up or down the template body', permission: 'documents.write', params: { blockId: 'id', direction: 'enum:up,down' } },
    { id: 'drafting.editTemplateVariable', label: 'Edit a blank', intent: 'change one of the blanks the template fills', permission: 'documents.write', params: { key: 'string', field: 'string', value: 'string' } },
    { id: 'drafting.addTemplateVariable', label: 'Add a blank', intent: 'add a blank to the template', permission: 'documents.write' },
    { id: 'drafting.removeTemplateVariable', label: 'Remove a blank', intent: 'remove a blank from the template', permission: 'documents.write', params: { key: 'string' } },
    { id: 'drafting.editTemplateQuestion', label: 'Edit a client question', intent: 'change one of the questions this template asks the client', permission: 'documents.write', params: { questionId: 'id', field: 'string', value: 'string' } },
    { id: 'drafting.addTemplateQuestion', label: 'Add a client question', intent: 'add a question this template asks the client', permission: 'documents.write' },
    { id: 'drafting.removeTemplateQuestion', label: 'Remove a client question', intent: 'remove one of the questions this template asks', permission: 'documents.write', params: { questionId: 'id' } },
    { id: 'drafting.editChecklistItem', label: 'Edit a recommendation', intent: 'change one of the recommendations for this template', permission: 'documents.write', params: { itemId: 'id', field: 'string', value: 'string' } },
    { id: 'drafting.addChecklistItem', label: 'Add a recommendation', intent: 'add a recommendation for this template', permission: 'documents.write' },
    { id: 'drafting.removeChecklistItem', label: 'Remove a recommendation', intent: 'remove a recommendation from this template', permission: 'documents.write', params: { itemId: 'id' } },
    { id: 'drafting.editStatuteRefs', label: 'Edit the statutes', intent: 'change the statutes this template leans on', permission: 'documents.write', params: { value: 'string' } },
    { id: 'drafting.saveTemplate', label: 'Save the template', intent: 'save this template and bump its version', permission: 'documents.write' },
    { id: 'drafting.togglePublished', label: 'Publish or unpublish', intent: 'offer this template when a draft is started, or take it off the list', permission: 'documents.write' },
    { id: 'drafting.previewTemplate', label: 'Preview on pleading paper', intent: 'see this template on pleading paper with sample values', permission: 'documents.read' },
    { id: 'drafting.newTemplate', label: 'New template', intent: 'create a new document template', permission: 'documents.write' },
  ],
  rules: ['RULE-DRAFT-02', 'RULE-DRAFT-05'],
  states: ['table of every template', 'editor open on a published template', 'editor open on a draft template', 'preview on pleading paper', 'read-only (paralegal)', 'Spanish', 'dark', '10-foot (>= 2560)'],
  notes: [SOURCE, 'P-07: templates are managed in the product, never as loose files. Ten templates ship seeded; the firm edits them here.', 'Creating a brand-new template from nothing is a Placeholder this pass (T-067 finishes it); the ten seeded templates are fully editable.'],
  checkedAt: CHECKED,
});
