import type { StringTable } from '../../i18n/types';

/**
 * Drafting studio strings (S-21, S-22, S-10). Legal terms of art keep the English term in parentheses on the Spanish
 * side the first time they appear (P-13: "demurrer (demurrer, excepción previa)"), because that is the word that
 * appears on the client's paperwork and the one the court will use.
 */
export const strings: StringTable = {
  'drafting.nav.studio': { en: 'Drafting studio', es: 'Taller de redacción' },
  'drafting.nav.templates': { en: 'Document templates', es: 'Plantillas de documentos' },

  // shared vocabulary
  'drafting.draft': { en: 'Draft', es: 'Borrador' },
  'drafting.drafts': { en: 'Drafts', es: 'Borradores' },
  'drafting.template': { en: 'Template', es: 'Plantilla' },
  'drafting.templates': { en: 'Templates', es: 'Plantillas' },
  'drafting.order': { en: 'Order', es: 'Pedido' },
  'drafting.client': { en: 'Client', es: 'Cliente' },
  'drafting.revision': { en: 'Revision', es: 'Revisión' },
  'drafting.status': { en: 'Status', es: 'Estado' },
  'drafting.lastEdited': { en: 'Last edited', es: 'Última edición' },
  'drafting.words': { en: 'words', es: 'palabras' },
  'drafting.unverified': { en: 'unverified', es: 'sin verificar' },
  'drafting.verified': { en: 'verified', es: 'verificado' },
  'drafting.unverifiedTip': { en: 'This row has not been checked against the current law or the reporter. It may be cited in a draft, but the studio keeps saying so until an attorney verifies it.', es: 'Esta fila no se ha comprobado contra la ley vigente ni contra el repertorio. Puede citarse en un borrador, pero el taller lo seguirá advirtiendo hasta que un abogado la verifique.' },
  'drafting.currencyFlag': { en: 'Flagged for a 2026 currency check', es: 'Marcada para revisión de vigencia 2026' },
  'drafting.notFound': { en: 'No such draft', es: 'No existe ese borrador' },
  'drafting.notFoundBody': { en: 'The draft may have been deleted, or the link is for another office.', es: 'El borrador pudo eliminarse, o el enlace es de otra oficina.' },
  'drafting.backToStudio': { en: 'All drafts', es: 'Todos los borradores' },
  'drafting.none': { en: 'Nothing here yet', es: 'Aún no hay nada aquí' },
  'drafting.cancel': { en: 'Cancel', es: 'Cancelar' },
  'drafting.close': { en: 'Close', es: 'Cerrar' },
  'drafting.details': { en: 'Details', es: 'Detalles' },
  'drafting.saved': { en: 'Saved', es: 'Guardado' },
  'drafting.of': { en: 'of', es: 'de' },

  // draft statuses
  'drafting.st.editing': { en: 'Being written', es: 'En redacción' },
  'drafting.st.sent_for_client_review': { en: 'With the client', es: 'Con el cliente' },
  'drafting.st.approved': { en: 'Approved by the client', es: 'Aprobado por el cliente' },
  'drafting.st.final': { en: 'Final', es: 'Versión final' },

  // S-21 index
  'drafting.s21.title': { en: 'Drafting studio', es: 'Taller de redacción' },
  'drafting.s21.subtitle': { en: 'Write the firm’s documents on California pleading paper, with the statutes, the precedent, the recommendations and the client’s own details beside the page.', es: 'Redacta los documentos del bufete en papel de alegatos de California, con las leyes, los precedentes, las recomendaciones y los datos del cliente junto a la página.' },
  'drafting.s21.startTitle': { en: 'Start a draft', es: 'Empezar un borrador' },
  'drafting.s21.startDesc': { en: 'Pick an order that has no draft yet, then a template. The template suggested first is the one that matches the order’s board square and document kind.', es: 'Elige un pedido que aún no tenga borrador y luego una plantilla. La plantilla sugerida primero es la que coincide con la casilla del tablero y el tipo de documento del pedido.' },
  'drafting.s21.pickOrder': { en: 'Order without a draft', es: 'Pedido sin borrador' },
  'drafting.s21.pickTemplate': { en: 'Template', es: 'Plantilla' },
  'drafting.s21.suggested': { en: 'Suggested for this order', es: 'Sugeridas para este pedido' },
  'drafting.s21.otherTemplates': { en: 'Every other published template', es: 'Las demás plantillas publicadas' },
  'drafting.s21.start': { en: 'Start the draft', es: 'Empezar el borrador' },
  'drafting.s21.startWhat': { en: 'create a draft for this order from the chosen template', es: 'crear un borrador para este pedido con la plantilla elegida' },
  'drafting.s21.continueTitle': { en: 'Continue a draft', es: 'Continuar un borrador' },
  'drafting.s21.continueDesc': { en: 'Everything being written in this office, newest first.', es: 'Todo lo que se está redactando en esta oficina, lo más reciente primero.' },
  'drafting.s21.allOrdersHaveDrafts': { en: 'Every open order already has a draft.', es: 'Todos los pedidos abiertos ya tienen borrador.' },
  'drafting.s21.noDrafts': { en: 'No drafts yet. Start one above.', es: 'Aún no hay borradores. Empieza uno arriba.' },
  'drafting.s21.statDrafts': { en: 'Drafts open', es: 'Borradores abiertos' },
  'drafting.s21.statWaiting': { en: 'Waiting on a client', es: 'Esperando al cliente' },
  'drafting.s21.statTemplates': { en: 'Published templates', es: 'Plantillas publicadas' },
  'drafting.s21.statDue': { en: 'Filing due within 3 days', es: 'Presentación en 3 días o menos' },
  'drafting.s21.searchLabel': { en: 'Search drafts', es: 'Buscar borradores' },
  'drafting.s21.manageTemplates': { en: 'Manage templates', es: 'Gestionar plantillas' },
  'drafting.s21.preselected': { en: 'Order {ref} is preselected from the pipeline.', es: 'El pedido {ref} viene preseleccionado desde el flujo.' },

  // S-22 studio
  'drafting.s22.title': { en: 'Draft', es: 'Borrador' },
  'drafting.s22.tabDocument': { en: 'Document', es: 'Documento' },
  'drafting.s22.tabOutline': { en: 'Outline', es: 'Esquema' },
  'drafting.s22.tabPanel': { en: 'Research', es: 'Investigación' },
  'drafting.s22.outline': { en: 'Outline', es: 'Esquema' },
  'drafting.s22.variables': { en: 'Blanks to fill', es: 'Espacios por completar' },
  'drafting.s22.variablesDesc': { en: 'Filled from the case, the client and the order where we already know the answer. Anything highlighted is required and still empty.', es: 'Se completan con el caso, el cliente y el pedido cuando ya sabemos la respuesta. Lo resaltado es obligatorio y sigue vacío.' },
  'drafting.s22.fromTemplate': { en: 'From {title} v{version}', es: 'De {title} v{version}' },
  'drafting.s22.save': { en: 'Save', es: 'Guardar' },
  'drafting.s22.saveWhat': { en: 'save this draft', es: 'guardar este borrador' },
  'drafting.s22.duplicate': { en: 'Duplicate as revision', es: 'Duplicar como revisión' },
  'drafting.s22.duplicateWhat': { en: 'start the next revision of this draft', es: 'empezar la siguiente revisión de este borrador' },
  'drafting.s22.print': { en: 'Print / PDF', es: 'Imprimir / PDF' },
  'drafting.s22.printWhat': { en: 'print this draft on Letter pleading paper or save it as a PDF', es: 'imprimir este borrador en papel de alegatos tamaño carta o guardarlo como PDF' },
  'drafting.s22.exportDocx': { en: 'Export DOCX', es: 'Exportar DOCX' },
  'drafting.s22.exportDocxWhat': { en: 'download this draft as a Word document', es: 'descargar este borrador como documento de Word' },
  'drafting.s22.sendClient': { en: 'Send for client review', es: 'Enviar al cliente para revisión' },
  'drafting.s22.sendClientWhat': { en: 'send this draft to the client for review', es: 'enviar este borrador al cliente para que lo revise' },
  'drafting.s22.sendClientTitle': { en: 'Send this draft to the client', es: 'Enviar este borrador al cliente' },
  'drafting.s22.sendClientBody': { en: 'The client sees the draft read-only in their app and is asked to approve it or tell us what to change. The order moves to “Reviewed by client” and will show as waiting on the client everywhere.', es: 'El cliente verá el borrador en modo lectura en su aplicación y se le pedirá que lo apruebe o nos diga qué cambiar. El pedido pasa a “En revisión del cliente” y aparecerá como pendiente del cliente en todas partes.' },
  'drafting.s22.message': { en: 'Message to the client', es: 'Mensaje para el cliente' },
  'drafting.s22.requestSupervisor': { en: 'Request supervisor review', es: 'Pedir revisión del supervisor' },
  'drafting.s22.requestSupervisorWhat': { en: 'send this draft to the supervising attorney', es: 'enviar este borrador al abogado supervisor' },
  'drafting.s22.markFinal': { en: 'Mark final', es: 'Marcar como final' },
  'drafting.s22.markFinalWhat': { en: 'sign off this draft as the final version', es: 'aprobar este borrador como versión final' },
  'drafting.s22.zoom': { en: 'Zoom', es: 'Zoom' },
  'drafting.s22.openOrder': { en: 'Open the order', es: 'Abrir el pedido' },
  'drafting.s22.moveBlocked': { en: 'Not allowed from this stage', es: 'No permitido desde esta etapa' },
  'drafting.s22.supervisorOnly': { en: 'Only a supervising attorney can mark a document final (RULE-DRAFT-01).', es: 'Solo un abogado supervisor puede marcar un documento como final (RULE-DRAFT-01).' },
  'drafting.s22.lockedNote': { en: 'This draft is with the client. Duplicate it as a revision to keep writing.', es: 'Este borrador está con el cliente. Duplícalo como revisión para seguir escribiendo.' },

  // side panel
  'drafting.panel.laws': { en: 'Laws', es: 'Leyes' },
  'drafting.panel.precedent': { en: 'Precedent', es: 'Precedentes' },
  'drafting.panel.recommendations': { en: 'Recommendations', es: 'Recomendaciones' },
  'drafting.panel.client': { en: 'Client', es: 'Cliente' },
  'drafting.panel.questions': { en: 'Questions', es: 'Preguntas' },
  'drafting.panel.title': { en: 'Beside the page', es: 'Junto a la página' },
  'drafting.laws.fromTemplate': { en: 'Cited by this template', es: 'Citadas por esta plantilla' },
  'drafting.laws.search': { en: 'Search the statute index', es: 'Buscar en el índice de leyes' },
  'drafting.laws.searchResults': { en: 'Search results', es: 'Resultados' },
  'drafting.laws.insert': { en: 'Insert citation', es: 'Insertar cita' },
  'drafting.laws.insertWhat': { en: 'insert this citation into the block you are editing', es: 'insertar esta cita en el bloque que estás editando' },
  'drafting.laws.open': { en: 'Open in legal memory', es: 'Abrir en la memoria legal' },
  'drafting.laws.noBlock': { en: 'Put the caret in a block first, then insert.', es: 'Coloca el cursor en un bloque y luego inserta.' },
  'drafting.laws.inserted': { en: 'Inserted {citation}', es: 'Se insertó {citation}' },
  'drafting.laws.source': { en: 'Source: docs/legal/statute-index.md — every row unverified until an attorney signs it off (D-019).', es: 'Fuente: docs/legal/statute-index.md — todas las filas están sin verificar hasta que un abogado las confirme (D-019).' },
  'drafting.prec.matching': { en: 'Matching this document', es: 'Coinciden con este documento' },
  'drafting.prec.holding': { en: 'Why we cite it', es: 'Por qué la citamos' },
  'drafting.prec.verifyNote': { en: 'Verify the citation before use.', es: 'Verifica la cita antes de usarla.' },
  'drafting.rec.checklist': { en: 'From the template', es: 'De la plantilla' },
  'drafting.rec.live': { en: 'Checked right now', es: 'Comprobado ahora mismo' },
  'drafting.rec.done': { en: 'done', es: 'hecho' },
  'drafting.client.details': { en: 'Client and case', es: 'Cliente y caso' },
  'drafting.client.language': { en: 'Preferred language', es: 'Idioma preferido' },
  'drafting.client.phone': { en: 'Phone', es: 'Teléfono' },
  'drafting.client.court': { en: 'Court', es: 'Tribunal' },
  'drafting.client.boardSquare': { en: 'Board square', es: 'Casilla del tablero' },
  'drafting.client.openRequests': { en: 'Open requests with the client', es: 'Solicitudes abiertas con el cliente' },
  'drafting.client.evidence': { en: 'Items in the binder', es: 'Elementos en la carpeta' },
  'drafting.client.parties': { en: 'Parties', es: 'Partes' },
  'drafting.q.fromTemplate': { en: 'Questions this document asks', es: 'Preguntas que pide este documento' },
  'drafting.q.onThisDraft': { en: 'On this draft', es: 'En este borrador' },
  'drafting.q.why': { en: 'Why we ask', es: 'Por qué lo preguntamos' },
  'drafting.q.add': { en: 'Add a question', es: 'Añadir una pregunta' },
  'drafting.q.addWhat': { en: 'add your own question for the client', es: 'añadir tu propia pregunta para el cliente' },
  'drafting.q.newLabel': { en: 'Your question or request', es: 'Tu pregunta o solicitud' },
  'drafting.q.kind': { en: 'Kind', es: 'Tipo' },
  'drafting.q.kindQuestion': { en: 'Question (an answer in words)', es: 'Pregunta (una respuesta escrita)' },
  'drafting.q.kindItem': { en: 'Item (a document or photo)', es: 'Elemento (un documento o una foto)' },
  'drafting.q.send': { en: 'Send to client', es: 'Enviar al cliente' },
  'drafting.q.sendWhat': { en: 'send the selected questions to the client', es: 'enviar al cliente las preguntas seleccionadas' },
  'drafting.q.sendNone': { en: 'Select at least one question first.', es: 'Selecciona al menos una pregunta.' },
  'drafting.q.sent': { en: 'Sent {count} to the client', es: 'Se enviaron {count} al cliente' },
  'drafting.q.insertAnswer': { en: 'Insert answer', es: 'Insertar respuesta' },
  'drafting.q.insertAnswerWhat': { en: 'insert the client’s answer into the block you are editing', es: 'insertar la respuesta del cliente en el bloque que estás editando' },
  'drafting.q.stPending': { en: 'Not sent', es: 'Sin enviar' },
  'drafting.q.stSent': { en: 'Sent', es: 'Enviada' },
  'drafting.q.stAnswered': { en: 'Answered', es: 'Respondida' },
  'drafting.q.stSkipped': { en: 'Skipped', es: 'Omitida' },

  // S-10 template manager
  'drafting.s10.title': { en: 'Document templates', es: 'Plantillas de documentos' },
  'drafting.s10.subtitle': { en: 'Every document the firm drafts is a row here, edited as a form — the body, the blanks, the questions we ask the client, the recommendations and the statutes it leans on. No template lives in a file.', es: 'Cada documento que redacta el bufete es una fila aquí, editada como formulario: el cuerpo, los espacios, las preguntas al cliente, las recomendaciones y las leyes en que se apoya. Ninguna plantilla vive en un archivo.' },
  'drafting.s10.new': { en: 'New template', es: 'Nueva plantilla' },
  'drafting.s10.newWhat': { en: 'create a new document template', es: 'crear una nueva plantilla de documento' },
  'drafting.s10.blocks': { en: 'Body', es: 'Cuerpo' },
  'drafting.s10.variables': { en: 'Blanks', es: 'Espacios' },
  'drafting.s10.questions': { en: 'Client questions', es: 'Preguntas al cliente' },
  'drafting.s10.checklist': { en: 'Recommendations', es: 'Recomendaciones' },
  'drafting.s10.statutes': { en: 'Statutes', es: 'Leyes' },
  'drafting.s10.preview': { en: 'Preview on pleading paper', es: 'Vista previa en papel de alegatos' },
  'drafting.s10.previewWhat': { en: 'see this template on pleading paper with sample values', es: 'ver esta plantilla en papel de alegatos con valores de ejemplo' },
  'drafting.s10.publish': { en: 'Published', es: 'Publicada' },
  'drafting.s10.publishHint': { en: 'Published templates are offered when a draft is started; drafts are visible here only.', es: 'Las plantillas publicadas se ofrecen al empezar un borrador; las que están en borrador solo se ven aquí.' },
  'drafting.s10.saveVersion': { en: 'Save (version {next})', es: 'Guardar (versión {next})' },
  'drafting.s10.saveWhat': { en: 'save this template and bump its version', es: 'guardar esta plantilla y subir su versión' },
  'drafting.s10.add': { en: 'Add', es: 'Añadir' },
  'drafting.s10.remove': { en: 'Remove', es: 'Quitar' },
  'drafting.s10.moveUp': { en: 'Move up', es: 'Subir' },
  'drafting.s10.moveDown': { en: 'Move down', es: 'Bajar' },
  'drafting.s10.code': { en: 'Code', es: 'Código' },
  'drafting.s10.kind': { en: 'Document kind', es: 'Tipo de documento' },
  'drafting.s10.blockKind': { en: 'Block kind', es: 'Tipo de bloque' },
  'drafting.s10.form': { en: 'Court form', es: 'Formulario judicial' },
  'drafting.s10.sku': { en: 'Store SKU', es: 'SKU de la tienda' },
  'drafting.s10.nodes': { en: 'Board squares', es: 'Casillas del tablero' },
  'drafting.s10.notes': { en: 'Drafting notes', es: 'Notas de redacción' },
  'drafting.s10.versionLabel': { en: 'Version {n}', es: 'Versión {n}' },
  'drafting.s10.usedBy': { en: '{n} drafts started from it', es: '{n} borradores iniciados con ella' },
};
