import type { StringTable } from '../../i18n/types';

/**
 * Document-pipeline strings (L-13 board, L-14 order detail, S-13 paralegal queue, C-11 client orders, F-14 desk
 * lookup). Stage names themselves are NOT here: they live once in `src/domain/pipeline.ts` as bilingual `label` /
 * `clientLabel` pairs so staff and the client can never see two different vocabularies for the same stage.
 * Document titles are the firm's own product wording and stay in English until the firm supplies Spanish.
 */
export const strings: StringTable = {
  // nav
  'pipeline.nav.board': { en: 'Document pipeline', es: 'Flujo de documentos' },
  'pipeline.nav.queue': { en: 'My document queue', es: 'Mi cola de documentos' },
  'pipeline.nav.orders': { en: 'My orders', es: 'Mis pedidos' },
  'pipeline.nav.desk': { en: 'Order status', es: 'Estado de pedidos' },

  // shared vocabulary
  'pipeline.order': { en: 'Order', es: 'Pedido' },
  'pipeline.orders': { en: 'Orders', es: 'Pedidos' },
  'pipeline.client': { en: 'Client', es: 'Cliente' },
  'pipeline.document': { en: 'Document', es: 'Documento' },
  'pipeline.stage': { en: 'Stage', es: 'Etapa' },
  'pipeline.clientSees': { en: 'The client sees', es: 'El cliente ve' },
  'pipeline.waiting': { en: 'Waiting on', es: 'Esperando a' },
  'pipeline.due': { en: 'Due', es: 'Vence' },
  'pipeline.filingDue': { en: 'Filing due', es: 'Presentación vence' },
  'pipeline.nextDue': { en: 'Next due', es: 'Próximo vencimiento' },
  'pipeline.assignee': { en: 'With', es: 'Con' },
  'pipeline.asked': { en: 'Asked', es: 'Pedido' },
  'pipeline.attorney': { en: 'Attorney', es: 'Abogado' },
  'pipeline.paralegal': { en: 'Paralegal', es: 'Asistente' },
  'pipeline.supervisor': { en: 'Supervisor', es: 'Supervisor' },
  'pipeline.priority': { en: 'Priority', es: 'Prioridad' },
  'pipeline.priority.rush': { en: 'Rush', es: 'Urgente' },
  'pipeline.priority.emergency': { en: 'Emergency', es: 'Emergencia' },
  'pipeline.revision': { en: 'rev {n}', es: 'rev {n}' },
  'pipeline.late': { en: 'Late', es: 'Atrasado' },
  'pipeline.open': { en: 'Open', es: 'Abrir' },
  'pipeline.moveTo': { en: 'Move to', es: 'Mover a' },
  'pipeline.moveToTitle': { en: 'Move {ref} to', es: 'Mover {ref} a' },
  'pipeline.moveHint': { en: 'Only the moves the pipeline allows from this stage are listed (RULE-PIPE-01).', es: 'Solo se listan los movimientos que el flujo permite desde esta etapa (RULE-PIPE-01).' },
  'pipeline.moveNote': { en: 'Note for the history (staff only)', es: 'Nota para el historial (solo personal)' },
  'pipeline.cancel': { en: 'Cancel', es: 'Cancelar' },
  'pipeline.close': { en: 'Close', es: 'Cerrar' },
  'pipeline.save': { en: 'Save', es: 'Guardar' },
  'pipeline.saved': { en: 'Saved', es: 'Guardado' },
  'pipeline.nudge': { en: 'Nudge', es: 'Recordar' },
  'pipeline.nudgeWhat': { en: 'create a follow-up for the front desk to chase this client', es: 'crear un seguimiento para que recepción contacte al cliente' },
  'pipeline.openRequests': { en: '{n} open requests', es: '{n} solicitudes abiertas' },
  'pipeline.openRequest1': { en: '1 open request', es: '1 solicitud abierta' },
  'pipeline.noOrders': { en: 'No orders match', es: 'Ningún pedido coincide' },
  'pipeline.noOrdersBody': { en: 'Widen the filters: clear the search, switch Mine to All, or turn off "late only".', es: 'Amplía los filtros: borra la búsqueda, cambia Míos por Todos o desactiva "solo atrasados".' },
  'pipeline.clearFilters': { en: 'Clear filters', es: 'Limpiar filtros' },
  'pipeline.notFound': { en: 'No order with that id', es: 'No hay pedido con ese id' },
  'pipeline.notFoundBody': { en: 'It may belong to another office, or the link is out of date.', es: 'Puede pertenecer a otra oficina o el enlace está desactualizado.' },
  'pipeline.backToBoard': { en: 'Back to the pipeline', es: 'Volver al flujo' },
  'pipeline.sentVia.app': { en: 'in the app', es: 'en la app' },
  'pipeline.sentVia.email': { en: 'by email', es: 'por correo' },
  'pipeline.sentVia.sms': { en: 'by text', es: 'por mensaje' },
  'pipeline.sentVia.call': { en: 'by phone', es: 'por teléfono' },
  'pipeline.kind.question': { en: 'Question', es: 'Pregunta' },
  'pipeline.kind.item': { en: 'Document or photo', es: 'Documento o foto' },
  'pipeline.kind.review': { en: 'Review', es: 'Revisión' },
  'pipeline.kind.approval': { en: 'Approval', es: 'Aprobación' },
  'pipeline.kind.signature': { en: 'Signature', es: 'Firma' },
  'pipeline.kind.payment': { en: 'Payment', es: 'Pago' },
  'pipeline.docKind.any': { en: 'Any document', es: 'Cualquier documento' },
  'pipeline.docKind.pleading': { en: 'Pleading', es: 'Escrito' },
  'pipeline.docKind.motion': { en: 'Motion', es: 'Moción' },
  'pipeline.docKind.discovery': { en: 'Discovery', es: 'Prueba anticipada' },
  'pipeline.docKind.letter': { en: 'Letter', es: 'Carta' },
  'pipeline.docKind.form': { en: 'Court form', es: 'Formulario' },
  'pipeline.docKind.agreement': { en: 'Agreement', es: 'Acuerdo' },
  'pipeline.docKind.other': { en: 'Other', es: 'Otro' },

  // toasts
  'pipeline.toast.moved': { en: '{ref} moved to {stage}', es: '{ref} pasó a {stage}' },
  'pipeline.toast.badMove': { en: 'That move is not allowed from this stage — nothing was changed', es: 'Ese movimiento no se permite desde esta etapa: no se cambió nada' },
  'pipeline.toast.noAdvance': { en: 'Only an attorney or paralegal moves an order (RULE-PIPE-06)', es: 'Solo un abogado o asistente mueve un pedido (RULE-PIPE-06)' },
  'pipeline.toast.noSupervise': { en: 'Only a supervising attorney moves an order out of supervisor review (RULE-PIPE-04)', es: 'Solo un abogado supervisor saca un pedido de la revisión del supervisor (RULE-PIPE-04)' },
  'pipeline.toast.nudged': { en: 'Follow-up created for {ref}', es: 'Seguimiento creado para {ref}' },
  'pipeline.toast.asked': { en: 'Request sent to the client', es: 'Solicitud enviada al cliente' },
  'pipeline.toast.answered': { en: 'Thank you — we have your answer', es: 'Gracias: ya tenemos tu respuesta' },
  'pipeline.toast.approved': { en: 'Approved. Your attorney takes it from here.', es: 'Aprobado. Tu abogado sigue desde aquí.' },
  'pipeline.toast.changes': { en: 'We have your changes', es: 'Ya tenemos tus cambios' },
  'pipeline.toast.callLogged': { en: 'Call logged', es: 'Llamada registrada' },
  'pipeline.toast.followUp': { en: 'Follow-up added', es: 'Seguimiento añadido' },

  // ---- L-13 board -------------------------------------------------------------------------------------------------
  'pipeline.l13.title': { en: 'Document pipeline', es: 'Flujo de documentos' },
  'pipeline.l13.subtitle': { en: 'Every document the firm owes a client, and whose turn it is.', es: 'Cada documento que el bufete debe a un cliente, y de quién es el turno.' },
  'pipeline.l13.statInProgress': { en: 'In progress', es: 'En curso' },
  'pipeline.l13.statWaiting': { en: 'Waiting on clients', es: 'Esperando a clientes' },
  'pipeline.l13.statWaitingHint': { en: 'longest: {ref}, {days} days', es: 'la más larga: {ref}, {days} días' },
  'pipeline.l13.statLate': { en: 'Late', es: 'Atrasados' },
  'pipeline.l13.statLateHint': { en: 'past a stage target or a due date', es: 'pasada la meta de etapa o una fecha límite' },
  'pipeline.l13.statWeek': { en: 'Due this week', es: 'Vencen esta semana' },
  'pipeline.l13.view.board': { en: 'Board', es: 'Tablero' },
  'pipeline.l13.view.table': { en: 'Table', es: 'Tabla' },
  'pipeline.l13.view.waiting': { en: 'Waiting on clients', es: 'Esperando a clientes' },
  'pipeline.l13.scope.mine': { en: 'Mine', es: 'Míos' },
  'pipeline.l13.scope.all': { en: 'All', es: 'Todos' },
  'pipeline.l13.waitingLabel': { en: 'Waiting on', es: 'Esperando a' },
  'pipeline.l13.waiting.any': { en: 'Anyone', es: 'Cualquiera' },
  'pipeline.l13.waiting.client': { en: 'Client', es: 'Cliente' },
  'pipeline.l13.waiting.attorney': { en: 'Attorney', es: 'Abogado' },
  'pipeline.l13.waiting.paralegal': { en: 'Paralegal', es: 'Asistente' },
  'pipeline.l13.waiting.supervisor': { en: 'Supervisor', es: 'Supervisor' },
  'pipeline.l13.waiting.court': { en: 'Court', es: 'Tribunal' },
  'pipeline.l13.lateOnly': { en: 'Late only', es: 'Solo atrasados' },
  'pipeline.l13.searchLabel': { en: 'Search client, document or order ref', es: 'Buscar cliente, documento o número de pedido' },
  'pipeline.l13.searchPlaceholder': { en: 'Dana, motion to quash, ORD-2026-0131…', es: 'Dana, moción, ORD-2026-0131…' },
  'pipeline.l13.group.intake': { en: 'Intake', es: 'Admisión' },
  'pipeline.l13.group.drafting': { en: 'Drafting', es: 'Redacción' },
  'pipeline.l13.group.review': { en: 'Client review', es: 'Revisión del cliente' },
  'pipeline.l13.group.approval': { en: 'Approval', es: 'Aprobación' },
  'pipeline.l13.group.filing': { en: 'Filing & service', es: 'Presentación y notificación' },
  'pipeline.l13.group.closed': { en: 'Done', es: 'Terminados' },
  'pipeline.l13.side': { en: 'On hold and cancelled ({n})', es: 'En pausa y cancelados ({n})' },
  'pipeline.l13.emptyColumn': { en: 'Nothing here', es: 'Nada aquí' },
  'pipeline.l13.waitingListTitle': { en: 'Orders waiting on a client, longest first', es: 'Pedidos esperando al cliente, del más largo al más corto' },
  'pipeline.l13.waitingListDesc': { en: 'What we asked for, when we asked, and how to chase it. A nudge creates a follow-up for the front desk; the text and email themselves are Pass 3.', es: 'Qué pedimos, cuándo lo pedimos y cómo darle seguimiento. Recordar crea un seguimiento para recepción; los mensajes y correos llegan en el paso 3.' },
  'pipeline.l13.noWaiting': { en: 'Nothing is waiting on a client', es: 'Nada está esperando a un cliente' },
  'pipeline.l13.noWaitingBody': { en: 'Every open order is with the firm or the court right now.', es: 'Todos los pedidos abiertos están con el bufete o con el tribunal.' },
  'pipeline.l13.askedOn': { en: 'asked {date} {via}', es: 'pedido el {date} {via}' },
  'pipeline.l13.col.ref': { en: 'Ref', es: 'Núm.' },
  'pipeline.l13.col.document': { en: 'Document', es: 'Documento' },
  'pipeline.l13.col.client': { en: 'Client', es: 'Cliente' },
  'pipeline.l13.col.stage': { en: 'Stage', es: 'Etapa' },
  'pipeline.l13.col.waiting': { en: 'Waiting on', es: 'Esperando a' },
  'pipeline.l13.col.days': { en: 'Days', es: 'Días' },
  'pipeline.l13.col.due': { en: 'Next due', es: 'Próximo vencimiento' },
  'pipeline.l13.col.with': { en: 'With', es: 'Con' },
  'pipeline.l13.count': { en: '{n} of {total} orders', es: '{n} de {total} pedidos' },

  // ---- L-14 order detail -------------------------------------------------------------------------------------------
  'pipeline.l14.eyebrow': { en: 'Document order', es: 'Pedido de documento' },
  'pipeline.l14.caseLink': { en: 'Open the case on the board', es: 'Abrir el caso en el tablero' },
  'pipeline.l14.noCase': { en: 'No case yet', es: 'Aún sin caso' },
  'pipeline.l14.track': { en: 'Where it is', es: 'Dónde está' },
  'pipeline.l14.trackDesc': { en: 'Staff stages. The plain line under each one is what the client reads (RULE-PIPE-03).', es: 'Etapas internas. La línea sencilla debajo es lo que lee el cliente (RULE-PIPE-03).' },
  'pipeline.l14.tab.timeline': { en: 'Timeline', es: 'Historial' },
  'pipeline.l14.tab.requests': { en: 'Client requests', es: 'Solicitudes al cliente' },
  'pipeline.l14.tab.documents': { en: 'Documents', es: 'Documentos' },
  'pipeline.l14.tab.details': { en: 'Details', es: 'Detalles' },
  'pipeline.l14.tab.activity': { en: 'Activity', es: 'Actividad' },
  'pipeline.l14.timelineDesc': { en: 'Every move, newest first. The history is append-only: a correction is a new event with a note, never a rewrite (RULE-PIPE-08).', es: 'Cada movimiento, del más reciente al más antiguo. El historial solo se añade: una corrección es un evento nuevo con nota, nunca una reescritura (RULE-PIPE-08).' },
  'pipeline.l14.by': { en: 'by {name}', es: 'por {name}' },
  'pipeline.l14.bySystem': { en: 'by the system', es: 'por el sistema' },
  'pipeline.l14.thenWaiting': { en: 'then waiting on {who}', es: 'luego esperando a {who}' },
  'pipeline.l14.askTitle': { en: 'Ask the client for something', es: 'Pedir algo al cliente' },
  'pipeline.l14.askDesc': { en: 'An open request is what makes an order wait on the client (RULE-PIPE-07). It lands in their app and on the desk\'s follow-up list.', es: 'Una solicitud abierta es lo que hace que un pedido espere al cliente (RULE-PIPE-07). Aparece en su app y en la lista de seguimiento de recepción.' },
  'pipeline.l14.askKind': { en: 'What do you need?', es: '¿Qué necesitas?' },
  'pipeline.l14.askPrompt': { en: 'What we ask, in the client\'s words', es: 'Lo que pedimos, en palabras del cliente' },
  'pipeline.l14.askPromptPh': { en: 'Upload the rent ledger for the last 12 months', es: 'Sube el registro de pagos de los últimos 12 meses' },
  'pipeline.l14.askDetail': { en: 'Why we need it and what counts', es: 'Por qué lo necesitamos y qué sirve' },
  'pipeline.l14.askDue': { en: 'Needed by', es: 'Para cuándo' },
  'pipeline.l14.askVia': { en: 'Send via', es: 'Enviar por' },
  'pipeline.l14.askSend': { en: 'Send the request', es: 'Enviar la solicitud' },
  'pipeline.l14.askAlsoMove': { en: 'This order is not waiting on the client yet. Also move it to "Gathering client details"?', es: 'Este pedido aún no espera al cliente. ¿Moverlo también a "Recopilando datos del cliente"?' },
  'pipeline.l14.noRequests': { en: 'Nothing has been asked of this client', es: 'No se le ha pedido nada a este cliente' },
  'pipeline.l14.noRequestsBody': { en: 'Use the form below when the draft needs a fact, a document or an approval.', es: 'Usa el formulario de abajo cuando el borrador necesite un dato, un documento o una aprobación.' },
  'pipeline.l14.answeredOn': { en: 'answered {date}', es: 'respondida el {date}' },
  'pipeline.l14.drafts': { en: 'Drafts', es: 'Borradores' },
  'pipeline.l14.openDrafting': { en: 'Open in the drafting studio', es: 'Abrir en el estudio de redacción' },
  'pipeline.l14.filedCopies': { en: 'Filed and served copies', es: 'Copias presentadas y notificadas' },
  'pipeline.l14.noFiled': { en: 'Nothing filed yet', es: 'Aún no se ha presentado nada' },
  'pipeline.l14.uploadFiled': { en: 'Upload the filed copy', es: 'Subir la copia presentada' },
  'pipeline.l14.details.court': { en: 'Court', es: 'Tribunal' },
  'pipeline.l14.details.caseNumber': { en: 'Case number', es: 'Número de caso' },
  'pipeline.l14.details.boardNode': { en: 'Game-board square', es: 'Casilla del tablero' },
  'pipeline.l14.details.assignments': { en: 'Who is on it', es: 'Quién lo lleva' },
  'pipeline.l14.details.unassigned': { en: 'Unassigned', es: 'Sin asignar' },
  'pipeline.l14.details.assigned': { en: 'Assigned to', es: 'Asignado a' },
  'pipeline.l14.details.notes': { en: 'Internal notes', es: 'Notas internas' },
  'pipeline.l14.details.notesHint': { en: 'Staff only. The client never sees this (RULE-PIPE-03).', es: 'Solo personal. El cliente nunca ve esto (RULE-PIPE-03).' },
  'pipeline.l14.details.summary': { en: 'What the client reads', es: 'Lo que lee el cliente' },
  'pipeline.l14.details.summaryHint': { en: 'The one plain sentence shown in their app and read aloud by the front desk.', es: 'La frase sencilla que aparece en su app y que recepción lee en voz alta.' },
  'pipeline.l14.activityDesc': { en: 'Calls and follow-ups that mention this order.', es: 'Llamadas y seguimientos que mencionan este pedido.' },
  'pipeline.l14.noActivity': { en: 'No calls or follow-ups on this order', es: 'Sin llamadas ni seguimientos en este pedido' },
  'pipeline.l14.sendDraft': { en: 'Send the draft to the client', es: 'Enviar el borrador al cliente' },
  'pipeline.l14.hold': { en: 'Put on hold', es: 'Poner en pausa' },
  'pipeline.l14.resume': { en: 'Resume', es: 'Reanudar' },
  'pipeline.l14.resumeTitle': { en: 'Resume {ref} at', es: 'Reanudar {ref} en' },
  'pipeline.l14.cancelOrder': { en: 'Cancel the order', es: 'Cancelar el pedido' },
  'pipeline.l14.cancelConfirm': { en: 'Cancel {ref}?', es: '¿Cancelar {ref}?' },
  'pipeline.l14.cancelBody': { en: 'Nothing more happens on this order. The history is kept and the client sees "Cancelled". Refunds are handled in payments.', es: 'No pasará nada más con este pedido. El historial se conserva y el cliente ve "Cancelado". Los reembolsos se manejan en pagos.' },
  'pipeline.l14.markFiled': { en: 'Mark filed', es: 'Marcar presentado' },
  'pipeline.l14.markServed': { en: 'Mark served', es: 'Marcar notificado' },
  'pipeline.l14.markProof': { en: 'Proof of service filed', es: 'Prueba de notificación presentada' },
  'pipeline.l14.markHearing': { en: 'Hearing set', es: 'Audiencia fijada' },
  'pipeline.l14.addFollowUp': { en: 'Add a follow-up', es: 'Añadir seguimiento' },
  'pipeline.l14.supervisorOnly': { en: 'A supervising attorney moves it out of supervisor review (RULE-PIPE-04).', es: 'Un abogado supervisor lo saca de la revisión del supervisor (RULE-PIPE-04).' },

  // ---- S-13 paralegal queue -----------------------------------------------------------------------------------------
  'pipeline.s13.title': { en: 'My document queue', es: 'Mi cola de documentos' },
  'pipeline.s13.subtitle': { en: 'Sorted by what is needed from you, not by date.', es: 'Ordenada por lo que se necesita de ti, no por fecha.' },
  'pipeline.s13.gather': { en: 'Gather client details', es: 'Recopilar datos del cliente' },
  'pipeline.s13.gatherDesc': { en: 'Chase the open requests, then move the order on when everything is in.', es: 'Persigue las solicitudes abiertas y mueve el pedido cuando esté todo.' },
  'pipeline.s13.prepare': { en: 'Prepare and assemble', es: 'Preparar y armar' },
  'pipeline.s13.prepareDesc': { en: 'Drafts to build from the template and the client facts, and the ones the supervisor sent back.', es: 'Borradores por armar con la plantilla y los hechos del cliente, y los que devolvió el supervisor.' },
  'pipeline.s13.file': { en: 'File and serve', es: 'Presentar y notificar' },
  'pipeline.s13.fileDesc': { en: 'Signed finals to file, filed documents to serve, and proofs of service to file.', es: 'Documentos firmados por presentar, presentados por notificar y pruebas de notificación por presentar.' },
  'pipeline.s13.waiting': { en: 'Waiting on the client', es: 'Esperando al cliente' },
  'pipeline.s13.waitingDesc': { en: 'Nothing for you to do until they answer — read-only, with a nudge for the desk.', es: 'Nada que hacer hasta que respondan: solo lectura, con un recordatorio para recepción.' },
  'pipeline.s13.empty': { en: 'Nothing in this part of the queue', es: 'Nada en esta parte de la cola' },
  'pipeline.s13.emptyAll': { en: 'Your queue is clear', es: 'Tu cola está vacía' },
  'pipeline.s13.emptyAllBody': { en: 'No order is waiting on you right now. The board shows everything the office has open.', es: 'Ningún pedido te está esperando. El tablero muestra todo lo que la oficina tiene abierto.' },
  'pipeline.s13.openBoard': { en: 'Open the pipeline board', es: 'Abrir el tablero del flujo' },
  'pipeline.s13.draft': { en: 'Draft', es: 'Redactar' },
  'pipeline.s13.mineOnly': { en: 'Assigned to me', es: 'Asignados a mí' },

  // ---- C-11 client orders --------------------------------------------------------------------------------------------
  'pipeline.c11.title': { en: 'My orders', es: 'Mis pedidos' },
  'pipeline.c11.subtitle': { en: 'Every document we are preparing for you.', es: 'Cada documento que estamos preparando para ti.' },
  'pipeline.c11.needYou': { en: 'Waiting on you ({n})', es: 'Te estamos esperando ({n})' },
  'pipeline.c11.needYouBlock': { en: 'We need something from you', es: 'Necesitamos algo de ti' },
  'pipeline.c11.inProgress': { en: 'We are working on these', es: 'Estamos trabajando en estos' },
  'pipeline.c11.finished': { en: 'Finished', es: 'Terminados' },
  'pipeline.c11.noOrders': { en: 'No documents yet', es: 'Aún no hay documentos' },
  'pipeline.c11.noOrdersBody': { en: 'When you order a document — or your attorney starts one for you — it shows up here with every step, so you always know whose turn it is.', es: 'Cuando pidas un documento, o tu abogado empiece uno para ti, aparecerá aquí con cada paso, para que siempre sepas de quién es el turno.' },
  'pipeline.c11.seeServices': { en: 'See what we can prepare', es: 'Ver lo que podemos preparar' },
  'pipeline.c11.progress': { en: 'Progress', es: 'Avance' },
  'pipeline.c11.whatNext': { en: 'What happens next', es: 'Qué sigue' },
  'pipeline.c11.whoIsWorking': { en: 'Who is working on it', es: 'Quién lo está trabajando' },
  'pipeline.c11.yourAttorney': { en: 'Your attorney', es: 'Tu abogado' },
  'pipeline.c11.office': { en: 'Office', es: 'Oficina' },
  'pipeline.c11.started': { en: 'Started', es: 'Empezado' },
  'pipeline.c11.expected': { en: 'Expected by', es: 'Previsto para' },
  'pipeline.c11.requests': { en: 'What we need from you', es: 'Lo que necesitamos de ti' },
  'pipeline.c11.nothingNeeded': { en: 'Nothing is needed from you right now', es: 'Ahora mismo no necesitamos nada de ti' },
  'pipeline.c11.answer': { en: 'Answer', es: 'Responder' },
  'pipeline.c11.answerPh': { en: 'Type your answer…', es: 'Escribe tu respuesta…' },
  'pipeline.c11.send': { en: 'Send', es: 'Enviar' },
  'pipeline.c11.upload': { en: 'Upload it', es: 'Subirlo' },
  'pipeline.c11.uploadWhat': { en: 'add the photo or document to your binder', es: 'añadir la foto o el documento a tu carpeta' },
  'pipeline.c11.reviewDraft': { en: 'Your draft is ready to read', es: 'Tu borrador está listo para leer' },
  'pipeline.c11.reviewDesc': { en: 'Read it once. If it says what happened, approve it. If anything is wrong, tell us and we will fix it — that is what this step is for.', es: 'Léelo una vez. Si dice lo que pasó, apruébalo. Si algo está mal, dínoslo y lo corregimos: para eso es este paso.' },
  'pipeline.c11.approve': { en: 'Approve', es: 'Aprobar' },
  'pipeline.c11.requestChanges': { en: 'Request changes', es: 'Pedir cambios' },
  'pipeline.c11.changesTitle': { en: 'What should we change?', es: '¿Qué debemos cambiar?' },
  'pipeline.c11.changesPh': { en: 'The move-in date should be March 2023, not 2024…', es: 'La fecha de mudanza debe ser marzo de 2023, no 2024…' },
  'pipeline.c11.changesSend': { en: 'Send the changes', es: 'Enviar los cambios' },
  'pipeline.c11.due': { en: 'by {date}', es: 'para el {date}' },
  'pipeline.c11.answered': { en: 'Answered', es: 'Respondida' },
  'pipeline.c11.received': { en: 'Received', es: 'Recibido' },
  'pipeline.c11.back': { en: 'All my orders', es: 'Todos mis pedidos' },
  'pipeline.c11.yourSteps': { en: 'Your steps', es: 'Tus pasos' },
  'pipeline.c11.paused': { en: 'Paused at your request', es: 'En pausa a petición tuya' },
  'pipeline.c11.next.new_order': { en: 'We are assigning your attorney. You will hear from us within a business day.', es: 'Estamos asignando a tu abogado. Sabrás de nosotros en un día hábil.' },
  'pipeline.c11.next.payment_confirmed': { en: 'Your payment is in. We are putting an attorney and an assistant on it.', es: 'Tu pago está confirmado. Estamos asignando abogado y asistente.' },
  'pipeline.c11.next.gathering_client_details': { en: 'We are waiting on you. Answer the questions below and we start drafting the same day.', es: 'Te estamos esperando. Responde abajo y empezamos a redactar el mismo día.' },
  'pipeline.c11.next.first_draft': { en: 'Your attorney is writing it. You will get it to read before anything is filed.', es: 'Tu abogado lo está escribiendo. Lo recibirás para leerlo antes de presentar nada.' },
  'pipeline.c11.next.client_review': { en: 'Read the draft and approve it, or tell us what to change.', es: 'Lee el borrador y apruébalo, o dinos qué cambiar.' },
  'pipeline.c11.next.client_requested_changes': { en: 'We are making your changes and will send it back to you.', es: 'Estamos haciendo tus cambios y te lo enviaremos de nuevo.' },
  'pipeline.c11.next.approved_by_client': { en: 'A second attorney checks it before it is signed.', es: 'Un segundo abogado lo revisa antes de firmarlo.' },
  'pipeline.c11.next.supervisor_review': { en: 'A supervising attorney is doing the final legal check.', es: 'Un abogado supervisor hace la revisión legal final.' },
  'pipeline.c11.next.final_signed': { en: 'Signed. We are filing or delivering it now.', es: 'Firmado. Lo estamos presentando o entregando.' },
  'pipeline.c11.next.filed_or_scheduled': { en: 'It is with the court. We will tell you the moment we hear back.', es: 'Está en el tribunal. Te avisaremos en cuanto sepamos algo.' },
  'pipeline.c11.next.served': { en: 'The other side has it. We file the proof of service next.', es: 'La otra parte ya lo tiene. Ahora presentamos la prueba de notificación.' },
  'pipeline.c11.next.hearing_scheduled': { en: 'Your hearing date is set — check your calendar in the app.', es: 'Tu audiencia tiene fecha: revisa tu calendario en la app.' },
  'pipeline.c11.next.done': { en: 'This one is finished. The copy is in your binder.', es: 'Este ya está terminado. La copia está en tu carpeta.' },
  'pipeline.c11.next.on_hold': { en: 'Paused. Tell us when you want us to pick it back up.', es: 'En pausa. Dinos cuándo quieres que lo retomemos.' },
  'pipeline.c11.next.cancelled': { en: 'This order was cancelled.', es: 'Este pedido fue cancelado.' },

  // ---- F-14 desk order lookup --------------------------------------------------------------------------------------
  'pipeline.f14.title': { en: 'Order status', es: 'Estado de pedidos' },
  'pipeline.f14.subtitle': { en: 'Find any order while the client is on the phone.', es: 'Encuentra cualquier pedido mientras el cliente está al teléfono.' },
  'pipeline.f14.searchLabel': { en: 'Name, phone, order ref or case number', es: 'Nombre, teléfono, número de pedido o de caso' },
  'pipeline.f14.searchPlaceholder': { en: 'Morales, 951 555 0142, ORD-2026-0131, UD-2026-004182', es: 'Morales, 951 555 0142, ORD-2026-0131, UD-2026-004182' },
  'pipeline.f14.col.staffStage': { en: 'Stage (staff)', es: 'Etapa (interna)' },
  'pipeline.f14.col.clientStage': { en: 'What the client is told', es: 'Lo que se le dice al cliente' },
  'pipeline.f14.col.lastTouch': { en: 'Last client touch', es: 'Último contacto' },
  'pipeline.f14.drawerTitle': { en: 'Status card', es: 'Ficha de estado' },
  'pipeline.f14.script': { en: 'Read this out', es: 'Léelo así' },
  'pipeline.f14.scriptLine1': { en: 'Your {title}: {clientStage}.', es: 'Tu {title}: {clientStage}.' },
  'pipeline.f14.scriptLine2': { en: 'It is with {who}.', es: 'Lo tiene {who}.' },
  'pipeline.f14.scriptLine3Client': { en: 'We are waiting on you for: {what}', es: 'Estamos esperando esto de ti: {what}' },
  'pipeline.f14.scriptLine3Us': { en: 'The next step is {next}{by}.', es: 'El siguiente paso es {next}{by}.' },
  'pipeline.f14.scriptBy': { en: ' by {date}', es: ' para el {date}' },
  'pipeline.f14.copyScript': { en: 'Copy the script', es: 'Copiar el texto' },
  'pipeline.f14.whereItStands': { en: 'Where it stands', es: 'Cómo va' },
  'pipeline.f14.remind': { en: 'Remind the caller about', es: 'Recuérdale al cliente' },
  'pipeline.f14.nothingOpen': { en: 'Nothing is owed by the client on this order.', es: 'El cliente no debe nada en este pedido.' },
  'pipeline.f14.logCall': { en: 'Log this call', es: 'Registrar la llamada' },
  'pipeline.f14.callNotes': { en: 'What was said', es: 'Qué se habló' },
  'pipeline.f14.callNotesPh': { en: 'Asked where the Answer stands; told her it is with her for approval.', es: 'Preguntó por el estado; le dije que está con ella para aprobación.' },
  'pipeline.f14.noAdvance': { en: 'The front desk does not move stages', es: 'Recepción no mueve etapas' },
  'pipeline.f14.noAdvanceTip': { en: 'Moving an order is the attorney\'s or paralegal\'s action (orders.advance, RULE-PIPE-06). You can log the call and add a follow-up, and they will see it on their board.', es: 'Mover un pedido es acción del abogado o del asistente (orders.advance, RULE-PIPE-06). Tú puedes registrar la llamada y añadir un seguimiento, y ellos lo verán en su tablero.' },
  'pipeline.f14.empty': { en: 'Search for a caller', es: 'Busca a quien llama' },
  'pipeline.f14.emptyBody': { en: 'Type a name, a phone number, an order ref or a case number. Results appear as you type.', es: 'Escribe un nombre, un teléfono, un número de pedido o de caso. Los resultados aparecen mientras escribes.' },
  'pipeline.f14.noMatch': { en: 'Nothing matches that', es: 'Nada coincide' },
  'pipeline.f14.noMatchBody': { en: 'Try the last name alone, or the last four digits of the phone number.', es: 'Prueba solo el apellido o los últimos cuatro dígitos del teléfono.' },
  'pipeline.f14.openFull': { en: 'Open the full order', es: 'Abrir el pedido completo' },
};
