import { defineSpec } from '../../specs/defineSpec';

const CHECKED = [360, 390, 768, 1280, 1920, 2560, 3840];
const ROLES = ['super_admin' as const, 'owner' as const];
/** No `permission` on these: they are view controls (zoom, pan, pick a device), and both allowed roles must be able to run them (owner has every permission except `dev.tools`). */

export const canvasSpec = defineSpec({
  code: 'D-21', name: 'Canvas',
  purpose: 'A free-form zoomable canvas of resizable browser windows (D-049): open any page of CTL OS as a window, size it to any device from a phone to a 4K TV, arrange the windows freely, save the arrangement, and switch on a second level that draws what each type of user can do as flow-chart lines between the windows.',
  layout: [
    'PageHeader (title, live-window counter, toolbar or - on a phone - a Tools button)',
    'Toolbar (zoom out / level / zoom in / 100 % / Fit all / Fit selection; preset; Add window; Inspector; Remove; Show flows + role + Focus on this role + Step through; live cap, frame language, frame builder tool; layout select, name, Save, Rename, Delete)',
    'Hint row (pan, zoom and key map; the tooltip explains the per-window role)',
    'UndoBar (a removed window comes back for 8 seconds)',
    'CanvasViewport (grid-dot world: group boxes, the flows layer, the BrowserWindows)',
    'FlowLegend (the four KEY colours, in a corner)',
    'Minimap (every window plus the viewport rectangle; point at it to move the view)',
    'StepCaption (the current flow step, Back / Next / Exit)',
    'Drawers (Tools on a phone, Add / Find a page, Window inspector: X, Y, width, height, device, role, language, address)',
    'ListView (inside a frame: every page as a list, because a canvas inside a canvas is nonsense)',
  ],
  data: ['canvas_layouts'], roles: ROLES,
  logic: [
    'The world is transform-based: one translate + scale on a world div, every window absolutely positioned in world pixels, so a pan or a zoom is one composited transform and not fifty layout passes.',
    'Zoom 0.04..2 with buttons, + / - keys, the wheel (anchored on the cursor; Shift+wheel pans), two-finger pinch on touch, Fit all, Fit selection, 100 % and F.',
    'Windows carry { id, code, path, x, y, w, h, device, role, lang, z }. Device presets: phone 390x844, tablet 768x1024, laptop 1280x800, desktop 1920x1080, TV 3840x2160 (shown at half size); the framed page renders at the device viewport and is transform-scaled into the window body.',
    'Drag by the title bar, resize from all eight handles, both committed in a requestAnimationFrame; the same moves are on the keyboard (arrows move by 16 px, Shift+arrows resize, Alt+arrows snap to a neighbour) and in the inspector as numbers, so nothing is drag-only.',
    'A transparent capture layer covers the body while dragging or resizing and whenever the zoom is under 0.5, so the iframe cannot swallow the gesture; clicking it (or Enter on the window) "enters" the window and hands the page the pointer.',
    'Live iframes are capped (default 8, 4 / 8 / 12 / 20) and chosen by distance from the viewport centre once the view settles; everything else is a wireframe tile with a Load button, and under 0.2 zoom every window is a tile.',
    'Presets: "All pages by surface" shelf-packs every page code into labelled surface groups (canvasLayout.ts); "Per role" gives one row per surface that role can reach, from the routes\' own roles arrays (D-048); "Pipeline walkthrough" reads the seeded canvas_layouts row cvl_pipeline_walkthrough and places its windows even when a path is not built yet - the frame then shows whatever that route renders, honestly.',
    'Layouts are canvas_layouts rows (name, owner_user_id, viewport, windows, flows_visible, role_filter) written through the DataProvider by id; the current viewport, windows and toggles also persist per viewer in localStorage ctl.canvas.v2.',
    'Selection: click, Shift+click to add; Delete removes the selection and an undo bar brings it back for 8 seconds (canvas.undo).',
    'Flows: ROLE_FLOWS[role] (src/flows/roleFlows.ts) drawn in world coordinates - a page step on the first window with that code, a page step with no window as a dashed ghost with an Add window button beside its predecessor, and action / decision / hand-off steps as pills / diamonds / role tags beside the window of the page they happen on. Edges use the game board KEY colours (normal, positive, negative, hand-off = the jump colour) with labels at the midpoints and arrowheads, and a cross-role hand-off names the target role.',
    'Step through walks the flow: the current step\'s window glows, the rest dim, the caption names the step, Fit selection moves the view, Left / Right step and Escape leaves. "Focus on this role" hides every window the role\'s flow does not touch.',
    'Every window runs as its own role through the iframe hash (?as=&lang=&dev=&theme=&brand=) applied by frameSession.ts inside the frame only, so the canvas never changes your own session.',
  ],
  integrations: [], components: ['PageHeader', 'Card', 'Button', 'IconButton', 'Select', 'Input', 'Checkbox', 'Toggle', 'SearchInput', 'Badge', 'StatusBadge', 'Kbd', 'BrandArt', 'Tooltip', 'EmptyState', 'Drawer', 'Toast', 'BrowserWindow', 'FlowLayer'],
  actions: [
    { id: 'canvas.zoomIn', label: 'Zoom in', intent: 'zoom the canvas in' },
    { id: 'canvas.zoomOut', label: 'Zoom out', intent: 'zoom the canvas out' },
    { id: 'canvas.zoomTo', label: 'Zoom to', intent: 'zoom the canvas to a level', params: { level: 'number' } },
    { id: 'canvas.fitAll', label: 'Fit all', intent: 'fit every window into the view' },
    { id: 'canvas.fitSelection', label: 'Fit selection', intent: 'fit the selected windows into the view' },
    { id: 'canvas.pan', label: 'Pan', intent: 'move the canvas view by an amount', params: { dx: 'number', dy: 'number' } },
    { id: 'canvas.addWindow', label: 'Add window', intent: 'put a page on the canvas as a window, running as a role', params: { code: 'string', role: 'enum:super_admin,owner,attorney,paralegal,front_desk,marketing,client,opposing_counsel,public' } },
    { id: 'canvas.removeWindow', label: 'Remove window', intent: 'take a window off the canvas', params: { id: 'string' } },
    { id: 'canvas.duplicateWindow', label: 'Duplicate window', intent: 'copy a window beside itself', params: { id: 'string' } },
    { id: 'canvas.moveWindow', label: 'Move window', intent: 'move a window to a position on the canvas', params: { id: 'string', x: 'number', y: 'number' } },
    { id: 'canvas.resizeWindow', label: 'Resize window', intent: 'set a window\'s width and height', params: { id: 'string', w: 'number', h: 'number' } },
    { id: 'canvas.setWindowDevice', label: 'Window device', intent: 'show a window at a device size', params: { id: 'string', device: 'enum:phone,tablet,laptop,desktop,tv' } },
    { id: 'canvas.setWindowRole', label: 'Window role', intent: 'run a window as a different role', params: { id: 'string', role: 'enum:super_admin,owner,attorney,paralegal,front_desk,marketing,client,opposing_counsel,public' } },
    { id: 'canvas.setWindowLang', label: 'Window language', intent: 'run a window in English or Spanish', params: { id: 'string', lang: 'enum:en,es' } },
    { id: 'canvas.setWindowPath', label: 'Window address', intent: 'point a window at another page', params: { id: 'string', path: 'string' } },
    { id: 'canvas.selectWindow', label: 'Select window', intent: 'select a window', params: { id: 'string' } },
    { id: 'canvas.focusWindow', label: 'Focus window', intent: 'zoom to one window and put the keyboard in it', params: { id: 'string' } },
    { id: 'canvas.bringToFront', label: 'Bring to front', intent: 'bring a window to the front of the stack', params: { id: 'string' } },
    { id: 'canvas.enterWindow', label: 'Enter window', intent: 'hand the pointer to the page inside a window', params: { id: 'string' } },
    { id: 'canvas.openPage', label: 'Open the page', intent: 'leave the canvas and open a window\'s page for real', params: { id: 'string' } },
    { id: 'canvas.preset', label: 'Lay out', intent: 'lay the canvas out by surface, per role, or as the pipeline walkthrough', params: { name: 'enum:surface,role,pipeline' } },
    { id: 'canvas.saveLayout', label: 'Save layout', intent: 'save this arrangement under a name', permission: 'canvas.write', params: { name: 'string' } },
    { id: 'canvas.loadLayout', label: 'Load layout', intent: 'load a saved arrangement', params: { id: 'string' } },
    { id: 'canvas.renameLayout', label: 'Rename layout', intent: 'rename a saved arrangement', permission: 'canvas.write', params: { id: 'string', name: 'string' } },
    { id: 'canvas.deleteLayout', label: 'Delete layout', intent: 'delete a saved arrangement', permission: 'canvas.write', params: { id: 'string' } },
    { id: 'canvas.toggleFlows', label: 'Show flows', intent: 'show or hide the role flow lines', params: { on: 'boolean' } },
    { id: 'canvas.setFlowRole', label: 'Flow role', intent: 'draw the flow of a particular role', params: { role: 'enum:super_admin,owner,attorney,paralegal,front_desk,marketing,client,opposing_counsel,public' } },
    { id: 'canvas.stepFlow', label: 'Step through', intent: 'walk the flow one step at a time', params: { dir: 'enum:next,back,start,exit' } },
    { id: 'canvas.focusRole', label: 'Focus on this role', intent: 'hide every window this role\'s flow does not touch', params: { role: 'enum:super_admin,owner,attorney,paralegal,front_desk,marketing,client,opposing_counsel,public' } },
    { id: 'canvas.setLiveCap', label: 'Live windows', intent: 'set how many windows may be live at once', params: { n: 'number' } },
    { id: 'canvas.setFrameLang', label: 'Frame language', intent: 'set the language every window runs in', params: { lang: 'enum:en,es' } },
    { id: 'canvas.setFrameDev', label: 'Frame builder tool', intent: 'turn the builder tool on or off inside the windows', params: { on: 'boolean' } },
    { id: 'canvas.find', label: 'Find a page', intent: 'search the pages you can put on the canvas', params: { q: 'string' } },
    { id: 'canvas.filterSurface', label: 'Filter by surface', intent: 'narrow the page list to one surface', params: { surface: 'string' } },
    { id: 'canvas.filterBuilt', label: 'Built only', intent: 'show only pages that are built in the page list', params: { on: 'boolean' } },
    { id: 'canvas.undo', label: 'Undo remove', intent: 'bring back the window you just removed' },
  ],
  rules: ['RULE-SYS-01'], states: ['fit all', 'zoomed in (windows live)', 'zoomed out (wireframe tiles)', 'window selected', 'multi-selection', 'dragging or resizing', 'window entered', 'flows shown', 'walking a flow', 'focused on one role', 'layout saved', 'inside a frame (list)'],
  notes: [
    'showcase module (T-025, rebuilt for D-049 under prompt 0006). Supersedes the shelf-packed viewer: the packing survives as the "All pages by surface" preset in canvasLayout.ts.',
    'Nothing on this page is unwired, so there is no Placeholder: saving, loading, renaming and deleting layouts all write canvas_layouts through the DataProvider. Sharing a layout with another viewer is the RLS line in the schema, not a control yet.',
    'Window roles are set by the iframe hash and frameSession.ts, which shadows ctl.session / ctl.lang / ctl.theme inside the frame only - no shared file is edited.',
    'The old spec claimed page_layouts; the canvas writes canvas_layouts (D-051) and page_layouts stays the per-page-code table.',
  ],
  checkedAt: CHECKED,
});

export const simulatorSpec = defineSpec({
  code: 'D-22', name: 'Demo simulator',
  purpose: 'Present any page of CTL OS at any size, as any demo role, in either language: phone, tablet, laptop, desktop and 4K TV frames with a present mode and a scripted tour, so a demo needs no screen sharing gymnastics.',
  layout: [
    'PageHeader (title, the current viewport as a badge, Present)',
    'Controls (device segmented control, rotate, page select grouped by surface family, role select, language, theme, builder tool, Present, Tour, screenshot placeholder)',
    'Device pill (Auto: <device> / Pinned: <device>, pin toggle, Responsive-check badge when a pinned device is not the one the surface is used on) and the share note',
    'Stage (DeviceFrame with the device drawn around the screen, scaled to fit the window whole)',
    'Tour (step counter, note, Back / Next)',
    'ShortcutHint (shown once)',
  ],
  data: ['page_layouts'], roles: ROLES,
  logic: [
    'Device presets: phone 360 and 390, tablet 768, laptop 1280, monitor 1920 and 2560, 4K TV 3840; the iframe really is that wide (the page picks its own --scale band) and the frame is scaled down so the whole device fits the window.',
    'Each preset draws its own hardware (D-050): phone (rounded bezel, dynamic island, home indicator), tablet (bezel, camera dot), laptop 1280 (screen bezel, hinge, keyboard deck), monitor 1920 / 2560 (thin bezel, neck and base), TV 3840 (very thin bezel, feet, "10-foot view" caption).',
    'The device follows the route unless the viewer pins one (D-050): customer -> phone 390, owner -> 2560, public -> laptop 1280, dev and plan -> laptop 1280, every other staff surface -> 1920. Picking a device by hand pins it (?pin=1); "Auto" hands control back to the route. A pinned device of a different kind from the route\'s is labelled "Responsive check", so a client-app demo is never passed off as a desktop product.',
    'Orientation swaps width and height for phone and tablet only.',
    'Pages come from the route manifest, listed under a heading per surface family; choosing one sets the role to that surface\'s demo role (client for the client app, front desk for the desk, attorney for counsel...). Parameterised paths are filled with the same sample ids the QA scripts use.',
    'Role, language, theme and builder tool are passed through the iframe hash (?as=&dev=&lang=&theme=) and applied inside the frame only (frameSession.ts), so presenting never changes your own session.',
    'Device, pin, page, role, language, theme, rotation, present mode and tour step live in the URL query (?device=&pin=&route=&role=&lang=&theme=&dev=&rot=&present=&step=), so a link reopens the same demo.',
    'The tour is a scripted sequence on the right device each time: hub (laptop), the client\'s orders on phone 390, the game board, the attorney pipeline on 1920, the owner on 2560, the proposal on a laptop. A step whose page is still being built falls back to the nearest page that exists and says so.',
    'Present mode hides the page chrome and leaves the device, its identity badges and the tour buttons; the keyboard shortcuts show once (remembered in localStorage ctl.simulator). Keyboard: P present, arrows step the tour, D cycles the device, R rotates (phone and tablet only), Esc leaves.',
  ],
  integrations: [], components: ['PageHeader', 'Card', 'Button', 'IconButton', 'Icon', 'Select', 'SegmentedControl', 'Toggle', 'Badge', 'DeviceFrame', 'Kbd', 'Placeholder', 'Tooltip'],
  actions: [
    { id: 'showcase.setDevice', label: 'Device', intent: 'show the demo on a device (and pin it)', params: { device: 'enum:phone360,phone390,tablet768,laptop1280,desktop1920,tv2560,tv3840' } },
    { id: 'showcase.pinDevice', label: 'Pin device', intent: 'keep this device while moving through pages, or let it follow again', params: { on: 'boolean' } },
    { id: 'showcase.autoDevice', label: 'Auto device', intent: 'let the device follow the page\'s surface again' },
    { id: 'showcase.setRoute', label: 'Page', intent: 'show a page in the simulator', params: { path: 'string' } },
    { id: 'showcase.setRole', label: 'Role', intent: 'run the framed page as a demo role', params: { role: 'enum:super_admin,owner,attorney,paralegal,front_desk,marketing,client,opposing_counsel,public' } },
    { id: 'showcase.setLang', label: 'Language', intent: 'run the framed page in English or Spanish', params: { lang: 'enum:en,es' } },
    { id: 'showcase.setTheme', label: 'Theme', intent: 'run the framed page in light or dark', params: { theme: 'enum:light,dark' } },
    { id: 'showcase.setDevMode', label: 'Builder tool', intent: 'turn the builder tool on or off inside the frame', params: { on: 'boolean' } },
    { id: 'showcase.rotate', label: 'Rotate', intent: 'rotate the phone or tablet frame' },
    { id: 'showcase.present', label: 'Present', intent: 'enter or leave present mode', params: { on: 'boolean' } },
    { id: 'showcase.tourStart', label: 'Start tour', intent: 'start the scripted demo tour' },
    { id: 'showcase.tourNext', label: 'Next', intent: 'go to the next step of the tour' },
    { id: 'showcase.tourBack', label: 'Back', intent: 'go back one step of the tour' },
    { id: 'showcase.tourStop', label: 'End tour', intent: 'end the scripted demo tour' },
    { id: 'showcase.screenshot', label: 'Screenshot', intent: 'save a picture of the framed page' },
  ],
  rules: ['RULE-SYS-01'], states: ['default', 'device follows the route', 'device pinned', 'responsive check (pinned mismatch)', 'present mode', 'tour running', 'rotated', 'Spanish', 'dark', 'inside a frame'],
  notes: ['showcase module (T-026, T-124 pass 2 wave A: device chrome per preset and the device follows the route, D-050). Screenshot is a Placeholder (plannedIn: screenshot pass): a same-origin iframe cannot be rasterised from the page, so it needs the Playwright pass or a browser API.'],
  checkedAt: CHECKED,
});
