import type { StringTable } from '../../i18n/types';

/** Chrome of the canvas (D-21) and the demo simulator (D-22). Page content comes from the framed pages themselves. */
export const strings: StringTable = {
  // shared
  'showcase.built': { en: 'Built', es: 'Construida' },
  'showcase.stub': { en: 'Stub', es: 'Pendiente' },
  'showcase.open': { en: 'Open', es: 'Abrir' },
  'showcase.openFull': { en: 'Open the full page', es: 'Abrir la página completa' },
  'showcase.focus': { en: 'Focus', es: 'Ampliar' },
  'showcase.close': { en: 'Close', es: 'Cerrar' },
  'showcase.role': { en: 'Role', es: 'Rol' },
  'showcase.lang': { en: 'Language', es: 'Idioma' },
  'showcase.theme': { en: 'Theme', es: 'Tema' },
  'showcase.devMode': { en: 'Builder tool', es: 'Herramienta' },
  'showcase.framed': { en: 'This page lays out other pages, so inside a frame it shows the list instead. Open it in a full window.', es: 'Esta página organiza otras páginas, así que dentro de un marco muestra la lista. Ábrela en una ventana completa.' },
  'showcase.frameRoleNote': { en: 'Each frame runs as the role of its surface (hash params as / dev / lang / theme); it never changes your own session.', es: 'Cada marco se ejecuta con el rol de su superficie (parámetros as / dev / lang / theme); nunca cambia tu propia sesión.' },

  // canvas
  'canvas.title': { en: 'Canvas', es: 'Lienzo' },
  'canvas.subtitle': { en: 'Every page of CTL OS laid out on one surface. Zoom in and use any page right inside its frame.', es: 'Todas las páginas de CTL OS en una sola superficie. Acércate y usa cualquier página dentro de su marco.' },
  'canvas.zoomIn': { en: 'Zoom in', es: 'Acercar' },
  'canvas.zoomOut': { en: 'Zoom out', es: 'Alejar' },
  'canvas.fitAll': { en: 'Fit all', es: 'Ver todo' },
  'canvas.fitRegion': { en: 'Fit group', es: 'Ver grupo' },
  'canvas.region': { en: 'Group', es: 'Grupo' },
  'canvas.allRegions': { en: 'All groups', es: 'Todos los grupos' },
  'canvas.builtOnly': { en: 'Built only', es: 'Solo construidas' },
  'canvas.search': { en: 'Search pages', es: 'Buscar páginas' },
  'canvas.surface': { en: 'Surface', es: 'Superficie' },
  'canvas.allSurfaces': { en: 'All surfaces', es: 'Todas las superficies' },
  'canvas.live': { en: '{n} live of {total}', es: '{n} activos de {total}' },
  'canvas.liveCap': { en: 'Live frames are capped at {cap} so the canvas stays usable; the rest load when they come into view or when you focus them.', es: 'Los marcos activos se limitan a {cap} para que el lienzo siga siendo usable; el resto cargan al entrar en vista o al ampliarlos.' },
  'canvas.loadFrame': { en: 'Load this page', es: 'Cargar esta página' },
  'canvas.notLoaded': { en: 'Not loaded', es: 'Sin cargar' },
  'canvas.minimap': { en: 'Minimap', es: 'Mapa' },
  'canvas.pan': { en: 'Drag the background to pan, or use the arrow keys. Ctrl + wheel zooms.', es: 'Arrastra el fondo para desplazar, o usa las flechas. Ctrl + rueda para el zoom.' },
  'canvas.keys': { en: 'Keys: + / − zoom · 0 fit all · arrows pan · Enter focuses the selected frame · Esc closes it', es: 'Teclas: + / − zoom · 0 ver todo · flechas desplazar · Enter amplía el marco seleccionado · Esc lo cierra' },
  'canvas.narrow': { en: 'The canvas is best on a larger screen', es: 'El lienzo se ve mejor en una pantalla grande' },
  'canvas.narrowBody': { en: 'On a phone it lists every page instead of laying them out. Open it on a laptop, a monitor or the TV to pan and zoom the layout.', es: 'En un teléfono lista todas las páginas en vez de organizarlas. Ábrelo en un portátil, un monitor o la TV para desplazar y hacer zoom.' },
  'canvas.list': { en: 'All pages', es: 'Todas las páginas' },
  'canvas.empty': { en: 'No page matches the filter', es: 'Ninguna página coincide con el filtro' },
  'canvas.frameOf': { en: '{code} · {name}', es: '{code} · {name}' },
  'canvas.viewport': { en: 'Canvas surface', es: 'Superficie del lienzo' },

  // simulator
  'sim.title': { en: 'Demo simulator', es: 'Simulador de demostración' },
  'sim.subtitle': { en: 'Present any page at any size, as any demo role, in either language. Phone to 4K TV.', es: 'Presenta cualquier página en cualquier tamaño, con cualquier rol demo y en los dos idiomas. Del teléfono a la TV 4K.' },
  'sim.device': { en: 'Device', es: 'Dispositivo' },
  'sim.page': { en: 'Page', es: 'Página' },
  'sim.rotate': { en: 'Rotate', es: 'Girar' },
  'sim.portrait': { en: 'Portrait', es: 'Vertical' },
  'sim.landscape': { en: 'Landscape', es: 'Horizontal' },
  'sim.present': { en: 'Present', es: 'Presentar' },
  'sim.exitPresent': { en: 'Exit present mode', es: 'Salir del modo presentación' },
  'sim.tour': { en: 'Tour', es: 'Recorrido' },
  'sim.tourStart': { en: 'Start the tour', es: 'Iniciar el recorrido' },
  'sim.tourStop': { en: 'End the tour', es: 'Terminar el recorrido' },
  'sim.next': { en: 'Next', es: 'Siguiente' },
  'sim.back': { en: 'Back', es: 'Atrás' },
  'sim.step': { en: 'Step {n} of {total}', es: 'Paso {n} de {total}' },
  'sim.screenshot': { en: 'Screenshot', es: 'Captura' },
  'sim.shortcuts': { en: 'P presents · → / ← step the tour · R rotates · Esc leaves present mode', es: 'P presenta · → / ← avanza el recorrido · R gira · Esc sale de la presentación' },
  'sim.gotIt': { en: 'Got it', es: 'Entendido' },
  'sim.share': { en: 'The address bar carries the device, page, role and language, so a link opens the same demo.', es: 'La barra de direcciones lleva dispositivo, página, rol e idioma, así que un enlace abre la misma demostración.' },
  'sim.tour.hub': { en: 'The testing hub: every surface, as any demo person', es: 'El centro de pruebas: cada superficie, como cualquier persona demo' },
  'sim.tour.client': { en: 'The tenant opens the app on their phone', es: 'El inquilino abre la app en su teléfono' },
  'sim.tour.board': { en: 'The eviction game board: where the case stands', es: 'El tablero del desalojo: dónde está el caso' },
  'sim.tour.counsel': { en: 'The regional attorney starts the day', es: 'El abogado regional empieza el día' },
  'sim.tour.plan': { en: 'The build plan of CTL OS itself', es: 'El plan de construcción de CTL OS' },
  'sim.tour.proposal': { en: 'The proposal, on the big screen', es: 'La propuesta, en la pantalla grande' },
  'sim.missing': { en: 'This page is not built yet, so the tour shows the hub instead.', es: 'Esta página aún no existe, así que el recorrido muestra el centro.' },
};
