import type { StringTable } from '../../i18n/types';

/** Chrome of the canvas (D-21) and the demo simulator (D-22). Page content comes from the framed pages themselves. */
export const strings: StringTable = {
  // shared
  'showcase.built': { en: 'Built', es: 'Construida' },
  'showcase.stub': { en: 'Stub', es: 'Pendiente' },
  'showcase.open': { en: 'Open', es: 'Abrir' },
  'showcase.openFull': { en: 'Open the full page', es: 'Abrir la página completa' },
  'showcase.focus': { en: 'Focus', es: 'Ampliar' },
  'showcase.close': { en: 'Close', es: 'Cerrar' },
  'showcase.role': { en: 'Role', es: 'Rol' },
  'showcase.lang': { en: 'Language', es: 'Idioma' },
  'showcase.theme': { en: 'Theme', es: 'Tema' },
  'showcase.devMode': { en: 'Builder tool', es: 'Herramienta' },
  'showcase.framed': { en: 'This page lays out other pages, so inside a frame it shows the list instead. Open it in a full window.', es: 'Esta página organiza otras páginas, así que dentro de un marco muestra la lista. Ábrela en una ventana completa.' },
  'showcase.frameRoleNote': { en: 'Each frame runs as the role of its surface (hash params as / dev / lang / theme); it never changes your own session.', es: 'Cada marco se ejecuta con el rol de su superficie (parámetros as / dev / lang / theme); nunca cambia tu propia sesión.' },

  // canvas (D-21, D-049)
  'canvas.title': { en: 'Canvas', es: 'Lienzo' },
  'canvas.subtitle': { en: 'A zoomable canvas of browser windows: open any page at any size, arrange them freely, save the arrangement, and switch on the flow lines to see what each type of user can do.', es: 'Un lienzo con zoom lleno de ventanas de navegador: abre cualquier página a cualquier tamaño, colócalas como quieras, guarda la disposición y activa las líneas de flujo para ver lo que puede hacer cada tipo de usuario.' },
  'canvas.viewport': { en: 'Canvas surface', es: 'Superficie del lienzo' },
  'canvas.tools': { en: 'Tools', es: 'Herramientas' },
  'canvas.zoomGroup': { en: 'Zoom and fit', es: 'Zoom y encaje' },
  'canvas.zoomIn': { en: 'Zoom in', es: 'Acercar' },
  'canvas.zoomOut': { en: 'Zoom out', es: 'Alejar' },
  'canvas.zoom100': { en: '100 %', es: '100 %' },
  'canvas.fitAll': { en: 'Fit all', es: 'Ver todo' },
  'canvas.fitSelection': { en: 'Fit selection', es: 'Ver selección' },
  'canvas.howTo': { en: 'How to drive the canvas', es: 'Cómo manejar el lienzo' },
  'canvas.pan': { en: 'Drag the background to pan, the wheel to zoom on the cursor, two fingers to pinch. Drag a title bar to move a window, its edges to resize it.', es: 'Arrastra el fondo para desplazar, la rueda hace zoom sobre el cursor, dos dedos para pinzar. Arrastra la barra de título para mover una ventana y sus bordes para redimensionarla.' },
  'canvas.keys': { en: 'Keys: arrows pan · + / − zoom · F fits (selection first) · on a window: arrows move, Shift+arrows resize, Alt+arrows snap, I inspector, Enter enters, Delete removes · ← / → walk the flow · Esc leaves', es: 'Teclas: flechas desplazan · + / − zoom · F encaja (primero la selección) · en una ventana: flechas mueven, Mayús+flechas redimensionan, Alt+flechas ajustan, I inspector, Enter entra, Supr quita · ← / → recorren el flujo · Esc sale' },

  'canvas.preset': { en: 'Lay out', es: 'Disposición' },
  'canvas.presetCustom': { en: 'Arranged by hand', es: 'Colocado a mano' },
  'canvas.presetSurface': { en: 'All pages by surface', es: 'Todas las páginas por superficie' },
  'canvas.presetRole': { en: 'Per role', es: 'Por rol' },
  'canvas.presetPipeline': { en: 'Pipeline walkthrough', es: 'Recorrido del flujo de documentos' },
  'canvas.add': { en: 'Add window', es: 'Añadir ventana' },
  'canvas.remove': { en: 'Remove', es: 'Quitar' },
  'canvas.removed': { en: 'Window removed', es: 'Ventana quitada' },
  'canvas.undo': { en: 'Undo', es: 'Deshacer' },
  'canvas.inspector': { en: 'Window inspector', es: 'Inspector de ventana' },
  'canvas.duplicate': { en: 'Duplicate window', es: 'Duplicar ventana' },
  'canvas.close': { en: 'Close window', es: 'Cerrar ventana' },
  'canvas.bringToFront': { en: 'Bring to front', es: 'Traer al frente' },
  'canvas.focusWindow': { en: 'Zoom to this window', es: 'Acercar a esta ventana' },
  'canvas.windowName': { en: 'Window: {title}', es: 'Ventana: {title}' },
  'canvas.url': { en: 'Address', es: 'Dirección' },
  'canvas.move': { en: 'Move (drag, or the arrow keys)', es: 'Mover (arrastrar o flechas)' },
  'canvas.resize': { en: 'Resize (drag, or Shift + arrow keys)', es: 'Redimensionar (arrastrar o Mayús + flechas)' },
  'canvas.x': { en: 'X', es: 'X' },
  'canvas.y': { en: 'Y', es: 'Y' },
  'canvas.width': { en: 'Width', es: 'Ancho' },
  'canvas.height': { en: 'Height', es: 'Alto' },
  'canvas.device': { en: 'Device', es: 'Dispositivo' },
  'canvas.role': { en: 'Role', es: 'Rol' },
  'canvas.roleNotAllowed': { en: 'this page does not allow that role', es: 'esta página no permite ese rol' },
  'canvas.lang': { en: 'Language', es: 'Idioma' },

  'canvas.findTitle': { en: 'Add a page to the canvas', es: 'Añadir una página al lienzo' },
  'canvas.search': { en: 'Search pages', es: 'Buscar páginas' },
  'canvas.surface': { en: 'Surface', es: 'Superficie' },
  'canvas.allSurfaces': { en: 'All surfaces', es: 'Todas las superficies' },
  'canvas.builtOnly': { en: 'Built only', es: 'Solo construidas' },
  'canvas.empty': { en: 'Nothing on the canvas yet', es: 'Nada en el lienzo todavía' },

  'canvas.layouts': { en: 'Saved layouts', es: 'Disposiciones guardadas' },
  'canvas.noLayout': { en: 'No saved layout', es: 'Sin disposición guardada' },
  'canvas.layoutName': { en: 'Layout name', es: 'Nombre de la disposición' },
  'canvas.save': { en: 'Save layout', es: 'Guardar' },
  'canvas.rename': { en: 'Rename', es: 'Renombrar' },
  'canvas.deleteLayout': { en: 'Delete layout', es: 'Eliminar' },

  'canvas.showFlows': { en: 'Show flows', es: 'Mostrar flujos' },
  'canvas.flowRole': { en: 'Flow of', es: 'Flujo de' },
  'canvas.flowOf': { en: 'What the {role} can do', es: 'Lo que puede hacer el rol {role}' },
  'canvas.focusRoleLabel': { en: 'Focus on this role', es: 'Centrarse en este rol' },
  'canvas.stepThrough': { en: 'Step through', es: 'Recorrer paso a paso' },
  'canvas.step': { en: 'Step {n} of {total}', es: 'Paso {n} de {total}' },
  'canvas.stepBack': { en: 'Back', es: 'Atrás' },
  'canvas.stepNext': { en: 'Next', es: 'Siguiente' },
  'canvas.stepExit': { en: 'Leave the walkthrough', es: 'Salir del recorrido' },
  'canvas.legend': { en: 'KEY — flows', es: 'CLAVE — flujos' },
  'canvas.keyNormal': { en: 'The usual path', es: 'El camino normal' },
  'canvas.keyPositive': { en: 'In the tenant\'s favour', es: 'A favor del inquilino' },
  'canvas.keyNegative': { en: 'Rejected, late or sent back', es: 'Rechazado, atrasado o devuelto' },
  'canvas.keyHandoff': { en: 'Another role takes over', es: 'Otro rol toma el relevo' },
  'canvas.nodeAction': { en: 'Action', es: 'Acción' },
  'canvas.nodeDecision': { en: 'Decision', es: 'Decisión' },
  'canvas.nodeHandoff': { en: 'Hand-off', es: 'Traspaso' },
  'canvas.handoffTo': { en: 'goes to', es: 'pasa a' },
  'canvas.notOnCanvas': { en: 'This page has no window on the canvas yet', es: 'Esta página aún no tiene ventana en el lienzo' },
  'canvas.addWindowShort': { en: 'Add window', es: 'Añadir ventana' },

  'canvas.live': { en: '{n} live of {total}', es: '{n} activas de {total}' },
  'canvas.liveFrames': { en: 'Live windows', es: 'Ventanas activas' },
  'canvas.capOption': { en: '{n} live', es: '{n} activas' },
  'canvas.liveCap': { en: 'Live windows are capped at {cap} so the canvas stays smooth; the rest are wireframe tiles that load when they come into view or when you click them.', es: 'Las ventanas activas se limitan a {cap} para que el lienzo siga fluido; el resto son plantillas que cargan al entrar en vista o al pulsarlas.' },
  'canvas.loadFrame': { en: 'Load this page', es: 'Cargar esta página' },

  'canvas.msgZoom': { en: 'zoom {n} %', es: 'zoom {n} %' },
  'canvas.msgNoSurface': { en: 'the canvas surface is not on screen', es: 'la superficie del lienzo no está en pantalla' },
  'canvas.msgNoPipeline': { en: 'the pipeline walkthrough layout is not in the database yet', es: 'la disposición del recorrido de documentos aún no está en la base de datos' },
  'canvas.msgSaved': { en: 'Layout “{name}” saved', es: 'Disposición «{name}» guardada' },
  'canvas.msgRenamed': { en: 'Layout renamed', es: 'Disposición renombrada' },
  'canvas.msgDeleted': { en: 'Layout deleted', es: 'Disposición eliminada' },
  'canvas.msgAdded': { en: '{code} is on the canvas', es: '{code} está en el lienzo' },
  'canvas.msgEntered': { en: 'the window has the pointer now', es: 'la ventana tiene el puntero ahora' },
  'canvas.msgFlowsOn': { en: 'flow lines on', es: 'líneas de flujo activadas' },
  'canvas.msgFlowsOff': { en: 'flow lines off', es: 'líneas de flujo desactivadas' },
  'canvas.msgNoFlow': { en: 'this role has no flow to walk', es: 'este rol no tiene flujo que recorrer' },
  'canvas.msgFocusRole': { en: 'showing only what the {role} touches', es: 'mostrando solo lo que toca el rol {role}' },
  'canvas.msgNothingToUndo': { en: 'nothing to undo', es: 'nada que deshacer' },

  // simulator
  'sim.title': { en: 'Demo simulator', es: 'Simulador de demostración' },
  'sim.subtitle': { en: 'Present any page on the device it is really used on, as any demo role, in either language. Phone to 4K TV.', es: 'Presenta cualquier página en el dispositivo en el que se usa de verdad, con cualquier rol demo y en los dos idiomas. Del teléfono a la TV 4K.' },
  'sim.device': { en: 'Device', es: 'Dispositivo' },
  'sim.page': { en: 'Page', es: 'Página' },
  'sim.rotate': { en: 'Rotate', es: 'Girar' },
  'sim.portrait': { en: 'Portrait', es: 'Vertical' },
  'sim.landscape': { en: 'Landscape', es: 'Horizontal' },
  'sim.present': { en: 'Present', es: 'Presentar' },
  'sim.exitPresent': { en: 'Exit present mode', es: 'Salir del modo presentación' },
  'sim.tour': { en: 'Tour', es: 'Recorrido' },
  'sim.tourStart': { en: 'Start the tour', es: 'Iniciar el recorrido' },
  'sim.tourStop': { en: 'End the tour', es: 'Terminar el recorrido' },
  'sim.next': { en: 'Next', es: 'Siguiente' },
  'sim.back': { en: 'Back', es: 'Atrás' },
  'sim.step': { en: 'Step {n} of {total}', es: 'Paso {n} de {total}' },
  'sim.screenshot': { en: 'Screenshot', es: 'Captura' },
  'sim.shortcuts': { en: 'P presents · → / ← step the tour · D cycles the device · R rotates · Esc leaves present mode', es: 'P presenta · → / ← avanza el recorrido · D cambia de dispositivo · R gira · Esc sale de la presentación' },
  'sim.gotIt': { en: 'Got it', es: 'Entendido' },
  'sim.share': { en: 'The address bar carries the device, page, role and language, so a link opens the same demo.', es: 'La barra de direcciones lleva dispositivo, página, rol e idioma, así que un enlace abre la misma demostración.' },
  'sim.pin': { en: 'Pin', es: 'Fijar' },
  'sim.auto': { en: 'Auto', es: 'Automático' },
  'sim.autoDevice': { en: 'Auto: {device}', es: 'Automático: {device}' },
  'sim.pinned': { en: 'Pinned: {device}', es: 'Fijado: {device}' },
  'sim.pinHint': { en: 'Pin this device so it stays while you move through pages.', es: 'Fija este dispositivo para que no cambie al pasar de página.' },
  'sim.unpinHint': { en: 'Let the device follow the page again ({device} for this one).', es: 'Deja que el dispositivo siga a la página otra vez ({device} para esta).' },
  'sim.responsiveCheck': { en: 'Responsive check', es: 'Prueba de adaptación' },
  'sim.noRotate': { en: 'Only the phone and the tablet rotate.', es: 'Solo el teléfono y la tableta giran.' },
  'sim.tenFoot': { en: '10-foot view', es: 'Vista a tres metros' },
  'sim.kind.phone': { en: 'phone', es: 'teléfono' },
  'sim.kind.tablet': { en: 'tablet', es: 'tableta' },
  'sim.kind.laptop': { en: 'laptop', es: 'portátil' },
  'sim.kind.monitor': { en: 'desk monitor', es: 'monitor de escritorio' },
  'sim.kind.tv': { en: '4K TV', es: 'TV 4K' },
  'sim.tour.hub': { en: 'The testing hub: every surface, as any demo person', es: 'El centro de pruebas: cada superficie, como cualquier persona demo' },
  'sim.tour.client': { en: 'The tenant opens the app on their phone', es: 'El inquilino abre la app en su teléfono' },
  'sim.tour.owner': { en: 'The owner reads the network on the big panel', es: 'El titular revisa la red en la pantalla grande' },
  'sim.tour.board': { en: 'The eviction game board: where the case stands', es: 'El tablero del desalojo: dónde está el caso' },
  'sim.tour.counsel': { en: 'The attorney works the document pipeline on the desk monitor', es: 'El abogado trabaja el flujo de documentos en el monitor de escritorio' },
  'sim.tour.plan': { en: 'The build plan of CTL OS itself', es: 'El plan de construcción de CTL OS' },
  'sim.tour.proposal': { en: 'The proposal, as the firm will read it on a laptop', es: 'La propuesta, como la leerá el despacho en un portátil' },
  'sim.missing': { en: 'That page is still being built, so the tour shows the nearest one that exists.', es: 'Esa página aún se está construyendo, así que el recorrido muestra la más cercana que existe.' },
};
