/**
 * Placeholder homes so every ROLE_HOME and hub card resolves before the modules ship. The registry prefers a real
 * (non-PageStub) route at the same path, so module agents simply register theirs; nobody edits this file.
 * Every stub declares its planned actions so the manifest (and D-20) already shows the vocabulary.
 */
import { createElement as h } from 'react';
import type { RouteDef } from '../../specs/types';
import { defineSpec } from '../../specs/defineSpec';
import { PageStub } from '../../components/template/PageStub/PageStub';
import { ALL_SIGNED_IN, EVERYONE, STAFF_ROLES } from '../../auth/roles';

export const strings = {};
const stub = (r: Omit<RouteDef, 'element'>): RouteDef => ({ ...r, element: h(PageStub, { spec: r.spec }) });
const CHECKED = [360, 390, 768, 1280, 1920, 2560, 3840];

export const routes: RouteDef[] = [
  stub({ path: '/site', roles: EVERYONE, surface: 'public', layout: 'auto', spec: defineSpec({ code: 'P-01', name: 'Public home', purpose: 'caltenantlaw.com home: "Your cloudy day is about to clear up", eviction help now, free videos first, consultation CTA, offices across California.', layout: ['SiteLayout', 'Hero', 'HelpNow (notice types)', 'FreeVideos', 'HowItWorks (vending machine)', 'Offices', 'CTA'], data: ['tenants'], roles: EVERYONE, logic: ['CTA leads to the consultation funnel (RULE-INTAKE-01).'], integrations: ['YouTube (videos)'], components: ['SiteLayout', 'Button', 'Card', 'Section'], actions: [{ id: 'site.bookConsultation', label: 'Book a consultation', intent: 'start booking a paid attorney consultation' }, { id: 'site.watchVideos', label: 'Watch free videos', intent: 'open the free pre-consultation videos' }], rules: ['RULE-INTAKE-01', 'RULE-NOTICE-01'], states: ['default', 'Spanish'], checkedAt: CHECKED, notes: ['public-site module'] }) }),
  stub({ path: '/app', roles: ['client', 'super_admin'], surface: 'customer', layout: 'mobile', nav: { label: 'Home', icon: 'home', order: 0, group: 'customer' }, spec: defineSpec({ code: 'C-01', name: 'Client home', purpose: 'The tenant sees their case at a glance: where they stand on the board, the next deadline, documents to sign, messages and the hotline.', layout: ['Header', 'CaseCard (board position)', 'NextDeadline', 'DocumentsToSign', 'Messages', 'Hotline'], data: ['users'], roles: ['client'], logic: ['Deadline math in court days (RULE-UD-01).'], integrations: [], components: ['Card', 'Badge', 'BottomNav', 'ProgressBar'], actions: [{ id: 'app.openCase', label: 'My case', intent: 'open my case details' }, { id: 'app.callHotline', label: 'Call the hotline', intent: 'start a paid hotline call' }], rules: ['RULE-UD-01', 'RULE-UD-04'], states: ['no case yet', 'active case', 'Spanish'], checkedAt: CHECKED, notes: ['client-app module'] }) }),
  stub({ path: '/desk', roles: STAFF_ROLES, surface: 'frontdesk', layout: 'desktop', nav: { label: 'Today', icon: 'home', order: 0, group: 'overview' }, spec: defineSpec({ code: 'F-01', name: 'Front desk today', purpose: 'Run the day at one office: intake queue, consultations scheduled, hotline minutes, store orders, payments.', layout: ['PageHeader', 'StatTiles', 'IntakeQueue', 'ConsultationsToday', 'OrdersAndPayments'], data: ['users', 'tenants'], roles: STAFF_ROLES, logic: ['Consultations are prepaid 30-minute blocks (RULE-INTAKE-01).'], integrations: ['Calendar / Teams (later)', 'Payments (later, seam)'], components: ['StatTile', 'DataTable', 'StatusBadge', 'Tabs'], actions: [{ id: 'desk.newIntake', label: 'New intake', intent: 'start a new intake for a caller', permission: 'intake.write' }, { id: 'desk.bookConsultation', label: 'Book consultation', intent: 'book a consultation slot for a client', permission: 'consultations.book', params: { clientId: 'id', date: 'date' } }], rules: ['RULE-INTAKE-01', 'RULE-DEPOSIT-02'], states: ['default', 'empty day'], checkedAt: CHECKED, notes: ['front-desk module'] }) }),
  stub({ path: '/counsel', roles: ['attorney', 'owner', 'super_admin'], surface: 'counsel', layout: 'desktop', nav: { label: 'My cases', icon: 'gavel', order: 0, group: 'cases' }, spec: defineSpec({ code: 'L-01', name: 'Attorney home', purpose: 'The regional attorney sees their active cases, hearings this week, filings due and messages from clients and opposing counsel.', layout: ['PageHeader', 'StatTiles', 'HearingsThisWeek', 'FilingsDue', 'CasesTable'], data: ['users'], roles: ['attorney', 'owner'], logic: ['Trial within 20 days of the answer (RULE-UD-02); discovery cut-off (RULE-UD-03).'], integrations: ['Court e-filing (later)'], components: ['StatTile', 'DataTable', 'StatusBadge', 'Card'], actions: [{ id: 'counsel.openCase', label: 'Open case', intent: 'open a case by id', params: { caseId: 'id' } }, { id: 'counsel.fileDocument', label: 'File', intent: 'file a document on a case', permission: 'documents.sign', params: { caseId: 'id' } }], rules: ['RULE-UD-02', 'RULE-UD-03', 'RULE-UD-05'], states: ['default'], checkedAt: CHECKED, notes: ['attorneys module'] }) }),
  stub({ path: '/assist', roles: ['paralegal', 'attorney', 'owner', 'super_admin'], surface: 'assist', layout: 'desktop', nav: { label: 'Queue', icon: 'list', order: 0, group: 'overview' }, spec: defineSpec({ code: 'S-01', name: 'Assistant queue', purpose: 'Paralegals work the drafting queue: answers, motions, discovery and kits, with deadlines and checklists.', layout: ['PageHeader', 'DeadlinesStrip', 'DraftQueue', 'Checklists'], data: ['users'], roles: ['paralegal', 'attorney'], logic: ['Queue sorted by court-day deadline.'], integrations: ['Document assembly (later)'], components: ['DataTable', 'Stepper', 'Badge', 'Card'], actions: [{ id: 'assist.startDraft', label: 'Start draft', intent: 'start drafting a document for a case', permission: 'documents.write', params: { caseId: 'id', kind: 'string' } }], rules: ['RULE-UD-01', 'RULE-UD-03'], states: ['default', 'empty'], checkedAt: CHECKED, notes: ['assistants module'] }) }),
  stub({ path: '/owner', roles: ['owner', 'super_admin'], surface: 'owner', layout: 'desktop', nav: { label: 'Network', icon: 'chart', order: 0, group: 'overview' }, spec: defineSpec({ code: 'O-01', name: 'Owner dashboard', purpose: 'The principal sees the whole network: consultations, revenue, cases by office, feedback inbox and decisions awaiting them.', layout: ['PageHeader', 'StatTiles', 'OfficesCompare', 'FeedbackInbox', 'AwaitingDecisions'], data: ['tenants', 'feedback'], roles: ['owner'], logic: ['Sum per tenant and period.'], integrations: [], components: ['StatTile', 'DataTable', 'Card', 'Tabs'], actions: [{ id: 'owner.triageFeedback', label: 'Triage', intent: 'record a triage decision on a feedback row', permission: 'feedback.triage', params: { id: 'id', triage: 'enum:fix,ask,wontfix' } }], rules: ['RULE-SYS-02'], states: ['default'], checkedAt: CHECKED, notes: ['owner module'] }) }),
  stub({ path: '/admin', roles: ['owner', 'super_admin'], surface: 'admin', layout: 'desktop', nav: { label: 'Settings', icon: 'settings', order: 0, group: 'settings' }, spec: defineSpec({ code: 'A-01', name: 'Admin home', purpose: 'Users, roles and permissions, offices (tenants), rules, settings and the feedback triage board.', layout: ['PageHeader', 'SettingsGrid (users, roles, tenants, rules, feedback)'], data: ['users', 'tenants', 'feedback'], roles: ['owner', 'super_admin'], logic: ['Permissions derive from role (ROLE_PERMISSIONS).'], integrations: ['Supabase Auth (later)'], components: ['Card', 'DataTable', 'RoleSwitcher'], actions: [{ id: 'admin.inviteUser', label: 'Invite user', intent: 'invite a person to an office with a role', permission: 'staff.write', params: { email: 'string', role: 'string', tenantId: 'id' } }], rules: ['RULE-SYS-02'], states: ['default'], checkedAt: CHECKED, notes: ['admin module'] }) }),
  stub({ path: '/opposition', roles: ['opposing_counsel', 'attorney', 'super_admin'], surface: 'opposition', layout: 'desktop', nav: { label: 'Shared case', icon: 'scale', order: 0, group: 'opposition' }, spec: defineSpec({ code: 'X-01', name: 'Opposing counsel portal', purpose: 'The landlord-side attorney sees one case: shared documents, proposed dates, messages; nothing else in the system.', layout: ['PageHeader', 'CaseSummary', 'SharedDocuments', 'Messages'], data: ['users'], roles: ['opposing_counsel'], logic: ['Rows visible only where shared_with includes the counsel (RLS intent).'], integrations: [], components: ['Card', 'DataTable', 'Badge'], actions: [{ id: 'opposition.sendMessage', label: 'Send message', intent: 'send a message on the shared case', permission: 'messages.write', params: { text: 'string' } }], rules: ['RULE-UD-02'], states: ['default', 'nothing shared'], checkedAt: CHECKED, notes: ['opposition module'] }) }),
  stub({ path: '/board', roles: EVERYONE, surface: 'board', layout: 'auto', nav: { label: 'Game board', icon: 'gamepad', order: 0, group: 'board' }, spec: defineSpec({ code: 'GB-01', name: 'Eviction game board', purpose: 'The unlawful-detainer flow as a board: squares from the notice to the sheriff, the moves a tenant has at each one, the time each move buys, and the position of a case.', layout: ['BoardHeader', 'Board (squares, paths)', 'MoveCards', 'Legend (positive, negative, neutral, jump, document, hearing)'], data: ['users'], roles: EVERYONE, logic: ['Square colours from boardHues; deadlines from rules RULE-UD-*.'], integrations: [], components: ['Card', 'Badge', 'Tooltip', 'Stepper'], actions: [{ id: 'board.selectSquare', label: 'Select square', intent: 'show the moves available at a board square', params: { square: 'string' } }, { id: 'board.placeCase', label: 'Place my case', intent: 'place my case on the board at its current stage', permission: 'board.play' }], rules: ['RULE-UD-01', 'RULE-UD-02', 'RULE-UD-04', 'RULE-UD-05', 'RULE-NOTICE-01'], states: ['browse', 'case placed', 'keyboard navigation'], checkedAt: CHECKED, notes: ['game-board module'] }) }),
  stub({ path: '/plan', roles: ['owner', 'super_admin', 'attorney', 'paralegal', 'marketing'], surface: 'plan', layout: 'desktop', nav: { label: 'Kanban', icon: 'kanban', order: 0, group: 'plan' }, spec: defineSpec({ code: 'PM-01', name: 'Project board', purpose: 'Kanban, decisions, changelog and build plan of CTL OS itself, read from docs/ at build time.', layout: ['PageHeader', 'Tabs (kanban, decisions, changelog, plan)', 'Board or MarkdownViewer'], data: ['page_layouts'], roles: ['owner', 'super_admin'], logic: ['docsIndex globs docs/**/*.md.'], integrations: [], components: ['Tabs', 'MarkdownViewer', 'Card'], actions: [{ id: 'plan.openDoc', label: 'Open', intent: 'open a docs file by path', params: { path: 'string' } }], rules: ['RULE-SYS-01'], states: ['kanban', 'decisions'], checkedAt: CHECKED, notes: ['project-management module'] }) }),
  stub({ path: '/manual', roles: ALL_SIGNED_IN, surface: 'manual', layout: 'desktop', nav: { label: 'Manual home', icon: 'book', order: 0, group: 'manual' }, spec: defineSpec({ code: 'M-01', name: 'Ops manual cover', purpose: 'How the firm runs, per role, with live numbers from the system; Spanish first, English mirror.', layout: ['Cover', 'RoleMatrix', 'ChapterGrid'], data: ['tenants'], roles: ALL_SIGNED_IN, logic: ['Chapters from docs/ops-manual/{es,en}/*.md at build time; {{directives}} render live values.'], integrations: [], components: ['Card', 'MarkdownViewer'], actions: [{ id: 'manual.openChapter', label: 'Open chapter', intent: 'open a manual chapter by slug', params: { slug: 'string' } }], rules: ['RULE-SYS-01'], states: ['cover', 'chapter'], checkedAt: CHECKED, notes: ['ops-manual module'] }) }),
  stub({ path: '/docs', roles: ['super_admin', 'owner', 'attorney', 'paralegal', 'marketing'], surface: 'docs', layout: 'desktop', nav: { label: 'Docs', icon: 'layers', order: 0, group: 'docs' }, spec: defineSpec({ code: 'K-01', name: 'Docs viewer', purpose: 'Every markdown file under docs/ rendered in-app with a tree, search and screenshot galleries; the project memory and the legal digests.', layout: ['DocsSidebar', 'Document (MarkdownViewer)', 'Gallery'], data: ['page_layouts'], roles: ['super_admin', 'owner'], logic: ['src/docs/docsIndex.ts: ?docmeta eager index + ?raw bodies on demand.'], integrations: [], components: ['MarkdownViewer', 'Sidebar', 'SearchInput'], actions: [{ id: 'docs.open', label: 'Open doc', intent: 'open a docs file by path', params: { path: 'string' } }, { id: 'docs.search', label: 'Search docs', intent: 'search every doc for a phrase', params: { q: 'string' } }], rules: ['RULE-SYS-01'], states: ['index', 'document'], checkedAt: CHECKED, notes: ['docs module (D-06 equivalent)'] }) }),
  stub({ path: '/marketing', roles: ['marketing', 'owner', 'super_admin'], surface: 'marketing', layout: 'desktop', nav: { label: 'Marketing', icon: 'megaphone', order: 0, group: 'marketing' }, spec: defineSpec({ code: 'MK-01', name: 'Marketing engine', purpose: 'City landing pages, video library, campaigns and the content calendar that feed the public site.', layout: ['PageHeader', 'StatTiles', 'CityPages', 'VideoLibrary', 'Calendar'], data: ['tenants'], roles: ['marketing', 'owner'], logic: ['A city page is a row rendered by the public site.'], integrations: ['YouTube', 'Search console (later)'], components: ['StatTile', 'DataTable', 'Card'], actions: [{ id: 'marketing.newCityPage', label: 'New city page', intent: 'create a landing page for a city', permission: 'marketing.write', params: { city: 'string' } }, { id: 'marketing.publish', label: 'Publish', intent: 'publish pending site changes', permission: 'site.publish' }], rules: ['RULE-INTAKE-01'], states: ['default'], checkedAt: CHECKED, notes: ['marketing module'] }) }),
];
