import type { StringTable } from '../../i18n/types';

/**
 * Board module strings. The node labels themselves stay in the poster's English (they are quotations from
 * © 2021 Ken Carlson and terms of art); a later Spanish pass adds an `es` label per square in nodes.json
 * (see docs/pages/GB-01.md "Real vs mock"). Everything the app itself says is bilingual here.
 */
export const strings: StringTable = {
  'board.nav.explore': { en: 'Game board', es: 'Tablero del juego' },
  'board.nav.case': { en: 'Where am I', es: '¿Dónde estoy?' },
  'board.nav.overlay': { en: 'Costs & if-then', es: 'Costos y si-entonces' },

  'board.title': { en: 'Unlawful Detainer game board', es: 'Tablero del juicio de desalojo' },
  'board.eyebrow': { en: 'Take the "awful" out of Unlawful Detainer · any number can play', es: 'Quítale lo "terrible" al desalojo · pueden jugar todos' },
  'board.subtitle': { en: 'Every square of the eviction process, the paths between them and what each move means. Pick a phase, search for a square, or open one to read what happens next.', es: 'Cada casilla del proceso de desalojo, los caminos entre ellas y lo que significa cada movimiento. Elige una fase, busca una casilla o abre una para leer qué sigue.' },
  'board.credit': { en: 'Board © 2021 Ken Carlson · caltenantlaw.com. Squares are quoted from the poster; the paths were reconstructed from its layout and the firm still has to confirm {n} of them.', es: 'Tablero © 2021 Ken Carlson · caltenantlaw.com. Las casillas son citas del póster; los caminos se reconstruyeron de su diseño y el despacho aún debe confirmar {n} de ellos.' },
  'board.counts': { en: '{phases} phases · {nodes} squares · {edges} paths', es: '{phases} fases · {nodes} casillas · {edges} caminos' },

  'board.search.label': { en: 'Search the board', es: 'Buscar en el tablero' },
  'board.search.placeholder': { en: 'Search a square (demurrer, stay, lockout…)', es: 'Busca una casilla (demurrer, suspensión, desalojo…)' },
  'board.search.results': { en: '{n} squares match', es: '{n} casillas coinciden' },
  'board.search.none': { en: 'No square matches that. Try "quash", "default", "appeal".', es: 'Ninguna casilla coincide. Prueba "quash", "default", "appeal".' },
  'board.phases': { en: 'Phases', es: 'Fases' },
  'board.wholeBoard': { en: 'Whole board', es: 'Todo el tablero' },
  'board.legend': { en: 'KEY', es: 'CLAVE' },
  'board.legend.paths': { en: 'KEY — paths', es: 'CLAVE — caminos' },
  'board.legend.shapes': { en: 'KEY — squares', es: 'CLAVE — casillas' },
  'board.legend.hint': { en: 'Switch a path type off to read the board without it.', es: 'Apaga un tipo de camino para leer el tablero sin él.' },

  'board.path.normal': { en: 'Normal path', es: 'Camino normal' },
  'board.path.positive': { en: 'Positive path', es: 'Camino positivo' },
  'board.path.negative': { en: 'Negative path', es: 'Camino negativo' },
  'board.path.neutral': { en: 'Neutral path', es: 'Camino neutral' },
  'board.path.jump': { en: 'Jump path', es: 'Salto' },

  'board.kind.start': { en: 'Start', es: 'Inicio' },
  'board.kind.document': { en: 'Document / filing', es: 'Documento / escrito' },
  'board.kind.hearing': { en: 'Hearing or decision', es: 'Audiencia o decisión' },
  'board.kind.outcome': { en: 'Outcome (the board ends here)', es: 'Resultado (el tablero termina aquí)' },
  'board.kind.event': { en: 'Event', es: 'Evento' },

  'board.actor.tenant': { en: 'You (tenant side)', es: 'Tú (lado del inquilino)' },
  'board.actor.landlord': { en: 'Landlord', es: 'Arrendador' },
  'board.actor.court': { en: 'Court / sheriff', es: 'Tribunal / alguacil' },
  'board.actor.both': { en: 'Both sides', es: 'Ambas partes' },

  'board.detail.phase': { en: 'Phase', es: 'Fase' },
  'board.detail.kind': { en: 'Square', es: 'Casilla' },
  'board.detail.actor': { en: 'Who moves', es: 'Quién mueve' },
  'board.detail.meaning': { en: 'What this means', es: 'Qué significa' },
  'board.detail.noMeaning': { en: 'The poster gives no note for this square; the label is the whole of it.', es: 'El póster no trae nota para esta casilla; la etiqueta es todo.' },
  'board.detail.documents': { en: 'Documents', es: 'Documentos' },
  'board.detail.documentsNone': { en: 'Templates for this square come in Pass 2', es: 'Las plantillas de esta casilla llegan en la Pasada 2' },
  'board.detail.next': { en: 'Possible next moves', es: 'Movimientos posibles' },
  'board.detail.nextNone': { en: 'Nothing follows: the board ends on this square.', es: 'No sigue nada: el tablero termina en esta casilla.' },
  'board.detail.from': { en: 'How you get here', es: 'Cómo se llega aquí' },
  'board.detail.cost': { en: 'Typical cost', es: 'Costo típico' },
  'board.detail.deadline': { en: 'Deadline rule', es: 'Regla de plazo' },
  'board.detail.reconstructed': { en: 'Reconstructed path — the arrow was ambiguous on the poster and the firm still has to confirm it.', es: 'Camino reconstruido: la flecha era ambigua en el póster y el despacho debe confirmarlo.' },
  'board.detail.open': { en: 'Open this square', es: 'Abrir esta casilla' },
  'board.detail.close': { en: 'Close', es: 'Cerrar' },

  'board.overlay.label': { en: 'Overlay', es: 'Capa' },
  'board.overlay.none': { en: 'None', es: 'Ninguna' },
  'board.overlay.cost': { en: 'Cost', es: 'Costo' },
  'board.overlay.deadline': { en: 'Deadline', es: 'Plazo' },
  'board.overlay.costBadge': { en: 'cost ?', es: 'costo ?' },
  'board.overlay.deadlineBadge': { en: 'deadline ?', es: 'plazo ?' },
  'board.overlay.costNotWired': { en: 'typical cost band for this square', es: 'banda de costo típica de esta casilla' },
  'board.overlay.deadlineNotWired': { en: 'deadline rule for this square', es: 'regla de plazo de esta casilla' },
  'board.overlay.filled': { en: '{cost} of {total} squares have a cost band · {deadline} have a deadline rule (board_node_meta).', es: '{cost} de {total} casillas tienen banda de costo · {deadline} tienen regla de plazo (board_node_meta).' },
  'board.overlay.subtitle': { en: 'What each move costs and what it triggers. The scenarios are real, the cost bands are the ones the store already prices, and every square without one \u2014 and every deadline \u2014 stays a marked placeholder.', es: 'Lo que cuesta cada movimiento y lo que desencadena. Los escenarios son reales, las bandas de costo son las que la tienda ya cotiza, y cada casilla sin banda \u2014 y todo plazo \u2014 sigue siendo un marcador se\u00f1alado.' },
  'board.overlay.explainTitle': { en: 'Why some badges are empty', es: 'Por qué algunas etiquetas están vacías' },
  'board.overlay.explain': { en: 'Every square carries a cost band and a deadline rule. The cost band is filled only where the services catalog already prices that step from a store SKU; the rest, and every deadline rule, are empty on purpose. Pass 2 fills the cost from the store SKUs and the cost model, and the deadline from the deadline engine, which must cite a statute row in the legal memory. A guessed number here would be unverified law and a wrong price, so the board shows a marked placeholder instead.', es: 'Cada casilla lleva una banda de costo y una regla de plazo. La banda de costo solo está llena donde el catálogo de servicios ya cotiza ese paso con un SKU de la tienda; el resto, y toda regla de plazo, están vacíos a propósito. La Pasada 2 llena el costo desde los SKU de la tienda y el modelo de costos, y el plazo desde el motor de plazos, que debe citar una norma en la memoria legal. Un número inventado aquí sería derecho sin verificar y un precio equivocado, así que el tablero muestra un marcador señalado.' },

  'board.ifthen.title': { en: 'If this, then that', es: 'Si esto, entonces aquello' },
  'board.ifthen.subtitle': { en: 'Branches from {label}, read from the board itself. The scenarios are real; only the money is not filled in yet.', es: 'Ramas desde {label}, leídas del propio tablero. Los escenarios son reales; solo el dinero falta.' },
  'board.ifthen.pick': { en: 'Open a square on the board to see its branches.', es: 'Abre una casilla del tablero para ver sus ramas.' },
  'board.ifthen.if': { en: 'If', es: 'Si' },
  'board.ifthen.then': { en: 'then', es: 'entonces' },
  'board.ifthen.andThen': { en: 'and from there', es: 'y desde ahí' },
  'board.ifthen.terminal': { en: 'the board ends here', es: 'el tablero termina aquí' },
  'board.ifthen.costCol': { en: 'Cost', es: 'Costo' },
  'board.ifthen.scenarios': { en: '{n} scenarios', es: '{n} escenarios' },

  'board.case.title': { en: 'Where am I on the board', es: '¿Dónde estoy en el tablero?' },
  'board.case.subtitle': { en: 'One case at a time: the squares it has passed, the square it stands on, and every move it can legally make next.', es: 'Un caso a la vez: las casillas recorridas, la casilla actual y cada movimiento posible.' },
  'board.case.selector': { en: 'Demo case', es: 'Caso demo' },
  'board.case.none': { en: 'No demo case has a board position yet.', es: 'Ningún caso demo tiene posición en el tablero.' },
  'board.case.missing': { en: 'That case is not on the board yet.', es: 'Ese caso todavía no está en el tablero.' },
  'board.case.missingBody': { en: 'No board_positions row points at this case id. Open one of the cases that has a position.', es: 'Ninguna fila de board_positions apunta a este id de caso. Abre uno de los casos que sí tiene posición.' },
  'board.case.hereTitle': { en: 'You are here', es: 'Estás aquí' },
  'board.case.nextTitle': { en: 'What happens next', es: 'Qué sigue' },
  'board.case.since': { en: 'On this square since {date}', es: 'En esta casilla desde {date}' },
  'board.case.visitedCount': { en: '{n} squares behind you', es: '{n} casillas recorridas' },
  'board.case.move': { en: 'Move here', es: 'Mover aquí' },
  'board.case.moved': { en: 'Moved to {label}', es: 'Movido a {label}' },
  'board.case.moveNeedsPermission': { en: 'Signed-in staff move a case on the board; you are reading it as a visitor.', es: 'El personal mueve el caso en el tablero; lo estás viendo como visitante.' },
  'board.case.history': { en: 'Moves so far', es: 'Movimientos hasta ahora' },
  'board.case.terminal': { en: 'This square is where the board ends. Nothing follows it.', es: 'Esta casilla es donde termina el tablero. No sigue nada.' },
  'board.case.demoNote': { en: 'Fictional demo cases. Real positions arrive with the cases module (T-055).', es: 'Casos demo ficticios. Las posiciones reales llegan con el módulo de casos (T-055).' },

  'board.board.surface': { en: 'Unlawful Detainer game board', es: 'Tablero del juicio de desalojo' },
  'board.board.zoomIn': { en: 'Zoom in', es: 'Acercar' },
  'board.board.zoomOut': { en: 'Zoom out', es: 'Alejar' },
  'board.board.fitBoard': { en: 'Fit the whole board', es: 'Ajustar todo el tablero' },
  'board.board.fitPhase': { en: 'Fit this phase', es: 'Ajustar esta fase' },
  'board.board.reset': { en: 'Reset the view', es: 'Restablecer la vista' },
  'board.board.panUp': { en: 'Pan up', es: 'Mover arriba' },
  'board.board.panDown': { en: 'Pan down', es: 'Mover abajo' },
  'board.board.panLeft': { en: 'Pan left', es: 'Mover a la izquierda' },
  'board.board.panRight': { en: 'Pan right', es: 'Mover a la derecha' },
  'board.board.zoom': { en: 'Zoom', es: 'Zoom' },
  'board.board.hint': { en: 'Drag or use the arrow buttons to pan; Ctrl + wheel zooms.', es: 'Arrastra o usa las flechas para mover; Ctrl + rueda hace zoom.' },
  'board.board.hintKeys': { en: 'Arrows pan · + / − zoom · 0 fits the board · F fits the phase', es: 'Flechas mueven · + / − zoom · 0 ajusta el tablero · F ajusta la fase' },
  'board.board.youAreHere': { en: 'YOU ARE HERE', es: 'ESTÁS AQUÍ' },
  'board.board.visited': { en: 'visited', es: 'recorrida' },
  'board.board.next': { en: 'possible next move', es: 'movimiento posible' },
  'board.board.current': { en: 'current square', es: 'casilla actual' },
};
