import { defineSpec } from '../../specs/defineSpec';
import type { Role } from '../../auth/roles';
import { CHECKED } from '../_homes/lib';

/** Who runs the desk (D-048): the front desk itself, plus owner and super admin who oversee every office. Attorneys, paralegals and marketing have their own homes. */
export const DESK_ROLES: Role[] = ['front_desk', 'owner', 'super_admin'];

export const deskHomeSpec = defineSpec({
  code: 'F-01', name: 'Front desk today', purpose: 'One screen to run the day at an office (and on the wall screen for the whole network): what is ringing, what was missed, the callbacks due, the orders waiting on a client, the things clients still owe us, the due dates this week, the consultations booked and the intake queue - plus a lookup box that answers "where is my order?" before the caller finishes the sentence.',
  layout: ['PageHeader', 'Order status lookup (search -> F-14)', 'StatTiles (calls ringing, missed today, callbacks due, waiting on client, needed from clients, due this week, consultations today, intake queue)', 'ConsultationsToday (timeline)', 'ConsultationsThisWeek', 'CallsToReturn (missed / voicemail -> F-12)', 'FollowUpsDue (-> F-15)', 'IntakeQueue (review / schedule)', 'PaymentsPending', 'QuickActions'],
  data: ['calls', 'follow_ups', 'client_requests', 'orders', 'consultations', 'intakes', 'invoices', 'users', 'tenants', 'cases'], roles: DESK_ROLES,
  logic: ['Rows are scoped to the signed-in office; owner and super admin see every office (P-02).', 'Today = the consultation’s scheduled_at falls on today; "this week" = the next seven days.', 'Live calls = status ringing / active / on_hold; "missed today" counts missed and voicemail rows started today.', 'Callbacks due = open follow-ups whose due date is today or earlier (lib.isDueNow).', 'Waiting on client = open orders whose waiting_on is client (RULE-PIPE-02); needed from clients = open client_requests.', 'Due dates this week = orders whose filing_due_at or due_at falls in the next seven days.', 'Reviewing an intake writes status = reviewed through the provider; scheduling waits for the scheduling pass.', 'Marking a consultation held writes status = held.', 'The lookup box navigates to /desk/orders?q=<text>; it never moves a stage (RULE-PIPE-06).', 'Consultations are prepaid, time-boxed 30-minute blocks (RULE-INTAKE-01); hotline blocks are $60 per 10 minutes as listed.'],
  integrations: ['Microsoft Teams / phone (consultation channel)', 'VoiceStamps hotline (later)', 'Scheduler (later)', 'Stripe / PayPal (seam)'],
  components: ['PageHeader', 'StatTile', 'Section', 'Card', 'DataTable', 'SearchInput', 'StatusBadge', 'Badge', 'Chip', 'Button', 'WaitingOnPill', 'EmptyState', 'Placeholder', 'Tooltip', 'Avatar'],
  actions: [
    { id: 'desk.lookupOrder', label: 'Order status lookup', intent: 'look up the status of an order for a caller', permission: 'orders.read', params: { q: 'string' } },
    { id: 'desk.openCalls', label: 'Open the call console', intent: 'open the call console', permission: 'calls.read' },
    { id: 'desk.openFollowUps', label: 'Open follow-ups', intent: 'open the follow-up list', permission: 'followups.read' },
    { id: 'desk.reviewIntake', label: 'Review', intent: 'mark an intake as reviewed', permission: 'intake.write', params: { id: 'id' } },
    { id: 'desk.scheduleIntake', label: 'Schedule', intent: 'book a consultation for someone in the intake queue', permission: 'consultations.book', params: { id: 'id' } },
    { id: 'desk.markConsultationHeld', label: 'Mark as held', intent: 'mark a consultation as held', permission: 'consultations.write', params: { id: 'id' } },
    { id: 'desk.newIntake', label: 'New intake', intent: 'start a new intake for a caller', permission: 'intake.write' },
    { id: 'desk.bookConsultation', label: 'Book a consultation', intent: 'book a consultation slot for a client', permission: 'consultations.book', params: { clientId: 'id', date: 'date' } },
    { id: 'desk.openCallLog', label: 'Open the call log', intent: 'open the call log with hotline minutes', permission: 'calls.read' },
    { id: 'desk.recordPayment', label: 'Record payment', intent: 'record a payment against an item on a case', permission: 'payments.write', params: { id: 'id' } },
  ],
  rules: ['RULE-INTAKE-01', 'RULE-SYS-02', 'RULE-PIPE-02', 'RULE-PIPE-06'], states: ['busy day', 'empty day', 'call ringing', 'one office', 'whole network', 'Spanish', 'dark', 'wall screen at 3840'],
  checkedAt: CHECKED,
  notes: ['front-desk module (T-041, refreshed for prompt 0006 pass 2 wave A). Tiles read the real pipeline tables and link to F-12, F-14 and F-15.', 'Scheduling, new intake, booking and recording a payment are Placeholders with plannedIn (T-063, T-064, payments seam).'],
});

export const callConsoleSpec = defineSpec({
  code: 'F-12', name: 'Call console', purpose: 'The screen the front desk lives on while the phone rings: the queue on the left with one big Answer button, the call being handled in the centre (who is calling, every order they have with whose turn it is, a script to read aloud and a five-point checklist for the call), and today\'s calls and callbacks on the right. Answers Justin\'s ask in prompt 0006: the desk knows the status of any order the moment the customer calls in.',
  layout: ['PageHeader', 'Counter strip (ringing, missed today, callbacks due, average handle time)', 'Queue (ringing / active / on hold + Simulate incoming call)', 'Active call: CallCard (matched caller or unknown caller with search)', 'Caller orders with Read status script', 'Call checklist (right hands, waiting on the client, due dates, payment, consult)', 'Wrap-up (purpose, notes, outcome)', 'Call controls (Answer / Hold / Resume / End / Voicemail / hotline minutes)', 'Recent: today\'s calls and callbacks due (DataTable)'],
  data: ['calls', 'orders', 'order_stage_events', 'client_requests', 'follow_ups', 'users', 'tenants'], roles: DESK_ROLES,
  logic: [
    'A call is matched to a user by the last ten digits of the number (lib.matchByPhone); an unmatched number is an unknown caller, which the desk can search and link by hand.',
    'The caller\'s orders come from orders.client_user_id (matched_order_ids is the ring-time snapshot); each row shows the client-facing stage (clientStageFor), the waiting-on pill (waitingOnFor + daysWaiting + isLate) and the next due date.',
    '"Read status" expands the three lines the desk reads aloud: what it is, who has it, what is next and by when (lib.phoneScript, the pipeline module\'s wording).',
    'Checklist item 1 shows the assigned attorney and paralegal; "Flag for reassignment" writes a check_in follow_up owned by the attorney - the desk never moves a stage (RULE-PIPE-06).',
    'Checklist item 2 lists the open client_requests with days waiting; "Remind and note" writes a client_item_due / client_review_due follow_up due tomorrow.',
    'Checklist item 3 lists filing_due_at / due_at within 14 days; items 4 and 5 (payment, consult) are Placeholders.',
    'Purpose, notes and outcome autosave to the call row by id (debounced 600 ms); the notes textarea never holds state the provider does not have (P-14).',
    'Answer / Hold / Resume set status; End writes status ended, ended_at and duration_seconds from started_at, then offers "Create follow-up"; Send to voicemail writes status voicemail.',
    '"Log hotline minutes" writes hotline_minutes_billed (VoiceStamps blocks are billed in tens of minutes as listed; the number is recorded, never charged here).',
    '"Simulate incoming call" inserts a ringing inbound call from a seeded client phone, and from an unknown number one time in four, so the console can be demonstrated without telephony.',
    '"Call back" on a missed or voicemail row inserts an outbound active call to the same number and selects it.',
    'The selected call is in the URL (?call=<id>), so a voice controller or a second screen can address it (P-06).',
  ],
  integrations: ['Telephony / softphone (Pass 3 seam: real ringing, answer, hold, transfer)', 'VoiceStamps hotline minutes', 'SMS and email reminders (Pass 3 comms seam)', 'Scheduler (T-064)'],
  components: ['PageHeader', 'StatTile', 'Section', 'Card', 'CallCard', 'WaitingOnPill', 'DataTable', 'SearchInput', 'Select', 'Textarea', 'Input', 'Button', 'Chip', 'Badge', 'StatusBadge', 'EmptyState', 'Placeholder', 'Tooltip', 'Avatar'],
  actions: [
    { id: 'desk.selectCall', label: 'Open call', intent: 'open a call in the console', permission: 'calls.read', params: { id: 'id' } },
    { id: 'desk.simulateCall', label: 'Simulate incoming call', intent: 'simulate an incoming call for a demo', permission: 'calls.write' },
    { id: 'desk.answerCall', label: 'Answer', intent: 'answer the ringing call', permission: 'calls.write', params: { id: 'id' } },
    { id: 'desk.holdCall', label: 'Hold', intent: 'put the call on hold', permission: 'calls.write', params: { id: 'id' } },
    { id: 'desk.resumeCall', label: 'Resume', intent: 'take the call off hold', permission: 'calls.write', params: { id: 'id' } },
    { id: 'desk.endCall', label: 'End call', intent: 'end the call and log how long it lasted', permission: 'calls.write', params: { id: 'id' } },
    { id: 'desk.sendToVoicemail', label: 'Send to voicemail', intent: 'send the ringing call to voicemail', permission: 'calls.write', params: { id: 'id' } },
    { id: 'desk.callBack', label: 'Call back', intent: 'call a missed caller back', permission: 'calls.write', params: { id: 'id' } },
    { id: 'desk.setCallPurpose', label: 'Purpose', intent: 'set why the person called', permission: 'calls.write', params: { id: 'id', purpose: 'enum:status|new_consult|payment|documents|scheduling|other' } },
    { id: 'desk.saveCallNotes', label: 'Notes', intent: 'save the notes taken during the call', permission: 'calls.write', params: { id: 'id', notes: 'string' } },
    { id: 'desk.setCallOutcome', label: 'Outcome', intent: 'record what was decided on the call', permission: 'calls.write', params: { id: 'id', outcome: 'string' } },
    { id: 'desk.logHotlineMinutes', label: 'Log hotline minutes', intent: 'log hotline minutes billed on this call', permission: 'calls.write', params: { id: 'id', minutes: 'number' } },
    { id: 'desk.linkCaller', label: 'Link caller', intent: 'link an unknown caller to a client record', permission: 'calls.write', params: { id: 'id', userId: 'id' } },
    { id: 'desk.readOrderStatus', label: 'Read status', intent: 'read the status of an order aloud to the caller', permission: 'orders.read', params: { id: 'id' } },
    { id: 'desk.flagForReassignment', label: 'Flag for reassignment', intent: 'flag an order as being in the wrong hands', permission: 'followups.write', params: { id: 'id' } },
    { id: 'desk.remindClientRequest', label: 'Remind and note', intent: 'remind the client about something we need and note it', permission: 'followups.write', params: { id: 'id' } },
    { id: 'desk.createFollowUpFromCall', label: 'Create follow-up', intent: 'create a follow-up from this call', permission: 'followups.write', params: { id: 'id' } },
    { id: 'desk.startIntakeForCaller', label: 'Start intake', intent: 'start an intake for an unknown caller', permission: 'intake.write', params: { id: 'id' } },
    { id: 'desk.scheduleConsultFromCall', label: 'Schedule a consult', intent: 'schedule a consultation for the caller', permission: 'consultations.book', params: { id: 'id' } },
    { id: 'desk.takeCallPayment', label: 'Take payment', intent: 'take a payment over the phone', permission: 'payments.write', params: { id: 'id' } },
  ],
  rules: ['RULE-PIPE-02', 'RULE-PIPE-03', 'RULE-PIPE-06', 'RULE-SYS-02'],
  states: ['a call ringing', 'a call in progress', 'on hold', 'unknown caller', 'caller with no orders', 'nothing ringing (quiet desk)', 'call just ended (create follow-up)', 'Spanish', 'dark', 'phone at 360', 'wall screen at 3840'],
  checkedAt: CHECKED,
  notes: ['Pass 2 wave A (prompt 0006, D-049). Real telephony, SMS and email are Pass 3 seams; "Simulate incoming call" stands in for a ring so the console is demonstrable today.', 'Payment on a call is a Placeholder (payments seam); scheduling a consult is a Placeholder with plannedIn T-064; "Start intake" is a Placeholder with plannedIn T-063 until /desk/intake ships in wave B.', 'The desk never advances a pipeline stage (RULE-PIPE-06): everything it can do here is a call row, a follow-up or a note.'],
});

export const followUpsSpec = defineSpec({
  code: 'F-15', name: 'Follow-ups', purpose: 'Everything the desk owes somebody, with a date on it: the follow-ups grouped overdue / today / this week / later, the things clients still have not sent us, and the filing and delivery dates landing in the next fortnight. Justin, prompt 0006: "following up on due dates or things needed from the client".',
  layout: ['PageHeader', 'Counter strip (overdue, today, this week, needed from clients)', 'Tabs (Follow-ups | Needed from clients | Due dates)', 'View toggle (board | list)', 'Board columns or grouped list with Done / Snooze / Cancel', 'Needed from clients grouped by client (Nudge, Call now, Mark received)', 'Due dates table (filing and delivery dates, next 14 days)'],
  data: ['follow_ups', 'client_requests', 'orders', 'users', 'tenants'], roles: DESK_ROLES,
  logic: [
    'Buckets: overdue (due before today), today, this week (next 7 days), later (lib.followUpBucket); rows are scoped to the office (P-02).',
    'Done writes status = done and done_at; Snooze writes a new due_at at 9 am in 1, 3 or 7 days and status = snoozed; Cancel writes status = cancelled. All by id (P-14).',
    'Every row links to the order through the desk lookup /desk/orders?q=<order_ref>, never to the attorney page (RULE-PIPE-06).',
    '"Needed from clients" lists open client_requests grouped by client with days waiting (lib.daysSince) and the order they block.',
    'Nudge writes a call_back follow-up due tomorrow; "Call now" appears when the client has a phone and inserts an outbound active call, then opens the console.',
    '"Mark received" is offered only for kind = item, and writes status = received - the desk confirms receipt, it never answers a question or approves a draft for the client.',
    'Due dates = orders whose filing_due_at or due_at falls in the next 14 days, soonest first, with the waiting-on pill so the desk knows whether the hold-up is the client.',
    'The tab and the view are in the URL (?tab=, ?view=) so they can be linked and driven (P-06).',
  ],
  integrations: ['SMS / email / app reminders (Pass 3 comms seam)', 'Telephony (Pass 3)', 'Deadline engine (T-059) feeds filing_due_at'],
  components: ['PageHeader', 'StatTile', 'Section', 'Card', 'Tabs', 'SegmentedControl', 'DataTable', 'WaitingOnPill', 'Select', 'Button', 'Chip', 'Badge', 'StatusBadge', 'EmptyState', 'Placeholder', 'Tooltip', 'Avatar'],
  actions: [
    { id: 'desk.setFollowUpTab', label: 'Tab', intent: 'switch between follow-ups, needed from clients and due dates', permission: 'followups.read', params: { tab: 'enum:followups|needed|dates' } },
    { id: 'desk.setFollowUpView', label: 'Board or list', intent: 'switch the follow-ups between board and list', permission: 'followups.read', params: { view: 'enum:board|list' } },
    { id: 'desk.completeFollowUp', label: 'Done', intent: 'mark a follow-up as done', permission: 'followups.write', params: { id: 'id' } },
    { id: 'desk.snoozeFollowUp', label: 'Snooze', intent: 'snooze a follow-up by a day, three days or a week', permission: 'followups.write', params: { id: 'id', days: 'number' } },
    { id: 'desk.cancelFollowUp', label: 'Cancel', intent: 'cancel a follow-up', permission: 'followups.write', params: { id: 'id' } },
    { id: 'desk.nudgeClient', label: 'Nudge', intent: 'nudge a client about something we need from them', permission: 'followups.write', params: { id: 'id' } },
    { id: 'desk.callClientNow', label: 'Call now', intent: 'call a client about what we need from them', permission: 'calls.write', params: { id: 'id' } },
    { id: 'desk.markRequestReceived', label: 'Mark received', intent: 'mark an item we asked the client for as received', permission: 'orders.read', params: { id: 'id' } },
  ],
  rules: ['RULE-PIPE-02', 'RULE-PIPE-05', 'RULE-PIPE-06'],
  states: ['overdue work', 'a clear list', 'board view', 'list view', 'needed from clients', 'due dates', 'Spanish', 'dark', 'phone at 360', 'wall screen at 3840'],
  checkedAt: CHECKED,
  notes: ['Pass 2 wave A (prompt 0006, D-049). Reminders are recorded as follow-ups today; actually sending an SMS or an email is the Pass 3 comms seam.', '"Mark received" writes client_requests.status = received for item requests only; questions, reviews, approvals and signatures are the client\'s to answer in C-21.'],
});

export const clientsSpec = defineSpec({
  code: 'F-13', name: 'Client directory', purpose: 'Who our clients are and how to reach them, from the desk\'s point of view: name, phone, email, office, how many orders they have, what they still owe us and when we last spoke. One click opens everything about that person - their orders, their calls and their follow-ups - so the desk can answer a cold call without asking an attorney.',
  layout: ['PageHeader', 'Counter strip (clients, with open orders, waiting on us, waiting on them)', 'Search', 'Directory (DataTable)', 'Client drawer: contact, orders, calls, follow-ups, Call / Add follow-up / Send message'],
  data: ['users', 'orders', 'calls', 'follow_ups', 'client_requests', 'tenants'], roles: DESK_ROLES,
  logic: [
    'The directory is the users table filtered to role = client, scoped to the office (P-02); phone numbers are formatted for people, not stored that way (lib.fmtPhone).',
    'Orders count = the client\'s non-terminal orders; open requests = open client_requests; last touch = the latest of orders.last_client_touch_at and the client\'s most recent call.',
    'The drawer shows the client\'s orders with the waiting-on pill, their last calls and their open follow-ups; every order links to the desk lookup, never to the attorney page (RULE-PIPE-06).',
    '"Call" inserts an outbound active call to the client and opens the console; "Add follow-up" writes a check_in follow-up due tomorrow owned by the signed-in user.',
    'The open client is in the URL (?client=<id>) so the drawer can be linked and driven (P-06).',
  ],
  integrations: ['Telephony (Pass 3 seam)', 'SMS / email (Pass 3 comms seam)', 'Supabase Auth (client accounts, T-099)'],
  components: ['PageHeader', 'StatTile', 'Section', 'Card', 'DataTable', 'Drawer', 'SearchInput', 'CallCard', 'WaitingOnPill', 'Button', 'Chip', 'Badge', 'StatusBadge', 'EmptyState', 'Placeholder', 'Tooltip', 'Avatar'],
  actions: [
    { id: 'desk.searchClients', label: 'Search clients', intent: 'search the client directory by name, phone or email', permission: 'clients.read', params: { q: 'string' } },
    { id: 'desk.openClient', label: 'Open client', intent: 'open everything we have on a client', permission: 'clients.read', params: { id: 'id' } },
    { id: 'desk.callClient', label: 'Call', intent: 'call a client', permission: 'calls.write', params: { id: 'id' } },
    { id: 'desk.addClientFollowUp', label: 'Add follow-up', intent: 'add a follow-up for a client', permission: 'followups.write', params: { id: 'id' } },
    { id: 'desk.messageClient', label: 'Send message', intent: 'send a client a message', permission: 'messages.write', params: { id: 'id' } },
  ],
  rules: ['RULE-PIPE-02', 'RULE-PIPE-06', 'RULE-SYS-02'],
  states: ['a full directory', 'a search with one hit', 'no results', 'drawer open', 'client with no orders', 'Spanish', 'dark', 'phone at 360', 'wall screen at 3840'],
  checkedAt: CHECKED,
  notes: ['Pass 2 wave A (prompt 0006, D-049). "Send message" is a Placeholder until the Pass 3 comms seam (SMS / email / app).', 'Demo clients are fictional (D-023); the 555 exchange is reserved for fiction.'],
});
