import type { StringTable } from '../../i18n/types';

/**
 * Front-desk strings, en / es from the start (P-13). Desk staff are often the bilingual people in the office, so
 * the Spanish here is first-class, not a fallback: every control, every empty state and every line of the phone
 * script exists in both languages.
 */
export const strings: StringTable = {
  // --- F-01 front desk today -------------------------------------------------------------------------------------
  'desk.title': { en: 'Front desk today', es: 'Recepción hoy' },
  'desk.sub': { en: 'What is ringing, what we owe people and what people owe us: calls, callbacks, orders waiting on a client, due dates, consultations and the intake queue.', es: 'Lo que está sonando, lo que debemos y lo que nos deben: llamadas, devoluciones, pedidos que esperan al cliente, vencimientos, consultas y la fila de admisión.' },
  'desk.lookup': { en: 'Order status lookup', es: 'Buscar el estado de un pedido' },
  'desk.lookupHint': { en: 'Order number, client name or phone — opens the read-only order lookup.', es: 'Número de pedido, nombre del cliente o teléfono: abre la consulta de pedidos (solo lectura).' },
  'desk.lookupPlaceholder': { en: 'ORD-2026-0131, Dana Morales, (951) 555-0142', es: 'ORD-2026-0131, Dana Morales, (951) 555-0142' },
  'desk.consultsToday': { en: 'Consultations today', es: 'Consultas de hoy' },
  'desk.consultsWeek': { en: 'Later this week', es: 'Más adelante esta semana' },
  'desk.intakeQueue': { en: 'Intake queue', es: 'Fila de admisión' },
  'desk.callsToReturn': { en: 'Calls to return', es: 'Llamadas por devolver' },
  'desk.paymentsPending': { en: 'Payments pending', es: 'Pagos pendientes' },
  'desk.quickActions': { en: 'Quick actions', es: 'Acciones rápidas' },
  'desk.newIntake': { en: 'New intake', es: 'Nueva admisión' },
  'desk.bookConsult': { en: 'Book a consultation', es: 'Reservar consulta' },
  'desk.review': { en: 'Review', es: 'Revisar' },
  'desk.schedule': { en: 'Schedule', es: 'Programar' },
  'desk.markHeld': { en: 'Mark as held', es: 'Marcar como realizada' },
  'desk.noConsults': { en: 'No consultations booked for today.', es: 'No hay consultas reservadas para hoy.' },
  'desk.noIntakes': { en: 'The intake queue is empty.', es: 'La fila de admisión está vacía.' },
  'desk.noPayments': { en: 'Nothing waiting to be paid.', es: 'Nada pendiente de pago.' },
  'desk.noCallsToReturn': { en: 'No missed calls or voicemails to return.', es: 'No hay llamadas perdidas ni buzones por devolver.' },
  'desk.openCallLog': { en: 'Open the call console', es: 'Abrir la consola de llamadas' },
  'desk.asListed': { en: 'Prices as listed on the firm site; not a quote.', es: 'Precios según el sitio del bufete; no es una cotización.' },
  'desk.office': { en: 'Office', es: 'Oficina' },
  'desk.unpaid': { en: 'Unpaid', es: 'Sin pagar' },
  'desk.network': { en: 'Whole network', es: 'Toda la red' },
  'desk.tileLive': { en: 'Calls live now', es: 'Llamadas en curso' },
  'desk.tileMissed': { en: 'Missed today', es: 'Perdidas hoy' },
  'desk.tileCallbacks': { en: 'Callbacks due', es: 'Devoluciones pendientes' },
  'desk.tileWaiting': { en: 'Waiting on a client', es: 'Esperando al cliente' },
  'desk.tileNeeded': { en: 'Needed from clients', es: 'Falta del cliente' },
  'desk.tileDue': { en: 'Due dates this week', es: 'Vencimientos esta semana' },
  'desk.ringingNow': { en: 'ringing now', es: 'sonando ahora' },
  'desk.openOrders': { en: 'open orders', es: 'pedidos abiertos' },
  'desk.openRequests': { en: 'open requests', es: 'solicitudes abiertas' },
  'desk.followUpsDue': { en: 'Follow-ups due', es: 'Seguimientos pendientes' },
  'desk.noFollowUps': { en: 'Nothing due. The desk is clear.', es: 'Nada pendiente. Recepción está al día.' },

  // --- shared desk vocabulary ------------------------------------------------------------------------------------
  'desk.client': { en: 'Client', es: 'Cliente' },
  'desk.order': { en: 'Order', es: 'Pedido' },
  'desk.orders': { en: 'Orders', es: 'Pedidos' },
  'desk.due': { en: 'Due', es: 'Vence' },
  'desk.owner': { en: 'Owner', es: 'Responsable' },
  'desk.phone': { en: 'Phone', es: 'Teléfono' },
  'desk.email': { en: 'Email', es: 'Correo' },
  'desk.language': { en: 'Language', es: 'Idioma' },
  'desk.lastTouch': { en: 'Last touch', es: 'Último contacto' },
  'desk.never': { en: 'never', es: 'nunca' },
  'desk.attorney': { en: 'Attorney', es: 'Abogado' },
  'desk.paralegal': { en: 'Paralegal', es: 'Asistente' },
  'desk.unassigned': { en: 'Not assigned yet', es: 'Sin asignar' },
  'desk.status': { en: 'Status', es: 'Estado' },
  'desk.purpose': { en: 'Purpose', es: 'Motivo' },
  'desk.notes': { en: 'Notes', es: 'Notas' },
  'desk.outcome': { en: 'Outcome', es: 'Resultado' },
  'desk.english': { en: 'English', es: 'Inglés' },
  'desk.spanish': { en: 'Spanish', es: 'Español' },
  'desk.saved': { en: 'Saved', es: 'Guardado' },
  'desk.cancel': { en: 'Cancel', es: 'Cancelar' },
  'desk.done': { en: 'Done', es: 'Hecho' },

  // --- F-12 call console -----------------------------------------------------------------------------------------
  'calls.title': { en: 'Calls', es: 'Llamadas' },
  'calls.pageTitle': { en: 'Call console', es: 'Consola de llamadas' },
  'calls.sub': { en: 'Answer, see everything the caller has with us before you say hello, read the status aloud, and leave the call with a note and a next step.', es: 'Conteste, vea todo lo que el cliente tiene con nosotros antes de saludar, lea el estado en voz alta y termine la llamada con una nota y un próximo paso.' },
  'calls.queue': { en: 'Queue', es: 'Cola' },
  'calls.active': { en: 'Active call', es: 'Llamada en curso' },
  'calls.recent': { en: 'Today and callbacks', es: 'Hoy y devoluciones' },
  'calls.ringing': { en: 'Ringing', es: 'Sonando' },
  'calls.onHold': { en: 'On hold', es: 'En espera' },
  'calls.inProgress': { en: 'In progress', es: 'En curso' },
  'calls.missed': { en: 'Missed', es: 'Perdida' },
  'calls.voicemail': { en: 'Voicemail', es: 'Buzón de voz' },
  'calls.ended': { en: 'Ended', es: 'Terminada' },
  'calls.answer': { en: 'Answer', es: 'Contestar' },
  'calls.hold': { en: 'Hold', es: 'Poner en espera' },
  'calls.resume': { en: 'Resume', es: 'Reanudar' },
  'calls.end': { en: 'End call', es: 'Colgar' },
  'calls.toVoicemail': { en: 'Send to voicemail', es: 'Enviar al buzón' },
  'calls.callBack': { en: 'Call back', es: 'Devolver la llamada' },
  'calls.simulate': { en: 'Simulate incoming call', es: 'Simular llamada entrante' },
  'calls.simulateHint': { en: 'Demo: rings a call from a seeded client, or an unknown number one time in four. Real telephony arrives in Pass 3.', es: 'Demostración: hace sonar una llamada de un cliente de ejemplo, o de un número desconocido una de cada cuatro veces. La telefonía real llega en la pasada 3.' },
  'calls.queueEmpty': { en: 'Nothing ringing. The queue is clear.', es: 'No suena nada. La cola está vacía.' },
  'calls.noneSelected': { en: 'No call open', es: 'Ninguna llamada abierta' },
  'calls.noneSelectedBody': { en: 'Answer a ringing call, pick one from the queue, or call somebody back from today\'s list.', es: 'Conteste una llamada, elija una de la cola o devuelva una llamada de la lista de hoy.' },
  'calls.unknownCaller': { en: 'Unknown caller', es: 'Persona desconocida' },
  'calls.unknownBody': { en: 'This number is not on any client record. Search for the person, or start an intake.', es: 'Este número no está en ningún expediente. Busque a la persona o inicie una admisión.' },
  'calls.searchCaller': { en: 'Search clients by name or phone', es: 'Buscar clientes por nombre o teléfono' },
  'calls.linkCaller': { en: 'This is them', es: 'Es esta persona' },
  'calls.startIntake': { en: 'Start intake', es: 'Iniciar admisión' },
  'calls.callerOrders': { en: 'What this caller has with us', es: 'Lo que este cliente tiene con nosotros' },
  'calls.noOrders': { en: 'No orders on this client yet.', es: 'Este cliente todavía no tiene pedidos.' },
  'calls.readStatus': { en: 'Read status', es: 'Leer el estado' },
  'calls.hideStatus': { en: 'Hide the script', es: 'Ocultar el guion' },
  'calls.scriptHead': { en: 'Read this to the caller', es: 'Lea esto a la persona que llama' },
  'calls.checklist': { en: 'Checklist for this call', es: 'Lista de verificación de la llamada' },
  'calls.chkHands': { en: 'Is the order in the right hands?', es: '¿El pedido está en las manos correctas?' },
  'calls.chkHandsBody': { en: 'Name the attorney and the paralegal on each order. If the caller says it is with the wrong person, flag it.', es: 'Diga qué abogado y qué asistente llevan cada pedido. Si el cliente dice que está con la persona equivocada, márquelo.' },
  'calls.flagReassign': { en: 'Flag for reassignment', es: 'Marcar para reasignar' },
  'calls.flagged': { en: 'Flagged for the attorney to look at.', es: 'Marcado para que lo revise el abogado.' },
  'calls.chkWaiting': { en: 'Anything waiting on the client?', es: '¿Falta algo del cliente?' },
  'calls.chkWaitingBody': { en: 'Everything we have asked for and not received. Ask for it now while you have them.', es: 'Todo lo que pedimos y no hemos recibido. Pídalo ahora que está al teléfono.' },
  'calls.nothingWaiting': { en: 'Nothing is waiting on this client.', es: 'No falta nada de este cliente.' },
  'calls.remindNote': { en: 'Remind and note', es: 'Recordar y anotar' },
  'calls.reminded': { en: 'Reminder noted; a follow-up is due tomorrow.', es: 'Recordatorio anotado; el seguimiento vence mañana.' },
  'calls.chkDates': { en: 'Due dates coming up', es: 'Fechas que se acercan' },
  'calls.chkDatesBody': { en: 'Filing and delivery dates in the next fortnight. Say the date out loud and confirm they have it.', es: 'Fechas de presentación y entrega de las próximas dos semanas. Diga la fecha en voz alta y confirme que la tienen.' },
  'calls.noDates': { en: 'No dates in the next fortnight.', es: 'No hay fechas en las próximas dos semanas.' },
  'calls.chkPayment': { en: 'Payment', es: 'Pago' },
  'calls.chkPaymentBody': { en: 'Balances and hotline blocks. Taking a card over the phone arrives with the payments seam.', es: 'Saldos y bloques de la línea directa. Cobrar con tarjeta por teléfono llega con la integración de pagos.' },
  'calls.takePayment': { en: 'Take payment', es: 'Cobrar' },
  'calls.chkConsult': { en: 'Schedule a consult', es: 'Agendar una consulta' },
  'calls.chkConsultBody': { en: 'Thirty-minute prepaid blocks with an attorney; the scheduler arrives in the scheduling pass.', es: 'Bloques prepagados de treinta minutos con un abogado; el calendario llega en la pasada de agenda.' },
  'calls.bookConsult': { en: 'Schedule', es: 'Agendar' },
  'calls.wrapUp': { en: 'Wrap up', es: 'Cierre de la llamada' },
  'calls.notesHint': { en: 'Saved to the call as you type.', es: 'Se guarda en la llamada mientras escribe.' },
  'calls.outcomePlaceholder': { en: 'Choose what was decided', es: 'Elija lo que se decidió' },
  'calls.purposePlaceholder': { en: 'Why are they calling?', es: '¿Por qué llaman?' },
  'calls.purpose.status': { en: 'Status of an order', es: 'Estado de un pedido' },
  'calls.purpose.new_consult': { en: 'New matter / consultation', es: 'Caso nuevo / consulta' },
  'calls.purpose.payment': { en: 'Payment or receipt', es: 'Pago o recibo' },
  'calls.purpose.documents': { en: 'Documents or uploads', es: 'Documentos o archivos' },
  'calls.purpose.scheduling': { en: 'Scheduling', es: 'Agenda' },
  'calls.purpose.other': { en: 'Something else', es: 'Otra cosa' },
  'calls.outcome.informed': { en: 'Told them where the order stands', es: 'Le dije en qué estado está el pedido' },
  'calls.outcome.asked': { en: 'Asked for what we still need', es: 'Pedí lo que todavía falta' },
  'calls.outcome.followUp': { en: 'Created a follow-up', es: 'Creé un seguimiento' },
  'calls.outcome.transferred': { en: 'Transferred to the attorney', es: 'Transferí al abogado' },
  'calls.outcome.consult': { en: 'Booked a consultation', es: 'Reservé una consulta' },
  'calls.outcome.payment': { en: 'Handled a payment question', es: 'Atendí una consulta de pago' },
  'calls.outcome.message': { en: 'Took a message', es: 'Tomé un mensaje' },
  'calls.hotline': { en: 'Hotline minutes', es: 'Minutos de línea directa' },
  'calls.logMinutes': { en: 'Log minutes', es: 'Registrar minutos' },
  'calls.minutesLogged': { en: 'Hotline minutes recorded on this call.', es: 'Minutos de la línea directa registrados en esta llamada.' },
  'calls.createFollowUp': { en: 'Create a follow-up', es: 'Crear un seguimiento' },
  'calls.endedBody': { en: 'Call logged. Anything left to do?', es: 'Llamada registrada. ¿Queda algo por hacer?' },
  'calls.avgHandle': { en: 'Average handle time', es: 'Duración media' },
  'calls.today': { en: 'Today', es: 'Hoy' },
  'calls.started': { en: 'Started', es: 'Empezó' },
  'calls.length': { en: 'Length', es: 'Duración' },
  'calls.direction': { en: 'Direction', es: 'Dirección' },
  'calls.inbound': { en: 'Inbound', es: 'Entrante' },
  'calls.outbound': { en: 'Outbound', es: 'Saliente' },
  'calls.handledBy': { en: 'Handled by', es: 'Atendida por' },
  'calls.noRecent': { en: 'No calls today yet.', es: 'Todavía no hay llamadas hoy.' },
  'calls.filterStatus': { en: 'Status', es: 'Estado' },
  'calls.filterPurpose': { en: 'Purpose', es: 'Motivo' },
  'calls.demo': { en: 'Demo', es: 'Demostración' },

  // --- F-15 follow-ups -------------------------------------------------------------------------------------------
  'fu.title': { en: 'Follow-ups', es: 'Seguimientos' },
  'fu.sub': { en: 'Everything the desk owes somebody, with a date on it — and everything clients still owe us.', es: 'Todo lo que recepción le debe a alguien, con fecha, y todo lo que los clientes todavía nos deben.' },
  'fu.tabFollowUps': { en: 'Follow-ups', es: 'Seguimientos' },
  'fu.tabNeeded': { en: 'Needed from clients', es: 'Falta del cliente' },
  'fu.tabDates': { en: 'Due dates', es: 'Vencimientos' },
  'fu.board': { en: 'Board', es: 'Tablero' },
  'fu.list': { en: 'List', es: 'Lista' },
  'fu.overdue': { en: 'Overdue', es: 'Atrasados' },
  'fu.today': { en: 'Today', es: 'Hoy' },
  'fu.week': { en: 'This week', es: 'Esta semana' },
  'fu.later': { en: 'Later', es: 'Más adelante' },
  'fu.empty': { en: 'Nothing here.', es: 'Nada por aquí.' },
  'fu.allClear': { en: 'Nothing open. The desk is clear.', es: 'Nada abierto. Recepción está al día.' },
  'fu.snooze': { en: 'Snooze', es: 'Posponer' },
  'fu.snooze1': { en: 'Tomorrow', es: 'Mañana' },
  'fu.snooze3': { en: 'In three days', es: 'En tres días' },
  'fu.snooze7': { en: 'Next week', es: 'La próxima semana' },
  'fu.snoozed': { en: 'Snoozed.', es: 'Pospuesto.' },
  'fu.cancelled': { en: 'Cancelled.', es: 'Cancelado.' },
  'fu.completed': { en: 'Marked done.', es: 'Marcado como hecho.' },
  'fu.kind.call_back': { en: 'Call back', es: 'Devolver llamada' },
  'fu.kind.client_item_due': { en: 'Item from client', es: 'Documento del cliente' },
  'fu.kind.client_review_due': { en: 'Client review', es: 'Revisión del cliente' },
  'fu.kind.filing_due': { en: 'Filing', es: 'Presentación' },
  'fu.kind.hearing': { en: 'Hearing', es: 'Audiencia' },
  'fu.kind.payment_due': { en: 'Payment', es: 'Pago' },
  'fu.kind.check_in': { en: 'Check in', es: 'Contactar' },
  'fu.needed': { en: 'Still needed from clients', es: 'Todavía falta de los clientes' },
  'fu.neededEmpty': { en: 'Clients owe us nothing right now.', es: 'Ahora mismo los clientes no nos deben nada.' },
  'fu.waitingDays': { en: 'waiting {days}', es: 'esperando {days}' },
  'fu.nudge': { en: 'Nudge', es: 'Recordar' },
  'fu.nudged': { en: 'Nudge noted; a call-back follow-up is due tomorrow.', es: 'Recordatorio anotado; la devolución de llamada vence mañana.' },
  'fu.callNow': { en: 'Call now', es: 'Llamar ahora' },
  'fu.markReceived': { en: 'Mark received', es: 'Marcar como recibido' },
  'fu.received': { en: 'Marked received.', es: 'Marcado como recibido.' },
  'fu.receivedOnlyItems': { en: 'Only things the client sends us can be marked received; questions, reviews and approvals are theirs to answer.', es: 'Solo se puede marcar como recibido lo que el cliente nos envía; las preguntas, revisiones y aprobaciones las responde el cliente.' },
  'fu.request.question': { en: 'Question', es: 'Pregunta' },
  'fu.request.item': { en: 'Document or photo', es: 'Documento o foto' },
  'fu.request.review': { en: 'Review', es: 'Revisión' },
  'fu.request.approval': { en: 'Approval', es: 'Aprobación' },
  'fu.request.signature': { en: 'Signature', es: 'Firma' },
  'fu.request.payment': { en: 'Payment', es: 'Pago' },
  'fu.dates': { en: 'Filing and delivery dates, next 14 days', es: 'Presentaciones y entregas, próximos 14 días' },
  'fu.datesEmpty': { en: 'No dates in the next fortnight.', es: 'No hay fechas en las próximas dos semanas.' },
  'fu.filingDue': { en: 'Filing due', es: 'Presentación' },
  'fu.deliveryDue': { en: 'Delivery due', es: 'Entrega' },

  // --- F-13 clients ----------------------------------------------------------------------------------------------
  'cl.title': { en: 'Clients', es: 'Clientes' },
  'cl.sub': { en: 'Everyone we act for, how to reach them, what they have with us and when we last spoke.', es: 'Todas las personas a quienes representamos, cómo contactarlas, qué tienen con nosotros y cuándo hablamos por última vez.' },
  'cl.search': { en: 'Search by name, phone or email', es: 'Buscar por nombre, teléfono o correo' },
  'cl.none': { en: 'No clients match that search.', es: 'Ningún cliente coincide con esa búsqueda.' },
  'cl.tileAll': { en: 'Clients', es: 'Clientes' },
  'cl.tileOrders': { en: 'With open orders', es: 'Con pedidos abiertos' },
  'cl.tileWaitingUs': { en: 'Waiting on us', es: 'Nos esperan' },
  'cl.tileWaitingThem': { en: 'Waiting on them', es: 'Los esperamos' },
  'cl.ordersCount': { en: 'Orders', es: 'Pedidos' },
  'cl.requestsCount': { en: 'Open requests', es: 'Solicitudes' },
  'cl.call': { en: 'Call', es: 'Llamar' },
  'cl.addFollowUp': { en: 'Add follow-up', es: 'Añadir seguimiento' },
  'cl.message': { en: 'Send message', es: 'Enviar mensaje' },
  'cl.drawerOrders': { en: 'Orders', es: 'Pedidos' },
  'cl.drawerCalls': { en: 'Recent calls', es: 'Llamadas recientes' },
  'cl.drawerFollowUps': { en: 'Open follow-ups', es: 'Seguimientos abiertos' },
  'cl.noOrders': { en: 'No orders yet.', es: 'Todavía no hay pedidos.' },
  'cl.noCalls': { en: 'No calls on record.', es: 'No hay llamadas registradas.' },
  'cl.noFollowUps': { en: 'No open follow-ups.', es: 'No hay seguimientos abiertos.' },
  'cl.followUpAdded': { en: 'Follow-up added for tomorrow.', es: 'Seguimiento añadido para mañana.' },
  'cl.calling': { en: 'Calling {name} — the call is open in the console.', es: 'Llamando a {name}: la llamada está abierta en la consola.' },
  'cl.noPhone': { en: 'No phone number on file.', es: 'No hay teléfono registrado.' },
};
