import type { StringTable } from '../../i18n/types';

/** K-10..K-13 legal memory. The banner is bilingual and cannot be dismissed while any row is unverified (D-019). */
export const strings: StringTable = {
  'legal.title': { en: 'Legal memory', es: 'Memoria legal' },
  'legal.subtitle': { en: 'The law CTL OS relies on: one row per statute with the date an attorney verified it, an append-only log of changes in the law, and one page per practice area. Code cites a row by its citation string, so nothing here can be renamed silently.', es: 'La ley en la que se apoya CTL OS: una fila por artículo con la fecha en que un abogado la verificó, un registro de cambios de ley que solo crece y una página por área de práctica. El código cita cada fila por su cadena de cita, así nada se renombra en silencio.' },
  'legal.banner.title': { en: 'Nothing here is verified legal advice yet', es: 'Nada aquí es asesoría legal verificada todavía' },
  'legal.banner.body': { en: 'Every row shows its verified_on date. {unverified} of {total} rows are still unverified: a model wrote them from the firm\'s own published content and general knowledge of California landlord-tenant law, without reading the current code. No deadline, cost or draft may treat an unverified row as current until a licensed attorney sets verified_on.', es: 'Cada fila muestra su fecha verified_on. {unverified} de {total} filas siguen sin verificar: un modelo las escribió a partir del contenido publicado del bufete y conocimiento general del derecho de arrendamiento de California, sin leer el código vigente. Ningún plazo, costo ni borrador puede tratar una fila sin verificar como vigente hasta que un abogado con licencia ponga verified_on.' },
  'legal.banner.rule': { en: 'D-019 · docs/legal/README.md', es: 'D-019 · docs/legal/README.md' },
  'legal.tiles.rows': { en: 'Statute rows', es: 'Filas de ley' },
  'legal.tiles.unverified': { en: 'Unverified', es: 'Sin verificar' },
  'legal.tiles.currency': { en: 'Flagged for 2026 check', es: 'Marcadas para revisión 2026' },
  'legal.tiles.changes': { en: 'Law changes logged', es: 'Cambios de ley registrados' },
  'legal.tiles.topics': { en: 'Topics', es: 'Temas' },
  'legal.loading': { en: 'Loading the legal memory…', es: 'Cargando la memoria legal…' },

  'legal.nav.index': { en: 'Statute index', es: 'Índice de leyes' },
  'legal.nav.changes': { en: 'Law-change log', es: 'Registro de cambios de ley' },
  'legal.nav.topics': { en: 'Topics', es: 'Temas' },
  'legal.nav.queue': { en: 'Verification queue', es: 'Cola de verificación' },

  'legal.table.citation': { en: 'Citation', es: 'Cita' },
  'legal.table.topic': { en: 'Topic', es: 'Tema' },
  'legal.table.rule': { en: 'Rule (as understood)', es: 'Regla (según se entiende)' },
  'legal.table.verifiedOn': { en: 'verified_on', es: 'verified_on' },
  'legal.table.source': { en: 'Source', es: 'Fuente' },
  'legal.table.flag': { en: 'Flag', es: 'Bandera' },
  'legal.table.section': { en: 'Section', es: 'Sección' },
  'legal.unverified': { en: 'unverified', es: 'sin verificar' },
  'legal.currencyFlag': { en: '2026 currency check', es: 'revisión de actualidad 2026' },
  'legal.addedFlag': { en: 'added for the game board', es: 'añadida por el tablero' },
  'legal.filter.topic': { en: 'Topic', es: 'Tema' },
  'legal.filter.allTopics': { en: 'Every topic', es: 'Todos los temas' },
  'legal.filter.currency': { en: 'Currency', es: 'Actualidad' },
  'legal.filter.currencyAll': { en: 'Every row', es: 'Todas las filas' },
  'legal.filter.currencyFlagged': { en: 'Flagged for 2026 currency check', es: 'Marcadas para revisión 2026' },
  'legal.filter.currencyUnverified': { en: 'Unverified only', es: 'Solo sin verificar' },
  'legal.rows': { en: '{n} rows', es: '{n} filas' },
  'legal.none': { en: 'No row matches that filter', es: 'Ninguna fila coincide con ese filtro' },

  'legal.changes.title': { en: 'Law-change log', es: 'Registro de cambios de ley' },
  'legal.changes.subtitle': { en: 'Append-only, newest first. A change to a rule the product relies on gets a row here before the statute row or the code changes, so nobody drafts against a superseded rule.', es: 'Solo se añade, más reciente primero. Un cambio en una regla que el producto usa recibe una fila aquí antes de tocar la fila de ley o el código, para que nadie redacte contra una regla derogada.' },
  'legal.changes.effective': { en: 'Effective {date}', es: 'Vigente desde {date}' },
  'legal.changes.logged': { en: 'Logged {date}', es: 'Registrado {date}' },
  'legal.changes.citations': { en: 'Affected citations', es: 'Citas afectadas' },
  'legal.changes.surfaces': { en: 'Affected surfaces', es: 'Superficies afectadas' },
  'legal.changes.note': { en: 'Note', es: 'Nota' },
  'legal.changes.none': { en: 'No change has been logged yet', es: 'Aún no se ha registrado ningún cambio' },

  'legal.topic.related': { en: 'Statutes on this topic', es: 'Leyes de este tema' },
  'legal.topic.changes': { en: 'Changes in the law that touch this topic', es: 'Cambios de ley que afectan este tema' },
  'legal.topic.notFound': { en: 'No such topic', es: 'No existe ese tema' },
  'legal.topic.notFoundBody': { en: 'Topics are markdown files in docs/legal/topics; pick one below.', es: 'Los temas son archivos markdown en docs/legal/topics; elige uno abajo.' },
  'legal.topic.open': { en: 'Open the topic', es: 'Abrir el tema' },

  'legal.queue.title': { en: 'Verification queue', es: 'Cola de verificación' },
  'legal.queue.body': { en: 'Rows with verified_on empty, most flagged first. Only a licensed attorney at the firm sets verified_on, after reading the current code section; the workflow that records it is the legal verification pass (Pass 2).', es: 'Filas con verified_on vacío, primero las marcadas. Solo un abogado con licencia del bufete pone verified_on, después de leer el artículo vigente; el flujo que lo registra es la pasada de verificación legal (Pasada 2).' },
  'legal.queue.markVerified': { en: 'Mark verified', es: 'Marcar verificada' },
  'legal.queue.markVerifiedWhat': { en: 'record verified_on, verified_by and the code text an attorney read for this citation', es: 'registrar verified_on, verified_by y el texto legal que el abogado leyó para esta cita' },
  'legal.queue.all': { en: 'Every row is verified', es: 'Todas las filas están verificadas' },
  'legal.queue.showing': { en: 'Showing {n} of {total} unverified rows', es: 'Mostrando {n} de {total} filas sin verificar' },
  'legal.queue.openIndex': { en: 'Open the full statute index', es: 'Abrir el índice completo' },
  'legal.source': { en: 'Source file', es: 'Archivo fuente' },
};
