import type { StringTable } from '../../i18n/types';

/** Every visible string of the PM viewer (P-13). Spanish where it is clear; English is the fallback. */
export const strings: StringTable = {
  'plan.title.kanban': { en: 'Plan board', es: 'Tablero del plan' },
  'plan.title.list': { en: 'Plan list', es: 'Lista del plan' },
  'plan.title.timeline': { en: 'Plan timeline', es: 'Cronología del plan' },
  'plan.title.graph': { en: 'Dependency graph', es: 'Grafo de dependencias' },
  'plan.title.passes': { en: 'Passes', es: 'Pasadas' },
  'plan.title.task': { en: 'Task', es: 'Tarea' },

  'plan.sub.kanban': { en: 'Every task in docs/plan/tasks.json as a card. Moving a card writes through the data provider, so the move survives a reload and is ready for two people at once.', es: 'Cada tarea de docs/plan/tasks.json como tarjeta. Mover una tarjeta se guarda en el proveedor de datos, así que el cambio persiste y admite varias personas a la vez.' },
  'plan.sub.list': { en: 'Every task as a sortable, groupable table. Click a row for the detail.', es: 'Todas las tareas en una tabla ordenable y agrupable. Pulse una fila para ver el detalle.' },
  'plan.sub.timeline': { en: 'Tasks placed on dependency ticks, not calendar days: a task starts the moment everything it depends on is done.', es: 'Tareas situadas en ticks de dependencia, no en días: una tarea empieza en cuanto termina todo aquello de lo que depende.' },
  'plan.sub.graph': { en: 'The plan as objects: one card-like node per task, its icon from its lane, its ring from its status.', es: 'El plan como objetos: un nodo por tarea, el icono según su carril y el anillo según su estado.' },
  'plan.sub.passes': { en: 'Goal, gate and progress of each pass, with the work split by model.', es: 'Objetivo, puerta y progreso de cada pasada, con el trabajo repartido por modelo.' },

  'plan.units': { en: 'Units are dependency ticks, not days', es: 'Las unidades son ticks de dependencia, no días' },
  'plan.unitsLong': { en: 'Units are dependency ticks, NOT calendar days: tick 0 starts immediately, tick n waits for a chain of n tasks.', es: 'Las unidades son ticks de dependencia, NO días: el tick 0 empieza ya; el tick n espera una cadena de n tareas.' },

  'plan.status.todo': { en: 'Backlog', es: 'Pendiente' },
  'plan.status.doing': { en: 'Doing', es: 'En curso' },
  'plan.status.blocked': { en: 'Blocked', es: 'Bloqueado' },
  'plan.status.done': { en: 'Done', es: 'Hecho' },

  'plan.group.lane': { en: 'By lane', es: 'Por carril' },
  'plan.group.pass': { en: 'By pass', es: 'Por pasada' },
  'plan.group.flat': { en: 'Flat', es: 'Sin agrupar' },
  'plan.group.model': { en: 'By model', es: 'Por modelo' },
  'plan.group.status': { en: 'By status', es: 'Por estado' },
  'plan.group.none': { en: 'No grouping', es: 'Sin agrupar' },
  'plan.group.label': { en: 'Grouping', es: 'Agrupación' },

  'plan.filter.title': { en: 'Filters', es: 'Filtros' },
  'plan.filter.pass': { en: 'Pass', es: 'Pasada' },
  'plan.filter.model': { en: 'Model', es: 'Modelo' },
  'plan.filter.lane': { en: 'Lane', es: 'Carril' },
  'plan.filter.status': { en: 'Status', es: 'Estado' },
  'plan.filter.all': { en: 'All', es: 'Todas' },
  'plan.filter.search': { en: 'Search tasks', es: 'Buscar tareas' },
  'plan.filter.clear': { en: 'Clear filters', es: 'Quitar filtros' },
  'plan.filter.showing': { en: '{n} of {total} tasks', es: '{n} de {total} tareas' },

  'plan.card.moveTo': { en: 'Move to…', es: 'Mover a…' },
  'plan.card.moveHelp': { en: 'Move this task to another column', es: 'Mover esta tarea a otra columna' },
  'plan.card.deps': { en: '{n} deps', es: '{n} dep.' },
  'plan.card.blocked': { en: 'Blocked by {n}', es: 'Bloqueada por {n}' },
  'plan.card.blockedBy': { en: 'Waiting for: {ids}', es: 'Espera a: {ids}' },
  'plan.card.tick': { en: 'tick {n}', es: 'tick {n}' },
  'plan.card.critical': { en: 'Critical path', es: 'Ruta crítica' },
  'plan.card.open': { en: 'Open task', es: 'Abrir tarea' },
  'plan.card.drag': { en: 'Drag, or use Move to…', es: 'Arrastre o use Mover a…' },

  'plan.col.count': { en: '{n} tasks', es: '{n} tareas' },
  'plan.empty.column': { en: 'Nothing here', es: 'Nada aquí' },
  'plan.empty.tasks': { en: 'No task matches these filters', es: 'Ninguna tarea coincide con estos filtros' },
  'plan.empty.tasksBody': { en: 'Clear a filter or search for another word.', es: 'Quite un filtro o busque otra palabra.' },
  'plan.empty.task': { en: 'Task not found', es: 'Tarea no encontrada' },
  'plan.empty.taskBody': { en: 'No task with that id is in the plan. Open the board to pick one.', es: 'No hay ninguna tarea con ese id en el plan. Abra el tablero para elegir una.' },

  'plan.reset': { en: 'Reset to repo plan', es: 'Restaurar el plan del repo' },
  'plan.resetHelp': { en: 'Re-apply docs/plan/tasks.json over the stored rows', es: 'Vuelve a aplicar docs/plan/tasks.json sobre las filas guardadas' },

  'plan.col.id': { en: 'Id', es: 'Id' },
  'plan.col.code': { en: 'Code', es: 'Código' },
  'plan.col.title': { en: 'Title', es: 'Título' },
  'plan.col.lane': { en: 'Lane', es: 'Carril' },
  'plan.col.pass': { en: 'Pass', es: 'Pasada' },
  'plan.col.tick': { en: 'Tick', es: 'Tick' },
  'plan.col.model': { en: 'Model', es: 'Modelo' },
  'plan.col.status': { en: 'Status', es: 'Estado' },
  'plan.col.size': { en: 'Size', es: 'Tamaño' },
  'plan.col.deps': { en: 'Depends on', es: 'Depende de' },
  'plan.list.export': { en: 'Export CSV', es: 'Exportar CSV' },
  'plan.list.exported': { en: 'CSV downloaded', es: 'CSV descargado' },
  'plan.list.empty': { en: 'No tasks match', es: 'Sin coincidencias' },

  'plan.tl.zoomIn': { en: 'Zoom in', es: 'Acercar' },
  'plan.tl.zoomOut': { en: 'Zoom out', es: 'Alejar' },
  'plan.tl.zoomReset': { en: 'Reset zoom', es: 'Restablecer zoom' },
  'plan.tl.zoomLevel': { en: 'Zoom {n}%', es: 'Zoom {n}%' },
  'plan.tl.today': { en: 'Now (tick {n})', es: 'Ahora (tick {n})' },
  'plan.tl.axis': { en: 'Dependency tick', es: 'Tick de dependencia' },
  'plan.tl.collapse': { en: 'Collapse lane', es: 'Plegar carril' },
  'plan.tl.expand': { en: 'Expand lane', es: 'Desplegar carril' },
  'plan.tl.criticalOnly': { en: 'Critical path only', es: 'Solo ruta crítica' },
  'plan.tl.showLinks': { en: 'Dependency lines', es: 'Líneas de dependencia' },
  'plan.tl.hint': { en: 'Scroll or use the arrow keys to pan; the zoom buttons work from the keyboard.', es: 'Desplace o use las flechas para moverse; los botones de zoom funcionan con teclado.' },
  'plan.tl.parallel': { en: '{n} tasks can run in parallel at tick {t}', es: '{n} tareas pueden ir en paralelo en el tick {t}' },

  'plan.graph.layout': { en: 'Layout', es: 'Disposición' },
  'plan.graph.lanes': { en: 'Lanes', es: 'Carriles' },
  'plan.graph.radial': { en: 'Radial', es: 'Radial' },
  'plan.graph.legend': { en: 'Icon = lane · ring = status · tone = model', es: 'Icono = carril · anillo = estado · tono = modelo' },
  'plan.graph.selected': { en: 'Selected: {id}', es: 'Seleccionada: {id}' },
  'plan.graph.upstream': { en: '{n} upstream', es: '{n} antes' },
  'plan.graph.downstream': { en: '{n} downstream', es: '{n} después' },
  'plan.graph.hint': { en: 'Tab to a node, Enter opens it. Selecting a node highlights what it waits for and what waits for it.', es: 'Tabule hasta un nodo y pulse Intro para abrirlo. Al seleccionar se resalta lo que espera y lo que la espera.' },
  'plan.graph.rings': { en: 'Rings are passes, sectors are lanes', es: 'Los anillos son pasadas; los sectores, carriles' },

  'plan.pass.goal': { en: 'Goal', es: 'Objetivo' },
  'plan.pass.gate': { en: 'Gate', es: 'Puerta' },
  'plan.pass.progress': { en: 'Pass {n} progress', es: 'Progreso de la pasada {n}' },
  'plan.pass.tasks': { en: '{n} tasks', es: '{n} tareas' },
  'plan.pass.byModel': { en: 'By model', es: 'Por modelo' },
  'plan.pass.byStatus': { en: 'By status', es: 'Por estado' },
  'plan.pass.open': { en: 'Open the board filtered to this pass', es: 'Abrir el tablero filtrado por esta pasada' },

  'plan.task.dependencies': { en: 'Depends on', es: 'Depende de' },
  'plan.task.dependents': { en: 'Waited on by', es: 'La esperan' },
  'plan.task.deliverables': { en: 'Deliverables', es: 'Entregables' },
  'plan.task.acceptance': { en: 'Acceptance', es: 'Aceptación' },
  'plan.task.notes': { en: 'Notes', es: 'Notas' },
  'plan.task.none': { en: 'None', es: 'Ninguno' },
  'plan.task.setStatus': { en: 'Status', es: 'Estado' },
  'plan.task.openPage': { en: 'Open page', es: 'Abrir página' },
  'plan.task.openDoc': { en: 'Page doc', es: 'Doc de la página' },
  'plan.task.back': { en: 'Back to the board', es: 'Volver al tablero' },
  'plan.task.meta': { en: 'Lane {lane} · pass {pass} · tick {tick} · size {size}', es: 'Carril {lane} · pasada {pass} · tick {tick} · tamaño {size}' },
  'plan.task.moved': { en: 'Moved {id} to {status}', es: '{id} movida a {status}' },

  'plan.stat.tasks': { en: 'Tasks', es: 'Tareas' },
  'plan.stat.done': { en: 'Done', es: 'Hechas' },
  'plan.stat.span': { en: 'Plan length', es: 'Longitud del plan' },
  'plan.stat.spanHint': { en: 'longest dependency chain', es: 'cadena de dependencias más larga' },
  'plan.stat.critical': { en: 'On the critical path', es: 'En la ruta crítica' },
  'plan.nav.kanban': { en: 'Board', es: 'Tablero' },
  'plan.nav.list': { en: 'List', es: 'Lista' },
  'plan.nav.timeline': { en: 'Timeline', es: 'Cronología' },
  'plan.nav.graph': { en: 'Graph', es: 'Grafo' },
  'plan.nav.passes': { en: 'Passes', es: 'Pasadas' },
  'plan.views': { en: 'Plan views', es: 'Vistas del plan' },
};
