import type { StringTable } from '../../i18n/types';

/** M-01..M-03 plus the `manual.live.*` labels the LiveBlock organism renders inside a chapter. */
export const strings: StringTable = {
  'manual.title': { en: 'Operations manual', es: 'Manual de operaciones' },
  'manual.subtitle': { en: 'How California Tenant Law runs, per role, in person and in the software. Every price, deadline, office and rule in a chapter is read live from the system, so the manual is never older than the data.', es: 'Cómo funciona California Tenant Law, por rol, en persona y en el software. Cada precio, plazo, oficina y regla de un capítulo se lee en vivo del sistema, así el manual nunca es más viejo que los datos.' },
  'manual.parts': { en: 'Parts', es: 'Partes' },
  'manual.chapters': { en: '{n} chapters', es: '{n} capítulos' },
  'manual.chaptersOne': { en: '1 chapter', es: '1 capítulo' },
  'manual.lang': { en: 'Manual language', es: 'Idioma del manual' },
  'manual.lang.en': { en: 'English', es: 'Inglés' },
  'manual.lang.es': { en: 'Spanish', es: 'Español' },
  'manual.role': { en: 'For', es: 'Para' },
  'manual.role.all': { en: 'Every role', es: 'Todos los roles' },
  'manual.progress': { en: 'Read {done} of {total}', es: 'Leídos {done} de {total}' },
  'manual.progressLabel': { en: 'Chapters read', es: 'Capítulos leídos' },
  'manual.read': { en: 'Read', es: 'Leído' },
  'manual.markRead': { en: 'Mark read', es: 'Marcar leído' },
  'manual.markUnread': { en: 'Mark unread', es: 'Marcar no leído' },
  'manual.inPerson': { en: 'Done in person', es: 'Hecho en persona' },
  'manual.inCtlOs': { en: 'Done in CTL OS', es: 'Hecho en CTL OS' },
  'manual.minutes': { en: '{n} min', es: '{n} min' },
  'manual.updated': { en: 'Updated {date}', es: 'Actualizado {date}' },
  'manual.version': { en: 'Version', es: 'Versión' },
  'manual.part': { en: 'Part', es: 'Parte' },
  'manual.open': { en: 'Open the chapter', es: 'Abrir el capítulo' },
  'manual.empty': { en: 'No chapter matches that filter', es: 'Ningún capítulo coincide con ese filtro' },
  'manual.emptyBody': { en: 'Chapters are markdown files in docs/ops-manual/{en,es}; adding one needs no code.', es: 'Los capítulos son archivos markdown en docs/ops-manual/{en,es}; añadir uno no requiere código.' },
  'manual.loading': { en: 'Loading the chapter…', es: 'Cargando el capítulo…' },
  'manual.fallback': { en: 'This chapter has no Spanish version yet, so you are reading the English source. Spanish fill is a pass, never a blocker.', es: 'Este capítulo aún no tiene versión en español, así que estás leyendo la fuente en inglés. El llenado en español es una pasada, nunca un bloqueo.' },
  'manual.notFound': { en: 'No such chapter', es: 'No existe ese capítulo' },
  'manual.notFoundBody': { en: 'Pick a chapter below; the manual is written as markdown files under docs/ops-manual.', es: 'Elige un capítulo abajo; el manual son archivos markdown en docs/ops-manual.' },
  'manual.outline': { en: 'In this chapter', es: 'En este capítulo' },
  'manual.outlineJump': { en: 'Jump to a section', es: 'Ir a una sección' },
  'manual.prev': { en: 'Previous chapter', es: 'Capítulo anterior' },
  'manual.next': { en: 'Next chapter', es: 'Capítulo siguiente' },
  'manual.source': { en: 'Source file', es: 'Archivo fuente' },
  'manual.decisionsLink': { en: 'Decisions needed', es: 'Decisiones pendientes' },
  'manual.decisionsCount': { en: '{n} decisions needed', es: '{n} decisiones pendientes' },
  'manual.decisionsCountOne': { en: '1 decision needed', es: '1 decisión pendiente' },
  'manual.decisions.title': { en: 'Decisions the manual is waiting for', es: 'Decisiones que el manual espera' },
  'manual.decisions.subtitle': { en: 'Every "decision needed" callout across the manual, with the chapter and section it sits in. A chapter states the question instead of inventing an answer.', es: 'Cada aviso de «decisión pendiente» del manual, con el capítulo y la sección donde está. Un capítulo plantea la pregunta en vez de inventar la respuesta.' },
  'manual.decisions.none': { en: 'No pending decisions in this language', es: 'No hay decisiones pendientes en este idioma' },
  'manual.decisions.captures': { en: 'Captures the manual still asks for', es: 'Capturas que el manual todavía pide' },
  'manual.decisions.inSection': { en: 'in {section}', es: 'en {section}' },
  'manual.callout.decision': { en: 'Decision needed', es: 'Decisión pendiente' },
  'manual.callout.inPerson': { en: 'In person', es: 'En persona' },
  'manual.callout.inCtlOs': { en: 'In CTL OS', es: 'En CTL OS' },
  'manual.callout.note': { en: 'Note', es: 'Nota' },
  'manual.callout.tip': { en: 'Tip', es: 'Consejo' },
  'manual.callout.warning': { en: 'Warning', es: 'Advertencia' },
  'manual.shotMissing': { en: 'Capture not taken yet', es: 'Captura aún no tomada' },
  'manual.shotOpen': { en: 'Open the page', es: 'Abrir la página' },

  'manual.live.badge': { en: 'Live', es: 'En vivo' },
  'manual.live.foot': { en: 'Live from the system — never typed into the chapter.', es: 'En vivo del sistema: nunca escrito en el capítulo.' },
  'manual.live.unknown': { en: 'will render a live block once this directive exists. Known directives: {options}.', es: 'mostrará un bloque en vivo cuando exista esta directiva. Directivas conocidas: {options}.' },
  'manual.live.roles.title': { en: 'Roles and what each one reaches', es: 'Roles y a qué llega cada uno' },
  'manual.live.roles.source': { en: 'Route manifest', es: 'Manifiesto de rutas' },
  'manual.live.roles.role': { en: 'Role', es: 'Rol' },
  'manual.live.roles.home': { en: 'Home', es: 'Inicio' },
  'manual.live.roles.screens': { en: 'Screens', es: 'Pantallas' },
  'manual.live.roles.permissions': { en: 'Permissions', es: 'Permisos' },
  'manual.live.routes.title': { en: 'Screens of the {surface} surface', es: 'Pantallas de la superficie {surface}' },
  'manual.live.routes.eyebrow': { en: '{n} screens, read from the running app', es: '{n} pantallas, leídas de la app en marcha' },
  'manual.live.routes.code': { en: 'Code', es: 'Código' },
  'manual.live.routes.screen': { en: 'Screen', es: 'Pantalla' },
  'manual.live.routes.route': { en: 'Route', es: 'Ruta' },
  'manual.live.routes.unknown': { en: 'will list the screens of a surface; "{arg}" is not one. Surfaces: {options}.', es: 'listará las pantallas de una superficie; «{arg}» no es una. Superficies: {options}.' },
  'manual.live.tables.title': { en: 'The {n} tables of the system', es: 'Las {n} tablas del sistema' },
  'manual.live.table.column': { en: 'Column', es: 'Columna' },
  'manual.live.table.type': { en: 'Type', es: 'Tipo' },
  'manual.live.table.notes': { en: 'Notes', es: 'Notas' },
  'manual.live.table.rls': { en: 'Who may read and write', es: 'Quién puede leer y escribir' },
  'manual.live.table.noRls': { en: 'No access intent recorded yet.', es: 'Aún no hay intención de acceso registrada.' },
  'manual.live.table.unknown': { en: 'will show a table; there is no table called "{arg}".', es: 'mostrará una tabla; no existe una tabla llamada «{arg}».' },
  'manual.live.rules.title': { en: '{n} rules the system enforces or displays', es: '{n} reglas que el sistema aplica o muestra' },
  'manual.live.rules.id': { en: 'Id', es: 'Id' },
  'manual.live.rules.rule': { en: 'Rule', es: 'Regla' },
  'manual.live.rules.authority': { en: 'Authority', es: 'Autoridad' },
  'manual.live.rules.status': { en: 'Status', es: 'Estado' },
  'manual.live.rules.verify': { en: 'not verified', es: 'sin verificar' },
  'manual.live.rules.unknown': { en: 'will list rules; "{arg}" is not a rule id or category.', es: 'listará reglas; «{arg}» no es un id ni una categoría de regla.' },
  'manual.live.offices.title': { en: '{n} regional offices', es: '{n} oficinas regionales' },
  'manual.live.offices.office': { en: 'Office', es: 'Oficina' },
  'manual.live.offices.city': { en: 'City', es: 'Ciudad' },
  'manual.live.offices.coverage': { en: 'Coverage', es: 'Cobertura' },
  'manual.live.offices.network': { en: 'network', es: 'red' },
  'manual.live.demoUsers.title': { en: '{n} demo people (all fictional)', es: '{n} personas demo (todas ficticias)' },
  'manual.live.demoUsers.person': { en: 'Person', es: 'Persona' },
  'manual.live.demoUsers.role': { en: 'Role', es: 'Rol' },
  'manual.live.demoUsers.home': { en: 'Home', es: 'Inicio' },
  'manual.live.pricing.stub': { en: 'show the price table read from the catalog tables, so no price is ever typed into a chapter', es: 'mostrar la tabla de precios leída de las tablas del catálogo, para que ningún precio se escriba en un capítulo' },
};
