import { useCallback, useMemo } from 'react';
import { useData, useTable } from '../../data/DataContext';
import { useSession } from '../../auth/SessionProvider';
import type { ManualProgressRow } from '../../data/schema/manual';
import type { Lang } from '../../i18n/types';

export interface ProgressApi {
  rows: ManualProgressRow[];
  /** Progress of one chapter for the person reading, or undefined when they have not touched it. */
  of: (slug: string) => ManualProgressRow | undefined;
  readCount: number;
  /** Writes one field of one chapter's row by id (inserting the row the first time). Idempotent per value. */
  set: (slug: string, lang: Lang, patch: Partial<Pick<ManualProgressRow, 'read' | 'in_person' | 'in_ctl_os'>>) => Promise<ManualProgressRow>;
}

/**
 * Reading progress through the provider (never component state): one `manual_progress` row per person per chapter,
 * written by id so a second tab or a second device cannot clobber it (P-14). The id is generated by the provider so
 * the row survives a demo reseed.
 */
export function useManualProgress(): ProgressApi {
  const data = useData();
  const { user } = useSession();
  const { rows } = useTable<ManualProgressRow>('manual_progress', { where: { user_id: user.id } });
  const byslug = useMemo(() => Object.fromEntries(rows.map((r) => [r.chapter_slug, r])), [rows]);

  const set = useCallback<ProgressApi['set']>(async (slug, lang, patch) => {
    const existing = rows.find((r) => r.chapter_slug === slug);
    const read_at = patch.read === false ? null : new Date().toISOString();
    if (existing) return data.update<ManualProgressRow>('manual_progress', existing.id, { ...patch, lang, read_at });
    return data.insert<ManualProgressRow>('manual_progress', {
      user_id: user.id, tenant_id: user.tenantId ?? undefined, chapter_slug: slug, lang,
      read: false, in_person: false, in_ctl_os: false, read_at, ...patch,
    });
  }, [data, rows, user.id, user.tenantId]);

  return { rows, of: (slug) => byslug[slug], readCount: rows.filter((r) => r.read).length, set };
}
