import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'hub.title': { en: 'CTL OS testing hub', es: 'Centro de pruebas CTL OS' },
  'hub.eyebrow': { en: 'California Tenant Law · operations system', es: 'California Tenant Law · sistema operativo' },
  'hub.subtitle': { en: 'Pick a surface, switch the demo user and try every role. Nothing here is real data; every person is fictional.', es: 'Elige una superficie, cambia el usuario demo y prueba cada rol. Nada aquí es real; todas las personas son ficticias.' },
  'hub.session': { en: 'Session', es: 'Sesión' },
  'hub.devModeOn': { en: 'Builder tool is on: every page shows a spec chip (bottom right) and Ctrl+. opens the inspector; placeholders show a dashed outline.', es: 'La herramienta de construcción está activa: cada página muestra su ficha (abajo a la derecha) y Ctrl+. abre el inspector; los marcadores muestran un borde discontinuo.' },
  'hub.surfaces': { en: 'Surfaces', es: 'Superficies' },
  'hub.enterAs': { en: 'Enter as {name}', es: 'Entrar como {name}' },
  'hub.open': { en: 'Open', es: 'Abrir' },
  'hub.codes': { en: 'Codes', es: 'Códigos' },
  'hub.footer.routes': { en: '{n} routes · {built} built · {stubs} stubs', es: '{n} rutas · {built} construidas · {stubs} pendientes' },
  'hub.footer.tables': { en: '{n} tables', es: '{n} tablas' },
  'hub.footer.rules': { en: '{n} rules', es: '{n} reglas' },
  'hub.footer.components': { en: '{n} components', es: '{n} componentes' },
  'hub.footer.actions': { en: '{n} actions', es: '{n} acciones' },
  'hub.footer.mock': { en: 'Mock data in this browser (localStorage). Demo people are fictional.', es: 'Datos simulados en este navegador (localStorage). Las personas demo son ficticias.' },
  'hub.surface.site': { en: 'Public website', es: 'Sitio público' }, 'hub.surface.site.body': { en: 'caltenantlaw.com rebuilt: eviction defense, services, free videos, offices, the consultation funnel and the proposal.', es: 'caltenantlaw.com renovado: defensa de desalojo, servicios, videos gratis, oficinas, el embudo de consultas y la propuesta.' },
  'hub.surface.app': { en: 'Client (tenant) app', es: 'App del cliente (inquilino)' }, 'hub.surface.app.body': { en: 'The tenant follows their case: deadlines, documents, the game board position, messages, store and hotline.', es: 'El inquilino sigue su caso: plazos, documentos, posición en el tablero, mensajes, tienda y línea directa.' },
  'hub.surface.desk': { en: 'Front desk', es: 'Recepción' }, 'hub.surface.desk.body': { en: 'Intake, consultations, hotline minutes, store orders and payments for one regional office.', es: 'Admisión, consultas, minutos de línea directa, pedidos de la tienda y pagos de una oficina regional.' },
  'hub.surface.counsel': { en: 'Attorneys', es: 'Abogados' }, 'hub.surface.counsel.body': { en: 'Cases, hearings, filings, opposing counsel and the case timeline for the regional attorney.', es: 'Casos, audiencias, escritos, abogado contrario y la línea de tiempo del caso para el abogado regional.' },
  'hub.surface.assist': { en: 'Assistants / paralegals', es: 'Asistentes legales' }, 'hub.surface.assist.body': { en: 'Drafting queue, deadlines, discovery, document assembly and checklists.', es: 'Cola de redacción, plazos, discovery, ensamblado de documentos y listas de verificación.' },
  'hub.surface.owner': { en: 'Owner', es: 'Propietario' }, 'hub.surface.owner.body': { en: 'The whole network: KPIs, offices, revenue, feedback inbox and decisions awaiting the principal.', es: 'Toda la red: indicadores, oficinas, ingresos, bandeja de comentarios y decisiones pendientes del titular.' },
  'hub.surface.admin': { en: 'Admin / settings', es: 'Administración / ajustes' }, 'hub.surface.admin.body': { en: 'Users, roles, tenants, rules, settings and the feedback triage.', es: 'Usuarios, roles, oficinas, reglas, ajustes y la revisión de comentarios.' },
  'hub.surface.opposition': { en: 'Opposing counsel portal', es: 'Portal del abogado contrario' }, 'hub.surface.opposition.body': { en: 'One case, shared documents and messages for the landlord side.', es: 'Un caso, documentos compartidos y mensajes para el lado del arrendador.' },
  'hub.surface.board': { en: 'Game board', es: 'Tablero del juego' }, 'hub.surface.board.body': { en: 'The unlawful-detainer flow as a board: squares, moves, time each move buys, and where a case stands.', es: 'El flujo del desalojo como tablero: casillas, movimientos, el tiempo que gana cada uno y dónde está el caso.' },
  'hub.surface.plan': { en: 'Project management', es: 'Gestión de proyectos' }, 'hub.surface.plan.body': { en: 'Kanban, decisions, changelog and the build plan of CTL OS itself, read from the docs tree.', es: 'Kanban, decisiones, changelog y plan de construcción de CTL OS, leídos del árbol de documentación.' },
  'hub.surface.manual': { en: 'Ops manual', es: 'Manual de operaciones' }, 'hub.surface.manual.body': { en: 'How the firm runs, per role, with live numbers from the system. Spanish first.', es: 'Cómo funciona el despacho, por rol, con cifras vivas del sistema. Español primero.' },
  'hub.surface.docs': { en: 'Docs & knowledge', es: 'Documentación y conocimiento' }, 'hub.surface.docs.body': { en: 'Everything in docs/: brief, principles, decisions, prompts, changelogs, page docs, legal memory.', es: 'Todo lo de docs/: brief, principios, decisiones, prompts, changelogs, fichas de página, memoria legal.' },
  'hub.surface.marketing': { en: 'Marketing engine', es: 'Motor de marketing' }, 'hub.surface.marketing.body': { en: 'City landing pages, videos, campaigns and the content calendar.', es: 'Páginas por ciudad, videos, campañas y el calendario de contenido.' },
  'hub.surface.dev': { en: 'Dev tools', es: 'Herramientas de desarrollo' }, 'hub.surface.dev.body': { en: 'Tokens, component library, page specs, table library, rules registry, route manifest and the actions registry. Super admin only.', es: 'Tokens, biblioteca de componentes, especificaciones, tablas, reglas, manifiesto de rutas y registro de acciones. Solo superadministrador.' },
  'hub.built': { en: 'Built', es: 'Construida' },
  'hub.stub': { en: 'Stub', es: 'Pendiente' },
  'hub.planned': { en: 'Planned', es: 'Planeada' },
  'hub.testing': { en: 'Testing hub', es: 'Centro de pruebas' },
  'hub.testingBody': { en: 'The tools that show the whole system at once: the canvas, the demo simulator, the plan, the board, the proposal, the docs, the manual, the legal memory and the builder tools.', es: 'Las herramientas que muestran todo el sistema a la vez: el lienzo, el simulador, el plan, el tablero, la propuesta, la documentación, el manual, la memoria legal y las herramientas de construcción.' },
  'hub.tool.planned': { en: 'open {name}', es: 'abrir {name}' },
  'hub.tool.canvas': { en: 'Canvas', es: 'Lienzo' },
  'hub.tool.canvas.body': { en: 'Every page laid out on one zoomable surface, each one live and usable', es: 'Todas las páginas en una superficie con zoom, cada una viva y usable' },
  'hub.tool.simulator': { en: 'Demo simulator', es: 'Simulador' },
  'hub.tool.simulator.body': { en: 'Phone to 4K TV frames, any role, either language, present mode and a tour', es: 'Marcos del teléfono a la TV 4K, cualquier rol, los dos idiomas, modo presentación y recorrido' },
  'hub.tool.plan': { en: 'Plan', es: 'Plan' },
  'hub.tool.plan.body': { en: 'Kanban, decisions, changelog and the build plan of CTL OS itself', es: 'Kanban, decisiones, changelog y el plan de construcción de CTL OS' },
  'hub.tool.board': { en: 'Game board', es: 'Tablero' },
  'hub.tool.board.body': { en: 'The eviction flow as a board, with the time each move buys', es: 'El flujo del desalojo como tablero, con el tiempo que gana cada movimiento' },
  'hub.tool.proposal': { en: 'Proposal', es: 'Propuesta' },
  'hub.tool.proposal.body': { en: 'What we are proposing to the firm, as a page', es: 'Lo que proponemos al despacho, como página' },
  'hub.tool.docs': { en: 'Docs', es: 'Documentación' },
  'hub.tool.docs.body': { en: 'Everything in docs/: principles, decisions, prompts, page docs, legal memory', es: 'Todo lo de docs/: principios, decisiones, prompts, fichas de página, memoria legal' },
  'hub.tool.manual': { en: 'Ops manual', es: 'Manual de operaciones' },
  'hub.tool.manual.body': { en: 'How the firm runs, per role, with live numbers', es: 'Cómo funciona el despacho, por rol, con cifras vivas' },
  'hub.tool.legal': { en: 'Legal memory', es: 'Memoria legal' },
  'hub.tool.legal.body': { en: 'The law we rely on, what changed and when it was last verified', es: 'La ley en la que nos basamos, qué cambió y cuándo se verificó' },
  'hub.tool.dev': { en: 'Dev tools', es: 'Herramientas de desarrollo' },
  'hub.tool.dev.body': { en: 'Tokens, components, specs, tables, rules, routes and the actions registry', es: 'Tokens, componentes, especificaciones, tablas, reglas, rutas y el registro de acciones' },
  'hub.footer.tasks': { en: '{done} of {total} tasks done', es: '{done} de {total} tareas hechas' },
  'noaccess.title': { en: 'This page is not available to your role', es: 'Esta página no está disponible para tu rol' },
  'noaccess.body': { en: 'You are {role}; {path} needs a different role. Switch the demo user in the hub.', es: 'Eres {role}; {path} necesita otro rol. Cambia el usuario demo en el centro.' },
  'noaccess.hub': { en: 'Back to the hub', es: 'Volver al centro' },
  'noaccess.home': { en: 'Go to my home', es: 'Ir a mi inicio' },
};
