import type { StringTable } from '../../i18n/types';
export const strings: StringTable = {
  'hub.title': { en: 'CTL OS testing hub', es: 'Centro de pruebas CTL OS' },
  'hub.eyebrow': { en: 'California Tenant Law · operations system', es: 'California Tenant Law · sistema operativo' },
  'hub.subtitle': { en: 'Pick a surface, switch the demo user and try every role. Nothing here is real data; every person is fictional.', es: 'Elige una superficie, cambia el usuario demo y prueba cada rol. Nada aquí es real; todas las personas son ficticias.' },
  'hub.session': { en: 'Session', es: 'Sesión' },
  'hub.devModeOn': { en: 'Builder tool is on: every page shows a spec chip (bottom right) and Ctrl+. opens the inspector; placeholders show a dashed outline.', es: 'La herramienta de construcción está activa: cada página muestra su ficha (abajo a la derecha) y Ctrl+. abre el inspector; los marcadores muestran un borde discontinuo.' },
  'hub.surfaces': { en: 'Surfaces', es: 'Superficies' },
  'hub.enterAs': { en: 'Enter as {name}', es: 'Entrar como {name}' },
  'hub.open': { en: 'Open', es: 'Abrir' },
  'hub.codes': { en: 'Codes', es: 'Códigos' },
  'hub.footer.mock': { en: 'Mock data in this browser (localStorage). Demo people are fictional.', es: 'Datos simulados en este navegador (localStorage). Las personas demo son ficticias.' },
  'hub.surface.site': { en: 'Public website', es: 'Sitio público' }, 'hub.surface.site.body': { en: 'caltenantlaw.com rebuilt: eviction defense, services, free videos, offices, the consultation funnel and the proposal.', es: 'caltenantlaw.com renovado: defensa de desalojo, servicios, videos gratis, oficinas, el embudo de consultas y la propuesta.' },
  'hub.surface.app': { en: 'Client (tenant) app', es: 'App del cliente (inquilino)' }, 'hub.surface.app.body': { en: 'The tenant follows their case: deadlines, documents, the game board position, messages, store and hotline.', es: 'El inquilino sigue su caso: plazos, documentos, posición en el tablero, mensajes, tienda y línea directa.' },
  'hub.surface.desk': { en: 'Front desk', es: 'Recepción' }, 'hub.surface.desk.body': { en: 'Intake, consultations, hotline minutes, store orders and payments for one regional office.', es: 'Admisión, consultas, minutos de línea directa, pedidos de la tienda y pagos de una oficina regional.' },
  'hub.surface.counsel': { en: 'Attorneys', es: 'Abogados' }, 'hub.surface.counsel.body': { en: 'Cases, hearings, filings, opposing counsel and the case timeline for the regional attorney.', es: 'Casos, audiencias, escritos, abogado contrario y la línea de tiempo del caso para el abogado regional.' },
  'hub.surface.assist': { en: 'Assistants / paralegals', es: 'Asistentes legales' }, 'hub.surface.assist.body': { en: 'Drafting queue, deadlines, discovery, document assembly and checklists.', es: 'Cola de redacción, plazos, discovery, ensamblado de documentos y listas de verificación.' },
  'hub.surface.owner': { en: 'Owner', es: 'Propietario' }, 'hub.surface.owner.body': { en: 'The whole network: KPIs, offices, revenue, feedback inbox and decisions awaiting the principal.', es: 'Toda la red: indicadores, oficinas, ingresos, bandeja de comentarios y decisiones pendientes del titular.' },
  'hub.surface.admin': { en: 'Admin / settings', es: 'Administración / ajustes' }, 'hub.surface.admin.body': { en: 'Users, roles, tenants, rules, settings and the feedback triage.', es: 'Usuarios, roles, oficinas, reglas, ajustes y la revisión de comentarios.' },
  'hub.surface.opposition': { en: 'Opposing counsel portal', es: 'Portal del abogado contrario' }, 'hub.surface.opposition.body': { en: 'One case, shared documents and messages for the landlord side.', es: 'Un caso, documentos compartidos y mensajes para el lado del arrendador.' },
  'hub.surface.board': { en: 'Game board', es: 'Tablero del juego' }, 'hub.surface.board.body': { en: 'The unlawful-detainer flow as a board: squares, moves, time each move buys, and where a case stands.', es: 'El flujo del desalojo como tablero: casillas, movimientos, el tiempo que gana cada uno y dónde está el caso.' },
  'hub.surface.plan': { en: 'Project management', es: 'Gestión de proyectos' }, 'hub.surface.plan.body': { en: 'Kanban, decisions, changelog and the build plan of CTL OS itself, read from the docs tree.', es: 'Kanban, decisiones, changelog y plan de construcción de CTL OS, leídos del árbol de documentación.' },
  'hub.surface.manual': { en: 'Ops manual', es: 'Manual de operaciones' }, 'hub.surface.manual.body': { en: 'How the firm runs, per role, with live numbers from the system. Spanish first.', es: 'Cómo funciona el despacho, por rol, con cifras vivas del sistema. Español primero.' },
  'hub.surface.docs': { en: 'Docs & knowledge', es: 'Documentación y conocimiento' }, 'hub.surface.docs.body': { en: 'Everything in docs/: brief, principles, decisions, prompts, changelogs, page docs, legal memory.', es: 'Todo lo de docs/: brief, principios, decisiones, prompts, changelogs, fichas de página, memoria legal.' },
  'hub.surface.marketing': { en: 'Marketing engine', es: 'Motor de marketing' }, 'hub.surface.marketing.body': { en: 'City landing pages, videos, campaigns and the content calendar.', es: 'Páginas por ciudad, videos, campañas y el calendario de contenido.' },
  'hub.surface.dev': { en: 'Dev tools', es: 'Herramientas de desarrollo' }, 'hub.surface.dev.body': { en: 'Tokens, component library, page specs, table library, rules registry, route manifest and the actions registry. Super admin only.', es: 'Tokens, biblioteca de componentes, especificaciones, tablas, reglas, manifiesto de rutas y registro de acciones. Solo superadministrador.' },
  'hub.built': { en: 'Built', es: 'Construida' },
  'hub.stub': { en: 'Stub', es: 'Pendiente' },
  'hub.planned': { en: 'Planned', es: 'Planeada' },
  'hub.tool.planned': { en: 'open {name}', es: 'abrir {name}' },
  'hub.tool.canvas': { en: 'Canvas', es: 'Lienzo' },
  'hub.tool.canvas.body': { en: 'Every page laid out on one zoomable surface, each one live and usable', es: 'Todas las páginas en una superficie con zoom, cada una viva y usable' },
  'hub.tool.simulator': { en: 'Demo simulator', es: 'Simulador' },
  'hub.tool.simulator.body': { en: 'Phone to 4K TV frames, any role, either language, present mode and a tour', es: 'Marcos del teléfono a la TV 4K, cualquier rol, los dos idiomas, modo presentación y recorrido' },
  'hub.tool.plan': { en: 'Plan', es: 'Plan' },
  'hub.tool.plan.body': { en: 'Kanban, decisions, changelog and the build plan of CTL OS itself', es: 'Kanban, decisiones, changelog y el plan de construcción de CTL OS' },
  'hub.tool.roles': { en: 'Role matrix', es: 'Matriz de roles' },
  'hub.tool.roles.body': { en: 'Every page against every role: who can open what, read from the route manifest', es: 'Cada página frente a cada rol: quién puede abrir qué, leído del manifiesto de rutas' },
  'hub.tool.proposal': { en: 'Proposal', es: 'Propuesta' },
  'hub.tool.proposal.body': { en: 'What we are proposing to the firm, as a page', es: 'Lo que proponemos al despacho, como página' },
  'hub.tool.docs': { en: 'Docs', es: 'Documentación' },
  'hub.tool.docs.body': { en: 'Everything in docs/: principles, decisions, prompts, page docs, legal memory', es: 'Todo lo de docs/: principios, decisiones, prompts, fichas de página, memoria legal' },
  'hub.tool.manual': { en: 'Ops manual', es: 'Manual de operaciones' },
  'hub.tool.manual.body': { en: 'How the firm runs, per role, with live numbers', es: 'Cómo funciona el despacho, por rol, con cifras vivas' },
  'hub.tool.legal': { en: 'Legal memory', es: 'Memoria legal' },
  'hub.tool.legal.body': { en: 'The law we rely on, what changed and when it was last verified', es: 'La ley en la que nos basamos, qué cambió y cuándo se verificó' },
  'hub.tool.dev': { en: 'Dev tools', es: 'Herramientas de desarrollo' },
  'hub.tool.dev.body': { en: 'Tokens, components, specs, tables, rules, routes and the actions registry', es: 'Tokens, componentes, especificaciones, tablas, reglas, rutas y el registro de acciones' },
  'noaccess.title': { en: 'This page is not available to your role', es: 'Esta página no está disponible para tu rol' },
  'noaccess.body': { en: 'You are {role}; {path} needs a different role. Switch the demo user in the hub.', es: 'Eres {role}; {path} necesita otro rol. Cambia el usuario demo en el centro.' },
  'noaccess.hub': { en: 'Back to the hub', es: 'Volver al centro' },
  'noaccess.home': { en: 'Go to my home', es: 'Ir a mi inicio' },
  // design pass (mod/design): hero, audience groups, card chips and the stat strip
  'hub.promise': { en: 'One system for every seat at the firm: tenants, front desk, attorneys, the owner and the people who build it.', es: 'Un sistema para cada puesto del despacho: inquilinos, recepción, abogados, el titular y quienes lo construyen.' },
  'hub.tagline': { en: 'Your cloudy day is about to clear up.', es: 'Tu día nublado está por despejarse.' },
  'hub.group.run': { en: 'Run the firm', es: 'Operar el despacho' }, 'hub.group.run.title': { en: 'Every seat that does the work', es: 'Cada puesto que hace el trabajo' }, 'hub.group.run.body': { en: 'Attorneys, paralegals, the front desk, the owner and settings: one staff shell whose menu is filtered per role, so every seat sees its own work and nothing else.', es: 'Abogados, asistentes legales, recepción, el titular y los ajustes: un mismo marco cuyo menú se filtra por rol, para que cada puesto vea su trabajo y nada más.' },
  'hub.group.clients': { en: 'Clients', es: 'Clientes' }, 'hub.group.clients.title': { en: 'What a tenant sees', es: 'Lo que ve el inquilino' }, 'hub.group.clients.body': { en: 'The app that follows their case, the website and store that brought them in, the eviction game board that explains every move, and the videos that teach the next step.', es: 'La app que acompaña su caso, el sitio y la tienda que los trajo, el tablero del desalojo que explica cada movimiento y los videos que enseñan el siguiente paso.' },
  'hub.group.build': { en: 'Build & review', es: 'Construir y revisar' }, 'hub.group.build.title': { en: 'See the whole system at once', es: 'Ver todo el sistema a la vez' }, 'hub.group.build.body': { en: 'The plan, the proposal, the canvas, the demo simulator, the documentation, the ops manual, the legal memory, the builder tools and the role matrix.', es: 'El plan, la propuesta, el lienzo, el simulador, la documentación, el manual de operaciones, la memoria legal, las herramientas de construcción y la matriz de roles.' },
  'hub.group.outside': { en: 'Outside parties & marketing', es: 'Terceros y marketing' }, 'hub.group.outside.title': { en: 'People who are not the firm', es: 'Quienes no son del despacho' }, 'hub.group.outside.body': { en: 'The landlord\'s attorney gets one case and nothing else; marketing works the city pages, videos and campaigns.', es: 'El abogado del arrendador ve un solo caso y nada más; marketing trabaja las páginas por ciudad, los videos y las campañas.' },
  'hub.enter': { en: 'Enter', es: 'Entrar' },
  'hub.inProgress': { en: 'In progress', es: 'En construcción' },
  'hub.you': { en: 'You are here', es: 'Estás aquí' },
  'hub.stat.tasks': { en: 'of {total} tasks done', es: 'de {total} tareas hechas' },
  'hub.stat.routes': { en: 'routes', es: 'rutas' }, 'hub.stat.built': { en: 'built', es: 'construidas' }, 'hub.stat.tables': { en: 'tables', es: 'tablas' }, 'hub.stat.rules': { en: 'rules', es: 'reglas' }, 'hub.stat.components': { en: 'components', es: 'componentes' }, 'hub.stat.actions': { en: 'actions', es: 'acciones' },

  // pass 2 wave A (prompt 0006, T-123): hub order, per-role surfaces, one-line "what this role does", live counts
  'hub.surface.learn': { en: 'Learning', es: 'Aprendizaje' }, 'hub.surface.learn.body': { en: 'The firm\'s 36 videos as a course: what to watch for the stage the case is at.', es: 'Los 36 videos del despacho como curso: qué ver para la etapa en la que está el caso.' },
  'hub.does.counsel': { en: 'Runs the cases: the document pipeline, hearings, filings and the other side.', es: 'Lleva los casos: el flujo de documentos, audiencias, escritos y la parte contraria.' },
  'hub.does.assist': { en: 'Gathers, drafts, assembles, files and serves; keeps the deadlines honest.', es: 'Reúne, redacta, ensambla, presenta y notifica; cuida los plazos.' },
  'hub.does.desk': { en: 'Answers the phone, takes intake, books consultations and chases what clients owe us.', es: 'Contesta el teléfono, toma la admisión, agenda consultas y persigue lo que falta del cliente.' },
  'hub.does.owner': { en: 'Watches the whole network: what is late, what is earning, what needs a decision.', es: 'Vigila toda la red: qué va tarde, qué genera ingresos, qué necesita una decisión.' },
  'hub.does.admin': { en: 'Sets up people, roles, offices, rules and settings, and triages tester feedback.', es: 'Configura personas, roles, oficinas, reglas y ajustes, y revisa los comentarios de los probadores.' },
  'hub.does.app': { en: 'The tenant follows their case, answers what we ask and pays, from their phone.', es: 'El inquilino sigue su caso, responde lo que pedimos y paga, desde su teléfono.' },
  'hub.does.site': { en: 'How a tenant finds the firm, learns the law and buys the document they need.', es: 'Cómo un inquilino encuentra al despacho, aprende la ley y compra el documento que necesita.' },
  'hub.does.board': { en: 'The eviction as a board: every square, every move and the time it buys.', es: 'El desalojo como tablero: cada casilla, cada movimiento y el tiempo que gana.' },
  'hub.does.learn': { en: 'The videos, in order, for where the case actually is.', es: 'Los videos, en orden, para el punto real del caso.' },
  'hub.does.opposition': { en: 'The landlord\'s attorney sees one case: served documents and messages, nothing else.', es: 'El abogado del arrendador ve un solo caso: documentos notificados y mensajes, nada más.' },
  'hub.does.marketing': { en: 'City pages, videos, campaigns and the content calendar.', es: 'Páginas por ciudad, videos, campañas y el calendario de contenido.' },
  'hub.startHere': { en: 'Start here', es: 'Empieza aquí' },
  'hub.start.pipeline': { en: 'Enter as attorney: the document pipeline', es: 'Entrar como abogado: el flujo de documentos' },
  'hub.start.calls': { en: 'Front desk: take a call', es: 'Recepción: atender una llamada' },
  'hub.start.orders': { en: 'Client: my orders', es: 'Cliente: mis pedidos' },
  'hub.moreSurfaces': { en: '+{n} more', es: '+{n} más' },
  'hub.stat.waitingOnClient': { en: 'orders waiting on a client', es: 'pedidos esperando al cliente' },
  'hub.stat.waitingOnParalegal': { en: 'orders on the paralegal', es: 'pedidos en manos del asistente' },
  'hub.stat.callsToReturn': { en: 'calls to return', es: 'llamadas por devolver' },
  'hub.stat.followUpsOpen': { en: 'follow-ups open', es: 'seguimientos abiertos' },
  'hub.stat.requestsWaiting': { en: 'requests waiting on you', es: 'solicitudes que te esperan' },
  // menu-group labels for the per-role page lists (src/app/navGroups.ts is English only and shared)
  'hub.navgroup.overview': { en: 'Overview', es: 'Resumen' },
  'hub.navgroup.intake': { en: 'Intake & consultations', es: 'Admisión y consultas' },
  'hub.navgroup.cases': { en: 'Cases', es: 'Casos' },
  'hub.navgroup.calendar': { en: 'Deadlines & hearings', es: 'Plazos y audiencias' },
  'hub.navgroup.documents': { en: 'Documents & filings', es: 'Documentos y escritos' },
  'hub.navgroup.board': { en: 'Game board', es: 'Tablero' },
  'hub.navgroup.clients': { en: 'Clients', es: 'Clientes' },
  'hub.navgroup.opposition': { en: 'Opposing counsel', es: 'Abogado contrario' },
  'hub.navgroup.store': { en: 'Store & payments', es: 'Tienda y pagos' },
  'hub.navgroup.messages': { en: 'Messages & hotline', es: 'Mensajes y línea directa' },
  'hub.navgroup.marketing': { en: 'Marketing', es: 'Marketing' },
  'hub.navgroup.reports': { en: 'Reports', es: 'Informes' },
  'hub.navgroup.plan': { en: 'Projects & plan', es: 'Proyectos y plan' },
  'hub.navgroup.settings': { en: 'Settings', es: 'Ajustes' },
  'hub.navgroup.manual': { en: 'Ops manual', es: 'Manual de operaciones' },
  'hub.navgroup.developer': { en: 'Developer', es: 'Desarrollo' },
  'hub.navgroup.docs': { en: 'Docs', es: 'Documentación' },
  'hub.navgroup.customer': { en: 'Client app', es: 'App del cliente' },

  // prompt 0007 (2026-09-20): visual explorations linked from the hub (docs/data/visual-explorations.json, D-053)
  'hub.group.explore': { en: 'Visual explorations', es: 'Exploraciones visuales' },
  'hub.group.explore.title': { en: 'Looks and ideas we are pointing at', es: 'Estilos e ideas que tomamos como referencia' },
  'hub.group.explore.body': { en: 'Concept sites made outside this codebase to explore how CTL OS could look. Each one opens in a new tab and is labelled external; nothing here is part of the build.', es: 'Sitios de concepto hechos fuera de este código para explorar cómo podría verse CTL OS. Cada uno se abre en una pestaña nueva y está marcado como externo; nada de esto forma parte de la construcción.' },
  'hub.explore.external': { en: 'External', es: 'Externo' },
  'hub.explore.opens': { en: 'Opens in a new tab', es: 'Se abre en una pestaña nueva' },
  'hub.explore.note': { en: '{note}. Added {date} by {author}.', es: '{note}. Añadido el {date} por {author}.' },
};
