// Writes docs/specs.md (every route, code, surface, status, completeness) from docs/screenshots/routes.json,
// which scripts/screenshots.mjs saves from the running app (window.__ctl.routes). Run screenshots first.
import { readFileSync, writeFileSync } from 'node:fs';
let routes;
try { routes = JSON.parse(readFileSync(new URL('../docs/screenshots/routes.json', import.meta.url), 'utf8')); } catch { console.error('docs/screenshots/routes.json missing - run npm run screenshots first'); process.exit(1); }
const score = (s) => { const checks = [!!s.purpose, s.layout.length > 0, s.data.length > 0, s.roles.length > 0, s.logic.length > 0, s.components.length > 0, !!s.rules?.length, !!s.states?.length, Array.isArray(s.actions) && (s.actions.length > 0 || (s.notes ?? []).some((n) => /no actions/i.test(n)))]; return Math.round((checks.filter(Boolean).length / checks.length) * 100); };
let md = `# Page specs\n\n_Generated by \`npm run specs\` from the route manifest. ${routes.length} routes, ${routes.filter((r) => r.status === 'built').length} built._\n\n| Code | Page | Route | Surface | Status | Spec | Actions | Rules | Roles |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n`;
for (const r of [...routes].sort((a, b) => a.code.localeCompare(b.code, undefined, { numeric: true }))) md += `| \`${r.code}\` | ${r.spec.name} | \`#${r.path}\` | ${r.surface} | ${r.status} | ${score(r.spec)}% | ${(r.spec.actions ?? []).map((a) => `\`${a.id}\``).join(', ')} | ${(r.spec.rules ?? []).join(', ')} | ${r.roles.join(', ')} |\n`;
writeFileSync(new URL('../docs/specs.md', import.meta.url), md);
console.log(`wrote docs/specs.md (${routes.length} routes)`);
