import { createElement as h } from 'react';
import { defineMeta } from '../../../design/meta';
import { DeviceFrame } from './DeviceFrame';
export default defineMeta({
  tier: 'organism', name: 'DeviceFrame', description: 'The app at a device viewport (phone 390, tablet 768, desktop 1280, 4K TV 3840, or any size) inside a same-origin iframe: the page lays out at that viewport and is transform-scaled to fill the stage edge to edge, which keeps its aspect ratio and crops rather than letterboxes. A hairline + inner-shadow edge makes the frame read in dark mode. With `chrome` it draws the hardware around the screen (phone bezel + dynamic island + home indicator, tablet bezel + camera, laptop bezel + hinge + keyboard deck, monitor bezel + stand, TV bezel + feet) so a demo is recognisably on the device it represents (D-050); the chrome is decoration and never changes the viewport the page sees. The hub previews, the canvas and the simulator use it; pages can inspect the framed document.',
  props: [{ name: 'route', type: 'string', required: true, description: 'Hash route to render' }, { name: 'device', type: "'phone'|'tablet'|'desktop'|'tv'", default: 'desktop', description: 'Preset' }, { name: 'width/height', type: 'number', description: 'Override the preset' }, { name: 'viewport', type: '{ width, height }', description: 'CSS viewport the page renders at; wins over device / width / height' }, { name: 'fit', type: 'boolean', default: 'true', description: 'Scale down to the stage width' }, { name: 'aspect', type: 'number', description: 'Stage width / height; default the viewport ratio. Wider crops the page at the bottom' }, { name: 'caption', type: 'boolean', default: 'true', description: 'Label + width badge row' }, { name: 'edge', type: 'boolean', default: 'true', description: 'Hairline + inner shadow over the stage' }, { name: 'chrome', type: "'none'|'phone'|'tablet'|'laptop'|'monitor'|'tv'", default: "'none'", description: 'Draw the device around the screen' }, { name: 'chromeNote', type: 'string', description: 'One translated line under a chromed device, e.g. "10-foot view"' }, { name: 'onLoad', type: '(doc) => void', description: 'Framed document' }],
  states: ['loading', 'scaled to the stage', 'full size', 'cropped (wider aspect)', 'chromed (phone / tablet / laptop / monitor / TV)'],
  usages: [
    { title: 'Tablet preset', render: () => h('div', { style: { maxWidth: 420 } }, h(DeviceFrame, { route: '/no-access', device: 'tablet', height: 520 })) },
    { title: 'Desktop viewport in a 300 px card, no caption', render: () => h('div', { style: { maxWidth: 300 } }, h(DeviceFrame, { route: '/no-access', viewport: { width: 1280, height: 800 }, caption: false })) },
    { title: 'Phone chrome (bezel, island, home indicator)', render: () => h('div', { style: { maxWidth: 260 } }, h(DeviceFrame, { route: '/no-access', device: 'phone', caption: false, chrome: 'phone' })) },
    { title: 'Laptop chrome (hinge + keyboard deck)', render: () => h('div', { style: { maxWidth: 420 } }, h(DeviceFrame, { route: '/no-access', width: 1280, height: 800, caption: false, chrome: 'laptop' })) },
    { title: 'TV chrome with the 10-foot caption', render: () => h('div', { style: { maxWidth: 460 } }, h(DeviceFrame, { route: '/no-access', width: 3840, height: 2160, caption: false, chrome: 'tv', chromeNote: '10-foot view' })) },
  ],
  a11y: ['iframe carries a title with the route and width.', 'The chrome is decorative: every bezel, island, deck, stand and foot is aria-hidden and not focusable.'],
  usedBy: ['HUB-01', 'D-21', 'D-22'],
});
