import type { StringTable } from '../../i18n/types';

/** K-01..K-03. Keys namespaced `docs.`; Spanish where known, English fallback otherwise (P-13). */
export const strings: StringTable = {
  'docs.title': { en: 'Docs & knowledge', es: 'Documentación y conocimiento' },
  'docs.subtitle': { en: 'Every markdown file under docs/ rendered in-app: the brief, the principles, the plan, the decisions, the prompts, the changelog, the page docs, the legal memory and the ops manual. The tree is built at build time; a body loads when you open it.', es: 'Todos los archivos markdown de docs/ dentro de la app: el brief, los principios, el plan, las decisiones, los prompts, el changelog, las fichas de página, la memoria legal y el manual. El árbol se construye en la compilación; el cuerpo se carga al abrir.' },
  'docs.tree': { en: 'Docs tree', es: 'Árbol de documentación' },
  'docs.treeToggle': { en: 'Show the docs tree', es: 'Mostrar el árbol' },
  'docs.pick': { en: 'Pick a document', es: 'Elegir un documento' },
  'docs.outline': { en: 'On this page', es: 'En esta página' },
  'docs.outlineJump': { en: 'Jump to a section', es: 'Ir a una sección' },
  'docs.outlineEmpty': { en: 'No sections in this document.', es: 'Este documento no tiene secciones.' },
  'docs.loading': { en: 'Loading the document…', es: 'Cargando el documento…' },
  'docs.notFound': { en: 'No document at that path', es: 'No hay documento en esa ruta' },
  'docs.notFoundBody': { en: 'The tree on the left lists every file under docs/. This link may point at a file that has not been written yet.', es: 'El árbol de la izquierda lista todos los archivos de docs/. Este enlace puede apuntar a un archivo que aún no existe.' },
  'docs.prev': { en: 'Previous', es: 'Anterior' },
  'docs.next': { en: 'Next', es: 'Siguiente' },
  'docs.decisions': { en: '{n} decisions needed', es: '{n} decisiones pendientes' },
  'docs.decisionsOne': { en: '1 decision needed', es: '1 decisión pendiente' },
  'docs.decisionsHint': { en: '> DECISION NEEDED callouts across the docs tree; the ops manual lists its own at /manual/decisions.', es: 'Avisos «DECISION NEEDED» en todo el árbol; el manual lista los suyos en /manual/decisions.' },
  'docs.words': { en: '{n} words', es: '{n} palabras' },
  'docs.openSearch': { en: 'Search the docs', es: 'Buscar en la documentación' },
  'docs.openPlanLog': { en: 'Plan log', es: 'Registro del plan' },
  'docs.shotMissing': { en: 'Capture not taken yet', es: 'Captura aún no tomada' },
  'docs.shotOpen': { en: 'Open the page', es: 'Abrir la página' },
  'docs.shotFolder': { en: 'Captures for {code}', es: 'Capturas de {code}' },
  'docs.count': { en: '{n} documents', es: '{n} documentos' },

  'docs.group.root': { en: 'Start here', es: 'Empieza aquí' },
  'docs.group.prompts': { en: 'Prompts (verbatim)', es: 'Prompts (literales)' },
  'docs.group.changelog': { en: 'Changelog', es: 'Registro de cambios' },
  'docs.group.pages': { en: 'Page docs', es: 'Fichas de página' },
  'docs.group.reference': { en: 'Reference', es: 'Referencia' },
  'docs.group.legal': { en: 'Legal memory', es: 'Memoria legal' },
  'docs.group.game-board': { en: 'Game board', es: 'Tablero del juego' },
  'docs.group.ops-manual': { en: 'Ops manual', es: 'Manual de operaciones' },
  'docs.group.plan': { en: 'Plan data', es: 'Datos del plan' },
  'docs.group.qa': { en: 'QA reports', es: 'Informes de QA' },
  'docs.group.screenshots': { en: 'Screenshots', es: 'Capturas' },

  'docs.search.title': { en: 'Knowledge search', es: 'Búsqueda de conocimiento' },
  'docs.search.subtitle': { en: 'Titles and headings are indexed at build time, so they answer instantly; the bodies load in the background and widen the search to full text with snippets.', es: 'Los títulos y encabezados se indexan en la compilación y responden al instante; los cuerpos se cargan en segundo plano y amplían la búsqueda al texto completo con fragmentos.' },
  'docs.search.label': { en: 'Search every doc', es: 'Buscar en todos los documentos' },
  'docs.search.placeholder': { en: 'statute, deadline, kanban, AB 2347…', es: 'ley, plazo, kanban, AB 2347…' },
  'docs.search.folder': { en: 'Folder', es: 'Carpeta' },
  'docs.search.allFolders': { en: 'Every folder', es: 'Todas las carpetas' },
  'docs.search.results': { en: '{n} documents match', es: '{n} documentos coinciden' },
  'docs.search.none': { en: 'Nothing matched', es: 'Sin coincidencias' },
  'docs.search.noneBody': { en: 'Try fewer words, or a statute number like 1167.', es: 'Prueba con menos palabras o con un número de ley como 1167.' },
  'docs.search.empty': { en: 'Type to search', es: 'Escribe para buscar' },
  'docs.search.emptyBody': { en: 'Every title and heading in the docs tree is already indexed; bodies join the search as they load.', es: 'Cada título y encabezado ya está indexado; los cuerpos se suman a medida que cargan.' },
  'docs.search.bodies': { en: 'Full text ready for {done} of {total} documents', es: 'Texto completo listo en {done} de {total} documentos' },
  'docs.search.inTitle': { en: 'title', es: 'título' },
  'docs.search.inHeading': { en: 'heading', es: 'encabezado' },
  'docs.search.inBody': { en: 'body', es: 'cuerpo' },
  'docs.search.keys': { en: 'Up and down move through the results, Enter opens one.', es: 'Arriba y abajo recorren los resultados, Enter abre uno.' },

  'docs.log.title': { en: 'Plan log', es: 'Registro del plan' },
  'docs.log.subtitle': { en: 'Prompts, changelog entries and decisions as one chronological record of how CTL OS got here: what was asked, what changed and why.', es: 'Prompts, entradas del changelog y decisiones como un único registro cronológico de cómo llegó CTL OS hasta aquí: qué se pidió, qué cambió y por qué.' },
  'docs.log.kind.all': { en: 'Everything', es: 'Todo' },
  'docs.log.kind.prompt': { en: 'Prompts', es: 'Prompts' },
  'docs.log.kind.changelog': { en: 'Changelog', es: 'Changelog' },
  'docs.log.kind.decision': { en: 'Decisions', es: 'Decisiones' },
  'docs.log.filter': { en: 'Pass or code', es: 'Pasada o código' },
  'docs.log.filterPlaceholder': { en: 'K-01, 0.1.0, D-019…', es: 'K-01, 0.1.0, D-019…' },
  'docs.log.entries': { en: '{n} entries', es: '{n} entradas' },
  'docs.log.pending': { en: 'Pending draft', es: 'Borrador pendiente' },
  'docs.log.decision': { en: 'Decision', es: 'Decisión' },
  'docs.log.prompt': { en: 'Prompt', es: 'Prompt' },
  'docs.log.open': { en: 'Open the document', es: 'Abrir el documento' },
  'docs.log.none': { en: 'Nothing matches that filter', es: 'Nada coincide con ese filtro' },
  'docs.log.codes': { en: 'Codes', es: 'Códigos' },
};
