import type { StringTable } from '../../i18n/types';

export const strings: StringTable = {
  'opposition.title': { en: 'Shared matters', es: 'Asuntos compartidos' },
  'opposition.sub': { en: 'The matters on which you have been served, the documents served on you, meet-and-confer requests and the hearings ahead.', es: 'Los asuntos en los que se le ha notificado, los documentos que se le han notificado, las solicitudes de conciliación y las audiencias próximas.' },
  'opposition.cases': { en: 'Matters', es: 'Asuntos' },
  'opposition.served': { en: 'Documents served on you', es: 'Documentos notificados a usted' },
  'opposition.meetConfer': { en: 'Meet and confer', es: 'Conciliación (meet and confer)' },
  'opposition.hearings': { en: 'Upcoming hearings', es: 'Audiencias próximas' },
  'opposition.acknowledge': { en: 'Acknowledge receipt', es: 'Acusar recibo' },
  'opposition.acknowledged': { en: 'Acknowledged', es: 'Acusado' },
  'opposition.awaiting': { en: 'Awaiting acknowledgement', es: 'Pendiente de acuse' },
  'opposition.respond': { en: 'Respond', es: 'Responder' },
  'opposition.download': { en: 'Download', es: 'Descargar' },
  'opposition.noCases': { en: 'No matters are shared with you.', es: 'No hay asuntos compartidos con usted.' },
  'opposition.noServed': { en: 'Nothing has been served on you.', es: 'No se le ha notificado nada.' },
  'opposition.noMeetConfer': { en: 'No meet-and-confer requests.', es: 'No hay solicitudes de conciliación.' },
  'opposition.noHearings': { en: 'No hearings on the calendar.', es: 'No hay audiencias en el calendario.' },
  'opposition.matter': { en: 'Matter', es: 'Asunto' },
  'opposition.caseNumber': { en: 'Case number', es: 'N.º de caso' },
  'opposition.court': { en: 'Court', es: 'Corte' },
  'opposition.attorney': { en: 'Attorney of record', es: 'Abogado de registro' },
  'opposition.document': { en: 'Document', es: 'Documento' },
  'opposition.method': { en: 'Method of service', es: 'Método de notificación' },
  'opposition.servedOn': { en: 'Served', es: 'Notificado' },
  'opposition.topic': { en: 'Topic', es: 'Tema' },
  'opposition.status': { en: 'Status', es: 'Estado' },
  'opposition.scope': { en: 'You see only what has been served on you or shared for conferral.', es: 'Solo ve lo que se le ha notificado o lo que se ha compartido para conciliar.' },
};
